### ISSUE TITLE
Mouse moving speed

### ISSUE THREAD

**Issue by HenryXiaoYang** [cabaletta/baritone#3727] opened 2022-11-13 06:05 UTC
## Describe your suggestion
Currently, mouse moves instantly. Thus, please make a setting that makes the mouse go slower.

## Settings
A set of number that sets the move speed of mouse.

## Context
If the speed of mouse can be set, baritone will like a real player is actually controlling the game.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-11-13 22:17
Duplicate of #2034

**Closed by ZacSharp** 2022-11-13 22:17 UTC
Labels: duplicate, enhancement
