### ISSUE TITLE
#build Storage

### ISSUE THREAD

**Issue by enderson0** [cabaletta/baritone#2175] opened 2020-11-12 00:16 UTC
## Describe your suggestion
The idea is for resource intensive schematics, lots have waay too many items for your inventory so basically make a storage and when your inventory empties the bot goes back to the storage, restocks on items and continues building where it left off

## Settings
#storage true  / false
#restock
#restock mode current / next
#restock context current / future
#storage set
## Context
I'm tired of making multiple schematics for 1 build because of how many materials it needs and needing to make a tower to start #build from so I hope you can add this

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by enderson0** [comment] 2020-11-12 01:24
This isnt storage for mining, this is storage for schematic materials. Please re open i havent seen anything about this in search

**Comment by l1ving** [comment] 2020-11-12 03:06
It would apply to all processes but okay :roll_eyes:

**Comment by me-rgb** [comment] 2020-12-02 19:00
plz add this :O

**Comment by scorbett123** [comment] 2021-10-30 14:06
Duplicate of #1098

**Closed by scorbett123** 2021-10-30 14:06 UTC
Labels: enhancement
