### ISSUE TITLE
NoFailFarm setting

### ISSUE THREAD

**Issue by LunarN0v4** [cabaletta/baritone#4075] opened 2023-07-28 10:16 UTC
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
Stops Baritone from failing in farming.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
NoFailFarm - Disables failing while farming, if no crops are found, it waits for an endless amount of time or until the user cancels the task

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
It would improve Baritone by allowing players to afk farm constantly without needing to check whether they need to run "farm" again.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] This is not a shitty suggestion

**Comment by ZacSharp** [comment] 2023-07-29 03:05
Duplicate of #893

**Closed by ZacSharp** 2023-07-29 03:05 UTC
Labels: duplicate, enhancement
