### ISSUE TITLE
how to disable the thing which shows while mining

### ISSUE THREAD

**Issue by eXpertdUst19** [cabaletta/baritone#2820] opened 2021-06-18 19:09 UTC
how to disable the thing which show the ores are and which block it will gousingwile mining

# set rendergoal false does not work

**Comment by ZacSharp** [comment] 2021-06-18 20:37
`#renderGoal false` turns off the green boxes
`#renderPath false` turns off the red line
Don't open another duplicate, you won't get a better answer unless you give us something to work with (a video of it not working would be nice)

**Comment by ZacSharp** [comment] 2021-06-18 20:37
Duplicate of #2818

**Closed by ZacSharp** 2021-06-18 20:37 UTC
Labels: question
