### ISSUE TITLE
Automaticly close the doors after went through

### ISSUE THREAD

**Issue by szdytom** [cabaletta/baritone#4129] opened 2023-09-05 00:04 UTC
## Describe your suggestion

Baritone can open doors and fence gates on its path, I want it to be able to close those opened doors after going through

## Settings

set `requireCloseDoor` to enable automatic door closing

## Context

Here is my use case:
I have divided my base into several areas using fences to prevent mob entering it. As I used baritone pathing between those areas, it always left those fence gates open.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-09-05 12:26
Duplicate of #389

**Closed as completed by ZacSharp** 2023-09-05 12:26 UTC
Labels: duplicate, enhancement
