### ISSUE TITLE
Suggestion: Branch Mining/Strip Mining Process

### ISSUE THREAD

**Issue by CptDinosaur** [cabaletta/baritone#1440] opened 2020-03-24 13:09 UTC
## Describe your suggestion
Add a process (i.e. #stripMine, #branchMine or other) to combine tunnel and legitmine.
Mine tunnels in a pattern like so:
![image](https://user-images.githubusercontent.com/26852749/77428302-c50f6600-6dcf-11ea-9749-d8ace4bb3d63.png)
![image](https://user-images.githubusercontent.com/26852749/77428795-95149280-6dd0-11ea-8ea4-5cfc8c6e6f88.png)

or, for more repeatability:
![image](https://user-images.githubusercontent.com/26852749/77428321-cd67a100-6dcf-11ea-8f2e-086c1334bb62.png)

When ores are made visible, mine them and continue pattern.

Preferably, smooth mouse movements.
If possible, add auto-torching too.
## Settings
- y-level
- Ignored Ores
- Diagonal Mining
- Tunnel Spacing
- Branch or strip mine
- For branch, poke holes or 2 high tunnels every x blocks.

## Context
This creates the most legit of legitmines. The bot can be left to afk, mining automatically in a way which isn't bannable. Branch mining mimics normal player movement.
Most code is already in place, schematics/mine/tunnel.

Something similar has already been made as a pull request, but never met checks to be implemented:
https://github.com/cabaletta/baritone/pull/877

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment] 2020-03-24 13:23
Instead of ignored ores, have the same setting as `#mine` does.

**Comment by twans0** [comment] 2020-03-26 23:12
this is the best idea yet!

**Comment by scorbett123** [comment] 2021-05-02 19:50
Duplicate of #773

**Closed by scorbett123** 2021-05-02 19:50 UTC
Labels: enhancement
