### ISSUE TITLE
baritone doesnt find anything

### ISSUE THREAD

**Issue by DaOberhammer** [cabaletta/baritone#4194] opened 2023-11-16 08:57 UTC
## Some information
Operating system: Windows 11 Pro
Java version: Build 1.8.0_391-b13
Minecraft version: 1.20.2
Baritone version: Baritone-Client-Mod-Meteor-Fabric-1.20.2
Other mods (if used): 
-iris-mc1.20.2-1.6.10
-Jade-1.20.2-fabric-12.2.1
-sodium-fabric-mc1.20.2-0.5.3
-Xaeros_Minimap_23.8.4_Fabric_1.20.2

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Open the game, and do #mine minecraft:diamond_ore minecraft:deepslate_dimaond_ore

## Modified settings
nothing, i put the randomtickspeed to 70

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

[latest.log](https://github.com/cabaletta/baritone/files/13374451/latest.log)

**Comment by ZacSharp** [comment] 2023-11-16 21:40
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-11-16 21:40 UTC
Labels: bug, duplicate
