### ISSUE TITLE
Maybe a "stripmine" command?

### ISSUE THREAD

**Issue by SupaGamer2017** [cabaletta/baritone#2930] opened 2021-08-09 14:22 UTC
I was thinking of a feature that would automatically strip mine in such a way that it would find the perfect place to strip mine to find the most ores, just to not look suspicious on non-anarchy servers. Sorry, I can't figure out how to label this as a suggestion.

**Comment by Yertled** [comment] 2021-08-09 15:07
+1

**Comment by Schweeeeeeeeeeeeeeee** [comment] 2021-08-09 18:11
pls

**Comment by Schweeeeeeeeeeeeeeee** [comment] 2021-08-09 18:28
but its a duplicate #1440

**Comment by ZacSharp** [comment] 2021-08-09 19:38
Duplicate of #773

**Closed by ZacSharp** 2021-08-09 19:38 UTC
Labels: duplicate, enhancement

**Comment by Schweeeeeeeeeeeeeeee** [comment] 2021-08-09 20:32
ZacSharp 
i think u were going to accually do this are u going to work on this anytime soon?

**Comment by ZacSharp** [comment] 2021-08-09 22:19
I already had some attempts before I started working on Baritone in a more serious fashion and I still have some ideas from back then I want to work on, but currently I'm working on something else so I probably won't do it soon.
