### ISSUE TITLE
Add Cocoa Beans to #farm

### ISSUE THREAD

**Issue by voxico** [cabaletta/baritone#1793] opened 2020-06-16 00:00 UTC
## Describe your suggestion
Add Cocoa Beans farming to #farm

## Context
I believe this would be good for Skyblock where the prices of Cocoa Beans can be quite high.

**Comment by dominikaaaa** [comment] 2020-06-16 00:03
Duplicate of #1570

**Closed by dominikaaaa** 2020-06-16 00:03 UTC
Labels: enhancement
