### ISSUE TITLE
crashing when using "#sel set" in a server

### ISSUE THREAD

**Issue by Gotort** [cabaletta/baritone#3130] opened 2021-12-10 16:29 UTC
## Some information
Operating system: Win 10
Java version: Java 17 x64
Minecraft version: 1.18
Baritone version: Downloaded it from meteor client, extracted baritone and installed with fabric
Other mods (if used): litematica, fabric api, malilib and wurst

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.log](https://github.com/cabaletta/baritone/files/7694024/latest.log)

## How to reproduce
I just join the server, do "#click" select the area, then "#sel set anything" and after it places the firt block, it crashes
In singleplayer it works fine

## Modified settings
![image](https://user-images.githubusercontent.com/95898575/145607256-632422e4-6ce0-4540-b022-062ef893527a.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-06-10 23:47
Duplicate of #3298

**Closed by ZacSharp** 2022-06-10 23:47 UTC
Labels: bug, duplicate
