### ISSUE TITLE
A safearea /No break zone

### ISSUE THREAD

**Issue by SmRzT** [cabaletta/baritone#3847] opened 2023-02-20 03:38 UTC
## Describe your suggestion
I keep getting baritone mining straight through my walls and its kinda annoying so maybe a command to select a no breakzone/safezone would be useful insted of blacklisting everyblock in my base

## Settings
#sel safezone
#sel safezoneExeption
#sel NoBreakArea
#sel NoBreakAreaExeption [blocks]
#safezone list (click on them to show boundries)

## Context
It would make baritone more survival friendly like in my example not ruining my base or protecting certain areas/structures 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-02-20 22:46
Duplicate of #2597

**Closed by ZacSharp** 2023-02-20 22:46 UTC
Labels: duplicate, enhancement
