### ISSUE TITLE
Carpet not placing when using #build

### ISSUE THREAD

**Issue by thetechlover0010** [cabaletta/baritone#1532] opened 2020-04-09 13:56 UTC
## Some information
Operating system: macOS Sierra 10.12.6
Java version: Java 1.8.0_74 64 bit
Minecraft version: 1.15.2
Baritone version: 1.5.1
Forge mods (if used): None (using impact nightly-20200403)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.txt](https://github.com/cabaletta/baritone/files/4456544/latest.txt)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
Exported schematic from MCEdit v1.5.6.0
Placed schematic file in /minecraft/schematics/
Opened up creative, added black carpet to hotbar
Typed `#build carpet.schematic`
Output: `[Baritone] Successfully loaded schematic for building`
`Origin: BetterBlockPos{x=44,y=4,z=340}`
`Done building`
However, the carpet was not placed at all. The Schematic is attached.
[carpet.schematic.zip](https://github.com/cabaletta/baritone/files/4456501/carpet.schematic.zip)

## Modified settings
To get the modified settings run `#modified` in game
All modified settings
> allowInventory true
> buildIgnoreExisitng true
> chatControl true
> mapArtMode true

Disabling any of these did not fix the issue.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment] 2020-04-09 14:27
Duplicate of #1531

**Closed by dominikaaaa** 2020-04-09 14:27 UTC
Labels: bug
