### ISSUE TITLE
setting protectedArea

### ISSUE THREAD

**Issue by m00nyONE** [cabaletta/baritone#3484] opened 2022-06-01 20:55 UTC
## Describe your suggestion
protectedArea command to protect a specific area predefined. This disallowes baritone to dig hole, place or break blocks in a specified area / base

## Settings
protectedArea add $NAME $X $Z
protectedArea del $NAME
protectedArea edit $NAME $X $Z
protectedArea rename $OLD_NAME $NEW_NAME

settings are pretty much self explenatory 

## Context
this would help baritone users not accidentaly break or add blocks to their base and go somewhere else mining.
happend to me in my base breaking a very important block that flood water in the base and wiped all redstone .-(

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-06-03 17:21
Duplicate of #2597

**Comment by ZacSharp** [comment] 2022-06-03 17:22
> breaking a very important block that flood water in the base and wiped all redstone

How did that happen? Baritone is supposed to not break blocks next to liquids to get somewhere.

**Closed by ZacSharp** 2022-06-03 17:21 UTC
Labels: duplicate, enhancement

**Comment by m00nyONE** [comment] 2022-06-08 23:45
it did :-(

also sometimes it breaks through fences in a farm or rips down walls because it can not interact with doors
