### ISSUE TITLE
Disable Autotool?

### ISSUE THREAD

**Issue by 265866** [cabaletta/baritone#1334] opened 2020-02-26 19:35 UTC
I would like an option to disable autotool while mining.

Something like #allowAutotool that is enabled by default but can be disabled

On the server  that I play on, mcprison.com, there is a beacon mine, but whenever I do "#mine" beacon or "#click" then "#sel ca", it automatically equips my backpack instead of my pickaxe, which I don't want

**Comment by S-B99** [comment] 2020-02-26 20:03
Uh, what item is your 'backpack'?

**Comment by S-B99** [comment] 2020-02-26 20:14
I'll probably do this later today if I have time, if not tomorrow.

**Comment by RealIndrit** [comment] 2020-02-26 20:35
Add this as the "public int getBestSlot()" in ToolSet return statement, "return BaritoneAPI.getSettings().autoTool.value ? best : player.inventory.selectedSlot;" and add the needed setting (Taken from fabritone, tried to add it here but it got rejected)

**Comment by 265866** [comment] 2020-02-26 21:14
the said "backpack" is a chest

**Comment by S-B99** [comment] 2020-02-26 21:29
Why the fuck is it selecting a chest to mine. Can you send a screenshot of it with enabled advanced tooltips

**Comment by 265866** [comment] 2020-02-26 22:51
Sure, here you go.
![unnamed](https://user-images.githubusercontent.com/54053306/75395521-77bed800-58a7-11ea-873c-976cc46e4a97.jpg)

**Comment by S-B99** [comment] 2020-02-26 22:55
That's so stupid holy shit lol. Yea I'll add an option

**Comment by 265866** [comment] 2020-02-26 22:58
Okay, thanks.

**Comment by 265866** [comment] 2020-02-26 23:52
Hey, I was just wondering when its done, how would I be able to use it?

**Comment by S-B99** [comment] 2020-02-26 23:52
`#autoTool false` or `.b autoTool false`

**Comment by 265866** [comment] 2020-02-26 23:52
oh, okay

**Comment by 265866** [comment] 2020-02-29 01:29
Just another question, is this going to be like an update for baritone or something? Like, whats the process of getting this update implemented?

**Comment by S-B99** [comment] 2020-02-29 01:30
Make pull request > get it merged > is added

**Comment by ZeroMemes** [comment] 2020-02-29 02:12
> tried to add it here but it got rejected

Next time try making a PR on the correct branch addressing one issue.

**Comment by sys4tf** [comment] 2020-03-21 17:56
reviving old post, is there a pull request yet?

**Comment by S-B99** [comment] 2020-03-21 18:57
https://github.com/cabaletta/baritone/pulls

**Comment by sys4tf** [comment] 2020-03-21 19:12
> https://github.com/cabaletta/baritone/pulls

cant seem to find a request for this issue? or i am just stupid. maybe a direct link? srry

**Comment by S-B99** [comment] 2020-03-21 19:45
The answer is no. 
![2020-03-21-154545_269x127_scrot](https://user-images.githubusercontent.com/17222512/77235316-08c55e00-6b8b-11ea-9661-404748370fc5.png)

**Comment by 0-x-2-2** [comment] 2020-03-22 09:23
#allowInventory

**Comment by 265866** [comment] 2020-03-23 03:08
wait like so im confused, what do i do to make a pull request because it seems like something that people want me to do.

**Comment by S-B99** [comment] 2020-03-23 03:31
You don't need to make one? But if you want to then you can fork the repo, write your code, push it to your repo, and then hit create pull request.

**Comment by S-B99** [comment] 2020-03-23 03:31
I self assigned this issue, as in I will do it. But that's probably going to be whenever I get around to it, maybe sometime next week.

**Comment by 265866** [comment] 2020-03-23 03:35
oh, okay, I'm kinda new to this, thank you!

**Comment by ImPqnda** [comment] 2020-03-24 13:57
Is this already added or no?

**Comment by S-B99** [comment] 2020-03-24 14:36
Try reading like 2 messages above.

**Comment by S-B99** [comment] 2020-03-24 14:37
Or look at the issue status.

**Comment by Narsisten9** [comment] 2020-05-05 17:38
is there any progress ?

**Comment by dominikaaaa** [comment] 2020-05-05 17:40
![Uploading 2020-05-05-134025_94x51_scrot.png…]()

**Comment by dominikaaaa** [comment] 2020-05-05 17:40
![2020-05-05-134025_94x51_scrot](https://user-images.githubusercontent.com/17222512/81097495-ff434b80-8ed5-11ea-91b9-f3209a503fb0.png)

**Comment by BottNet** [comment] 2020-05-15 12:16
![image](https://user-images.githubusercontent.com/46427383/82049502-543d4980-96ae-11ea-9e85-d11b3699e3ad.png)
Doesn't work for me

**Comment by TheK0tYaRa** [comment] 2020-05-15 13:12
Try `.b set autoTool false`

**Comment by BottNet** [comment] 2020-05-15 14:42
![image](https://user-images.githubusercontent.com/46427383/82062924-ba33cc00-96c2-11ea-8019-e7da83012af1.png)

**Comment by dominikaaaa** [comment] 2020-05-15 16:16
For fucks sake it's not added yet, as this issue is still

# opened

**Comment by dominikaaaa** [comment] 2020-05-15 16:17
I hate to be rude but everyone commenting on this issue needs to realise that this is **not** added because the issue is still **opened**

**Comment by cookiedragon234** [comment] 2020-05-16 13:20
lol

**Comment by kaleb762** [comment] 2020-07-15 20:47
just wondering if somebody is working on it and how long in till its done thx

**Comment by dominikaaaa** [comment] 2020-07-15 22:40
No and no

**Comment by kaleb762** [comment] 2020-07-15 22:46
ok thx any way

**Comment by Wahubah** [comment] 2020-07-28 04:26
so you say you work on it friend in February and march and you imply many time it will take short time frame so you make it please since you self assign?

**Comment by dominikaaaa** [comment] 2020-07-28 05:07
I'll do it when I get around to it. You're free to do it yourself if you want it done faster.

**Comment by sys4tf** [comment] 2020-07-28 05:15
justtesting#5009 add me on discord if u want a solution to this, only specific to this server. not code.

**Comment by 265866** [comment] 2020-07-29 00:54
Oh, jeez, I did not know that this was still a thing haha, It's been like two months since I've checked GitHub. @dominikaaaa take your time lol, its just Minecraft.

**Comment by 265866** [comment] 2020-07-29 00:57
Also, HOLY CRAP 40 COMMENTS!?!?! I never expected this to get as much attention as it did, I thought it was only me who wanted this feature...

**Comment by dominikaaaa** [comment] 2020-07-29 01:17
I'll probably do this soon because it's not that hard and it's pretty requested

**Comment by 265866** [comment] 2020-07-29 01:33
Oh, okay, thank you so much! Again, take your time, you probably have way more important things to do haha

**Comment by 265866** [comment] 2020-07-30 07:34
Oh, that's why it got so much attention, you referenced this issue/enhancement like 4 times haha. Makes so much more sense now... but still, it seems crazy (to me, at least) that so many people needed this feature or whatever

(Hello fellow players of mcprisons)

**Comment by 265866** [comment] 2020-08-19 05:13
Thank you so much!! Can I close this now?

**Comment by dominikaaaa** [comment] 2020-08-19 05:58
Yea, it should've been automatically closed when it was merged

**Closed by dominikaaaa** 2020-08-19 05:58 UTC
Labels: enhancement

**Comment by wolfgamer2805** [comment] 2022-01-05 04:32
![image](https://user-images.githubusercontent.com/30170841/148161035-e309ab0c-31d4-4f2c-a430-2b8486d077aa.png)
not work help pls
