### ISSUE TITLE
By clicking in chat (on anything), it won't work, but bring up a text instead in chat

### ISSUE THREAD

**Issue by RonnieNine** [cabaletta/baritone#1951] opened 2020-08-16 08:35 UTC
Basically, by clicking on next page for example, it'll bring up the command itself, but it replaces the ' # ' prefix with <<c544d0...(longer line)..f66b>>, thus the command itself wont register, and will show up in chat as a text instead. Any idea what could be wrong? thank you.

**Comment by ZacSharp** [comment] 2020-08-16 09:52
the randomized prefix is intended behavior, but it should run as a command
the randomized prefix is there to keep clickable text working even if you change the "#" prefix

**Comment by RonnieNine** [comment] 2020-08-16 09:56
> the randomized prefix is intended behavior, but it should run as a command
> the randomized prefix is there to keep clickable text working even if you change the "#" prefix

Yeah, I figured, but it's not working as a command and it's appearing as text only.

**Comment by RealIndrit** [comment] 2020-08-16 09:58
What version?

**Comment by RonnieNine** [comment] 2020-08-16 10:12
> What version?
Sorry, cant believe I left it out.
1.16.2 MC, 1.6.2 and 1.6.1 baritone (happens to both). Running with forge.

**Comment by ZacSharp** [comment] 2020-08-16 11:16
Then it's a Fabritone issue unless you can reproduce it with Baritone
If you can't please close this issue

**Comment by CDAGaming** [comment] 2020-08-16 13:21
Ok, 1.6.1 Baritone is deprecated for both Baritone and Fabritone due to 1.16.2, so you shouldnt even be using 1.6.1

Second, Id like to ask how you have gotten access to this build, since there are only two spots this was available at.

Either way, dont close this *just* yet.

**Comment by CDAGaming** [comment] 2020-08-16 14:30
![Screenshot from 2020-08-16 09-28-53](https://user-images.githubusercontent.com/16328918/90336677-054fca80-dfa3-11ea-895a-ab5754fcb107.png)

This issue can be closed, confirmed to no longer be present in either Baritone 1.16.2 and the upcoming v2 port of Fabritone for 1.16.2

**Closed** 2020-08-16 15:21 UTC
Labels: bug
