### ISSUE TITLE
Add 1.17.X support

### ISSUE THREAD

**Issue by ValentinKhmer** [cabaletta/baritone#2905] opened 2021-07-30 10:47 UTC
## What do you need help with?
When Baritone will be able to support 1.17.X versions? 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I already search if this question is not duplicate. 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment] 2021-07-30 10:49
duplicate of #2425

**Closed by wagyourtail** 2021-07-30 10:49 UTC
Labels: question
