### ISSUE TITLE
Auto Eat

### ISSUE THREAD

**Issue by CG573** [cabaletta/baritone#1472] opened 2020-03-29 13:54 UTC
## Describe your suggestion
Add a setting to eat food either in the offhand or in the hotbar when the player gets hungry.

## Settings
#autoEat (to toggle the setting true/false)

## Context
Increased survivability for automated players.

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] Y E S

**Comment by marsuh228** [comment] 2020-03-29 14:15
It is already in impact.

**Comment by S-B99** [comment] 2020-03-29 16:18
Duplicate of #496

**Closed by S-B99** 2020-03-29 16:18 UTC
Labels: enhancement
