### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by ColdHulkmask** [cabaletta/baritone#1713] opened 2020-05-19 15:11 UTC
## Some information
Operating system:Windows
Java version:32 bit
Minecraft version:1.12.2
Baritone version:impact
[latest.log](https://github.com/cabaletta/baritone/files/4651278/latest.log)
[latest.log](https://github.com/cabaletta/baritone/files/4651335/latest.log)

Forge mods (if used): none

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
i dont know how but i tried to use a schematic file and used #build but it said to report it here
## Modified settings
To get the modified settings run `#modified` in game
chatControl(boolean)
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue. UwU

**Comment by ColdHulkmask** [comment] 2020-05-19 15:12
sorry if this is just me being stupid

**Comment by dominikaaaa** [comment] 2020-05-19 15:37
Please add a brief but descriptive title

**Comment by dominikaaaa** [comment] 2020-05-19 15:38
duplicate of #1712

**Closed by dominikaaaa** 2020-05-19 15:38 UTC
Labels: bug
