### ISSUE TITLE
Maybe a "stayaway" command

### ISSUE THREAD

**Issue by slikkc** [cabaletta/baritone#3280] opened 2022-02-24 23:43 UTC
I was thinking a command that when a player comes within 10 blocks (or any amount) of the player that the bot stays exactly 10 blocks away

Being able to set the range of which you could stay away from the player so like .b stayaway 10 as an example

Thought this would be a useful addition to anarchy servers or just PvP in general. Being able to lure someone or just "tease" them would be cool.

**Comment by ZacSharp** [comment] 2022-03-04 21:40
Duplicate of #1611

**Closed by ZacSharp** 2022-03-04 21:40 UTC
Labels: duplicate, enhancement
