### ISSUE TITLE
routine system

### ISSUE THREAD

**Issue by VolantTheFox** [cabaletta/baritone#986] opened 2019-09-26 08:38 UTC
## Describe your suggestion

i suggest a system of routines using concepts from issue #176, where you could issue multiple commands in a queue system, with my addition of being able to save the queue as a routine.

syntax could be something like "#r create"

//output//: send the commands you would like to have in your routine. click "save" to save and choose a name!

*you type your commands*

>#explore (let's say for this example explore has a time limit or a block limit) 3000(blocks)
>#save mine
>#mine diamond_ore 400(blocks)
>#mine coal_ore 30
>#goto home

then you would click on an in chat button which would give you a prompt for a name
or you could issue a command like #r save [name]

## Settings

we should be able to set either a block limit or a time limit for #explore and #mine 

## Context
it would improve being able to let baritone afk or be used as a group of bots you could send off to do your slave work while you sit back and build a house or something. i've seen a couple people who thought a queue and routines seemed pretty intuitive and were surprised it didn't exist already.

## Final checklist
- [check_mark] I have not used any OwO's or UwU's in this issue.

**Comment by Xephorix** [comment] 2019-10-01 16:13
I do know that you can set a block limit for #mine. unless you mean all blocks in total. (i.e. stone, andesite, etc.) however I do think that a time limit would be a cool addition.

**Comment by exwundee** [comment] 2020-01-04 19:01
bumping this, would be a very useful feature

**Comment by S-B99** [comment] 2020-02-26 03:46
This is just a duplicate of that issue.

**Closed by S-B99** 2020-02-26 03:46 UTC
Labels: enhancement
