### ISSUE TITLE
AutoMine modded blocks.

### ISSUE THREAD

**Issue by gutoguto08** [cabaletta/baritone#1771] opened 2020-06-08 02:14 UTC
## Is there a way to mine modded blocks?
I have tried to do 
#mine mod_name:block_ore 
but it doesn't work.

## Final checklist
- [x] I know how to properly use mine.
- [x] I have not and will not use any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment] 2020-06-08 02:28
Duplicate of something. Searching on mobile is hard

**Closed** 2020-06-08 02:28 UTC
Labels: question

**Comment by gutoguto08** [comment] 2020-06-08 02:29
That's not very helpful, just so you know i did try to search for it.

**Comment by dominikaaaa** [comment] 2020-06-08 02:34
#1253 #1720 #1294
