### ISSUE TITLE
I cant follow players

### ISSUE THREAD

**Issue by Shadowgaming2021** [cabaletta/baritone#3098] opened 2021-11-20 20:40 UTC
## Some information
Operating system:Pc/Windows
Java version:
Minecraft version:1.17.1
Baritone version:
Other mods (if used): Meteor(Mod menu)

## Exception, error or logs
When im trying to follow a player its saying that i have a error in my Files and i should Come here

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
enter in the Chat "#follow player ..."

## Modified settings
Mod Menu /Meteor (but Baritone was Included

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-11-20 20:44
Is the player in render distance?

**Comment by ZacSharp** [comment] 2021-11-20 22:37
Also you omitted the logs which I could use to answer that question myself so imma mark this as invalid and close it as a duplicate of all the issues caused by #1926.

**Closed by ZacSharp** 2021-11-20 22:37 UTC
Labels: bug, invalid
