### ISSUE TITLE
Wildcards for block names

### ISSUE THREAD

**Issue by SupaGamer2017** [cabaletta/baritone#3181] opened 2022-01-05 19:30 UTC
## Describe your suggestion

This would allow for wildcards to be used to specify a broad category for selectable blocks.

## Settings

"Exact match for wildcards": Determines if the text before or after the wildcard must exactly match the remaining text in the block name or not. Normally enabled due to possible overgeneralization.

"Toggle Wildcards": Determines if wildcards can be used. Normally off due to most new users being inexperienced with wildcards.

"Wildcard Character": Determines what character is used for the wildcard arguments. Normally set to "*".
## Example of Settings

"Exact match for wildcards" ON: Searching for the wildcard "*bed" would flag all beds.

"Exact match for wildcards" OFF: Searching for the wildcard "*bed" would flag all beds AND bedrock.

"Toggle Wildcards" ON: Searching for "*bed" will be interpreted as a broad wildcard and will successfully target all blocks matching the criteria.

"Toggle Wildcards" OFF: Searching for "*bed" will be interpreted as a specific block ID and will inevitably fail due to not being recognized as a valid block ID.

## Context

This would be used as a slightly more elegant option for targeting multiple blocks during one operation than manually listing out the blocks to target. It also allows for up to 3 general wildcards to be targeted at once, as opposed to 3 specific blocks at once.

## Final checklist

- [■] I know how to properly use check boxes.

- [■] I have used no "OwO"s or "UwU"s in this issue.

**Comment by scorbett123** [comment] 2022-01-05 21:32
Duplicate of #3047

**Closed by scorbett123** 2022-01-05 21:32 UTC
Labels: enhancement
