### ISSUE TITLE
Update the #help command

### ISSUE THREAD

**Issue by Wudg3r** [cabaletta/baritone#1356] opened 2020-03-01 17:58 UTC
The #help command is not entirely correct when it mentions the syntax, like when it says that #follow is #follow (playername) and not #follow player (playername). It is one of the most used sources for syntax help when ingame and it would be very nice if you could fix it!

**Comment by S-B99** [comment] 2020-03-01 18:00
Duplicate of #1211

**Closed by S-B99** 2020-03-01 18:00 UTC
Labels: enhancement
