### ISSUE TITLE
When told to mine ore such as diamond It paths it but stands still and doesnt mine

### ISSUE THREAD

**Issue by DootDootboi** [cabaletta/baritone#4031] opened 2023-06-28 04:56 UTC
## Some information
Operating system: Windows 10
Java version: 20
Minecraft version: 1.19.2
Baritone version: 1.9.4
Other mods (if used): Fantasy Minecraft Fabric

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/11889832/latest.log)

How to reproduce:
Use commands like #mine diamond_ore or #mine ancient_debris

Modified settings:
AllowInventory True 
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment] 2023-06-28 09:02
you have far sight installed which is incompatible with baritone.

**Comment by ZacSharp** [comment] 2023-07-12 01:41
Duplicate of #3773

**Closed by ZacSharp** 2023-07-12 01:41 UTC
Labels: bug, duplicate
