### ISSUE TITLE
Hello! I tried mining with Baritone, but it said that An unhandled exception occured and that i had to report my games log to this github.com page. So here is my Minecraft log

### ISSUE THREAD

**Issue by Blearable** [cabaletta/baritone#3370] opened 2022-04-02 09:27 UTC
## Some information
Operating system:
Java version:
Minecraft v
[latest.log](https://github.com/cabaletta/baritone/files/8402236/latest.log)
ersion:
Baritone version:
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment] 2022-04-02 09:59
update baritone, duplicate of the pinned issue

**Closed** 2022-04-02 10:00 UTC
Labels: bug, duplicate
