### ISSUE TITLE
Baritone should auto-eat. 

### ISSUE THREAD

**Issue by fast-and-curious-1910** [cabaletta/baritone#2936] opened 2021-08-14 05:32 UTC
I would like to see a feature for baritone to eat the food in the hotbar when it reaches a certain number of hunger bars. I set baritone to mine logs and went afk to see baritone dead. 

Certain amount of hunger bars needed to be able to eat, or even to eat. 

It would be helpful while auto-mining, auto-building, and even tunneling and travelling on nether highways.

**Comment by scorbett123** [comment] 2021-08-14 20:07
Duplicate of #496

**Closed by scorbett123** 2021-08-14 20:07 UTC
Labels: enhancement
