### ISSUE TITLE
Copy and Paste for #sel

### ISSUE THREAD

**Issue by Bernardo122** [cabaletta/baritone#1210] opened 2019-12-29 16:58 UTC
Would be nice if the #sel command has a copy and paste arguments, this will temporarily resolve the problem with the .schematic. This just working in the current player session would be great, without any file export.

For example I build a floor of a cane farm that is repetitive but I just build one and copy and paste it on top of each other
![71552585-a111d380-29de-11ea-8853-bef2c13be297](https://user-images.githubusercontent.com/35816200/71560021-4eb6ce00-2a43-11ea-8844-6e6402c1c690.png)
, so i run .b build sel and start auto building .

**Comment by S-B99** [comment] 2020-02-25 14:24
Duplicate of #1116

**Closed** 2020-02-25 14:24 UTC
Labels: duplicate, enhancement
