### ISSUE TITLE
Fly Support

### ISSUE THREAD

**Issue by 1rens1** [cabaletta/baritone#3030] opened 2021-10-12 06:10 UTC
Creative Fly support can be really helpful on creative (sp), bigger builds or something

- [V] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2021-10-12 10:04
I don't think any build battle servers allow baritone, so don't use baritone on servers that it isn't allowed.

Also baritone doesn't deal with creative very well.

Duplicate of #2112

**Closed as completed by scorbett123** 2021-10-12 10:04 UTC
Labels: enhancement
