### ISSUE TITLE
Farm command should wait for crops to grow

### ISSUE THREAD

**Issue by Grummiom** [cabaletta/baritone#3970] opened 2023-06-05 14:44 UTC
## Describe your suggestion
Can you add an option so baritone doesn't cancel farm command operation when you don't have any bone meals and there is no fully grew crop? This way bot stops until it finds a new fully grew crop to harvest and plant it seed or whatever

## Context
So i can leave my game, come back and see a full inventory of farmed crops

**Comment by ZacSharp** [comment] 2023-06-07 22:53
Yes, that's possible and someone already suggested it in #893.
It's just that nobody implemented it so far.

**Comment by ZacSharp** [comment] 2023-06-07 22:53
Duplicate of #893

**Closed by ZacSharp** 2023-06-07 22:53 UTC
Labels: duplicate, enhancement
