### ISSUE TITLE
#mine Bot is ignoring Blocks next to Liquids

### ISSUE THREAD

**Issue by Matoex** [cabaletta/baritone#1410] opened 2020-03-16 01:14 UTC
## Introduction
I wanted the bot to mine cobblestones created by a cobblestone generator in skyblock, but the bot is ignoring the blocks created by the collision of water and lava.
![2020-03-16_01 46 34](https://user-images.githubusercontent.com/32068409/76715138-35ace780-672b-11ea-9b97-66f20aa21016.png)

## Reproduce
Build a Cobblestone generator and try `#mine cobblestone`.

## My Interpretation
![2020-03-16_02 02 13](https://user-images.githubusercontent.com/32068409/76715159-4eb59880-672b-11ea-96e8-97d9fd2febc1.png)
After some testing I think I know whats happening.
The bot is ignoring all blocks which are next to a liquid.

Therefore this is not really a "bug" but more like a "safety feature".
But still: Is there a way to turn this o to use the bot for farming cobblestones in Skyblock?

**Comment by S-B99** [comment] 2020-03-16 16:58
I can't find a setting for it, so your should probably make a feature request instead.

**Comment by ZacSharp** [comment] 2021-11-14 21:44
This is intended behaviour, so I will close this bugreport.

**Closed by ZacSharp** 2021-11-14 21:44 UTC
Labels: bug
