### ISSUE TITLE
Mine any type of ore/log/etc from mods (modpack)

### ISSUE THREAD

**Issue by Butter-On** [cabaletta/baritone#3654] opened 2022-09-10 20:31 UTC
## Describe your suggestion
Adding prefix any to mine command so it would look like this #mine (minecraft;mod_name;**any**):desired_block _(mod_exclusion)_
OR
Being able to list one block under multiple mods/sources

## Settings
Exclude mods setting to remove some bad apples that may not fit your purpose (see italic at the end of the description)

## Context
This improvement focuses primarily on modpack users that need specific material but can use a range of varieties from different mods.
(Let's say you need titanium ore so you go in and do #mine any:titanium_ore or exclude via #mine any:titanium_ore _mechanism_ or adding mods one by one #mine tinkersconstruct;mekanism:titanium_ore)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-09-11 22:39
Duplicate of #3047

**Closed by ZacSharp** 2022-09-11 22:39 UTC
Labels: duplicate, enhancement
