### ISSUE TITLE
Multiple settings profiles

### ISSUE THREAD

**Issue by Butter-On** [cabaletta/baritone#2799] opened 2021-06-12 10:00 UTC
## Describe your suggestion
As the title suggests, multiple setting profiles. These can be switched from one to another depending on the situation or server. Adding new profiles would be accessed from the game, editing them could be done in-game or in the files. Not much to say here.

## Settings
- **#settingProfiles**
Will list your created profiles and their names.

- **#settingProfile [profile]** 
Will exchange your currently used profile for another on the list.

- **#settingProfileDefault [profile]** 
Will set your selected profile for default when starting up baritone. 

## Context
Its always pain when you need to switch settings to fit your liking/game, so this feature will improve this. Example is that for diamond mining you use one setting profile optimalized for that and when you need to get something like wood you use another profile for that. And many more examples can be found like servers minigames, parkours, etc....

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2021-06-12 18:09
When creating a new profile would the settings be based on the existing settings or default?

**Comment by ZacSharp** [comment] 2021-06-12 20:25
I'd say either split it split it into create and copy commands or make it based on the current settings (so you can `#reset all` them).

Also #2196 does suggest sparse setting profiles, duplicate or not?

**Comment by Butter-On** [comment] 2021-06-12 20:42
I'll say it is a duplicate, we basically suggest the same thing yet it's differently worded and structured. Also forgot commands for creating and deleting profiles.

**Comment by ZacSharp** [comment] 2021-06-12 22:47
Duplicate of #2196

**Comment by ZacSharp** [comment] 2021-06-12 22:47
The difference is whether the profiles are sparse (override only some settings) or not, but imo both should be supported anyway

**Closed by ZacSharp** 2021-06-12 22:47 UTC
Labels: enhancement
