### ISSUE TITLE
Place block with NBT

### ISSUE THREAD

**Issue by neila-a** [cabaletta/baritone#3701] opened 2022-10-26 05:06 UTC
## Describe your suggestion
Place block with NBT.

## Context
When placing a block with `#sel replace`, leave the block with NBT, for example, `axis: y`

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-10-27 00:27
Duplicate of #1760

**Closed by ZacSharp** 2022-10-27 00:27 UTC
Labels: duplicate, enhancement
