### ISSUE TITLE
When mining logs such as tall Spruce Logs or normal logs, the bot should be able to staircase up (in the case of tall spruce logs) or use temporary blocks to get to the logs nested up high in the tree

### ISSUE THREAD

**Issue by runecapes** [cabaletta/baritone#3567] opened 2022-07-16 02:37 UTC
The ability to use temporary blocks and then break them afterwards so as to not waste resources, e.g placing a block of cobblestone to get to a log nested up in the trees.

There is a setting to use temporary blocks, however the bot will make no effort to destroy them.

**Comment by ZacSharp** [comment] 2022-07-16 13:05
Duplicate of #2976

**Closed by ZacSharp** 2022-07-16 13:05 UTC
Labels: duplicate, enhancement
