### ISSUE TITLE
Allow it to place items in chest (read details)

### ISSUE THREAD

**Issue by oTylerr** [cabaletta/baritone#600] opened 2019-07-21 04:19 UTC
I need something that when my inventory is FULL It will deposit unneeded items into a nearby chest, the blocks the bot will mine and all the chests are all very close. This combined with autominer would allow somebody to grind for way longer than usual. FOr example with this i could sleep and still grind or go to school which during a school day that can give me an extra 15 hours of grinding !

**Comment by ZeroMemes** [comment] 2019-07-21 21:11
Although #605 is a duplicate of this issue fundamentally, it is slightly more detailed in functionality so let’s move to there.

**Closed by ZeroMemes** 2019-07-21 21:11 UTC
Labels: enhancement
