### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by mayday5109** [cabaletta/baritone#4184] opened 2023-11-06 06:32 UTC
## Some information
Operating system: Windows
Java version: Unknown
Minecraft version: 1.20.2
Baritone version: newest idk
Other mods (if used): Aristois if this helps

It says "An unhandled exception occurred, the error is in your games log" after trying to use the mining command

[latest.log](https://github.com/cabaletta/baritone/files/13263209/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here. N/A?

## Modified settings
To get the modified settings run `#modified` in game N?A

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-11-06 17:36
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-11-06 17:36 UTC
Labels: bug, duplicate
