### ISSUE TITLE
An unhandled exception occured. The error is in your game's log, please report this.

### ISSUE THREAD

**Issue by Auxqe** [cabaletta/baritone#3104] opened 2021-11-25 06:21 UTC
I try to use the "#follow player NAME" command and it says, "An unhandled exception occured. The error is in your game's log, please report this.

What exactly is the problem and how do I fix it? Thanks

**Comment by pikachu1298** [comment] 2021-11-25 19:34
the player might be out of render distance

**Comment by ZacSharp** [comment] 2021-11-25 20:34
Please add a log so we can see whether pikachu1298 is right.

**Comment by ZacSharp** [comment] 2022-01-12 00:15
Closing because the issue is likely fixed and no further information was provided.

**Closed by ZacSharp** 2022-01-12 00:15 UTC
Labels: question
