### ISSUE TITLE
Filling area on server crashes, Baritone attempts to save

### ISSUE THREAD

**Issue by ExperiBass** [cabaletta/baritone#3244] opened 2022-02-03 05:05 UTC
When filling an area using `#sel fill` on a server, Baritone attempts to save, and then crashes the client.

## Some information
Operating system: Linux (EndeavourOS Rolling)
Java version: `openjdk 17.0.1 2021-10-19`
Minecraft version: 1.18.1 (Fabric)
Baritone version: 1.8.2 Standalone
Other mods (if used): 
- betterfpsdist
- C^2ME
- Cull Leaves
- DashLoader
- Dynamic FPS
- Entity Culling
- Inventory Sorter
- Lithium
- Logical Zoom
- Mod Menu
- Mouse Tweaks
- ReplayMod
- Starlight
- Xaeros Minimap/World Map

## Exception, error or logs

[2022-02-02-6.log](https://github.com/cabaletta/baritone/files/7991924/2022-02-02-6.log)

## How to reproduce
1. Join a server.
2. Attempt to fill an area. I was attempting to fill a 10x10x1 area with dirt blocks.
3. See Baritone attempt to save, then crash.

## Modified settings
![image](https://user-images.githubusercontent.com/33764485/152284278-1901a27a-d446-4bc5-b73c-a15db324f13a.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment] 2022-02-03 05:51
I'm actually struggling to reproduce this one...
I've done everything...
what's your buildIgnoreBlocks actually look like?

**Comment by ExperiBass** [comment] 2022-02-03 06:27
`buildIgnoreBlocks` is `torch,ladder`.

**Comment by Kincaid-dev** [comment] 2022-02-09 15:45
I believe I also have this problem. It comes and goes. But, mine I'm always doing `#s ca`. Sometimes this works and sometimes it crashes. Usually, if it crashes I can't use the command again or any fill/replace command for some time. After a while, it begins working again.

**Comment by wagyourtail** [comment] 2022-02-14 22:50
can someone get this crash to happen with the baritone-unoptimized (forge/fabric/whatever) jar?

**Comment by JaaiDead** [comment] 2022-02-22 17:51
@wagyourtail yes. I had this issue my self somethings my game just blunty crash or its due to haveing a low  RAM imo. Useing
#sel fill crashes .and other times it works fine .

**Comment by debian-user-france1** [comment] 2022-02-22 21:03
It seems to only happen if there isn't any block available anymore that's needed (if you fill with dirt and you don't have dort anymore it will crash). That's what at least I experience.

**Comment by ExperiBass** [comment] 2022-02-23 03:54
> It seems to only happen if there isn't any block available anymore that's needed (if you fill with dirt and you don't have dort anymore it will crash). That's what at least I experience. 

Maybe also if you don't have enough?

**Comment by debian-user-france1** [comment] 2022-02-23 11:20
No. I currently don't want to try the unoptimized version, but do I have to?

**Comment by ehylo** [comment] 2022-02-23 16:28
The unoptimized jar doesn't actually make baritone slower, it's name is confusing as it means the jar is slightly bigger in size, and wag wants you to crash with it because it's not obfuscated so fixing the bug or finding the root cause is infinitely easier.

**Comment by wagyourtail** [comment] 2022-03-15 21:12
#3308 merged closing this

**Closed by wagyourtail** 2022-03-15 21:12 UTC
Labels: bug
