### ISSUE TITLE
Baritone automatic take from chest/shulker/enderchest

### ISSUE THREAD

**Issue by NumseBacon** [cabaletta/baritone#1517] opened 2020-04-06 18:35 UTC
## What do you need help with?
I saw a group on 2b2t using a version of baritone to make it automatically take ender chests from shulker and break the ender chests to get obsidian to place obisidian? Is it possible a guy like me every could get that program , or anything similar

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment] 2020-04-06 18:36
Duplicate of #1515 

I marked your other issue as a duplicate because it hasn't been added to baritone.

**Closed by S-B99** 2020-04-06 18:36 UTC
Labels: question

**Comment by NumseBacon** [comment] 2020-04-06 18:38
> 
> 
> Duplicate of #1515
> 
> I marked your other issue as a duplicate because it hasn't been added to baritone.

Thats 2 different things I talked about in the first post and that doesnt make any sense that its a duplicate because it hasent been added and u say its duplicate of my other post

**Comment by S-B99** [comment] 2020-04-06 18:39
It's the same thing.

**Comment by S-B99** [comment] 2020-04-06 18:39
And it is a duplicate, it's the exact same thing.

**Comment by NumseBacon** [comment] 2020-04-06 18:40
How is something a group has the same as putting in chests

**Comment by S-B99** [comment] 2020-04-06 18:42
You'd have literally the exact same code to have baritone store shit in chests vs shulkers. It's the same concept and idea. Even your issue description is copy and pasted.

**Comment by NumseBacon** [comment] 2020-04-06 18:43
Yep ofc I copied some of the description. So he is working on it?

**Comment by S-B99** [comment] 2020-04-06 18:44
[????](https://lmgtfy.com/?q=how+does+github+issues+work+)

**Comment by NumseBacon** [comment] 2020-04-06 18:51
????

**Comment by S-B99** [comment] 2020-04-06 18:52
click the link ♿♿♿♿

**Comment by NumseBacon** [comment] 2020-04-06 18:56
U calling me handicapped?

**Comment by NumseBacon** [comment] 2020-04-06 18:58
damn so he isnt gonna add it

**Comment by S-B99** [comment] 2020-04-06 18:59
no?? the issue is still open. that doesn't mean it won't be added, it just means it hasn't

**Comment by NumseBacon** [comment] 2020-04-06 19:04
But I asked if it was possible that a guy like me could get the software that group is using

**Comment by S-B99** [comment] 2020-04-06 19:05
no?? this is baritone, and it's not implemented in baritone. we don't know what random ass youtube video you were watching.

**Comment by NumseBacon** [comment] 2020-04-06 19:06
FitMC

**Comment by S-B99** [comment] 2020-04-06 19:07
i couldn't care less. if it's not in baritone (as shown by the issue being still open) we can't help you with it

**Comment by Aaron2550** [comment] 2020-04-07 21:05
_that moment when someone asks which video you were watching and you reply with a whole channel_
