### ISSUE TITLE
Mining deepslate ores causes it to bug out

### ISSUE THREAD

**Issue by 9ny4** [cabaletta/baritone#4180] opened 2023-11-05 02:52 UTC
## Some information
Operating system: Win 11
Java version:17.0.7
Minecraft version: 1.20.2
Baritone version: Null(Meteor Dev env) Jar file is named baritone-1.20.2-20231022.115809-1.jar pretty sure i got it from the meteor website
Other mods (if used):  Sodium. Meteorist(Meteor addon), Clientcommands and borderless-mining

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/13258169/latest.log)
[debug.log](https://github.com/cabaletta/baritone/files/13258171/debug.log)

## How to reproduce
#mine minecraft:deepslate_diamond_ore (Any deepslate ore) have not tested normal deepslate block

For me it just sets a goal like 100 blocks away, goes to it and sets a new goal 100 blocks away.

## Modified settings
backfill, blockPlacementPenalty, BlockReachDistance, cachedCunksOpacity, colorBestPathSoFar, colorBlocksToBreak, colorBlocksToPlace, colorBlocksToWalkInTo, colorCurrentPath, colorGoalBox, ColorInvertedGoalBox, colorNextPath, colorSelection, colorSelectionPos1, colorSelectionPos2, elytraNetherSpeed, elytraTimeBetweenCacheCullSecs, faliureTimeoutMS. followOffsetDirection, goalRenderLineWidthPixels, maxFallHightNoWater, mineDropLoiterDurationMSThanksLouca, pathingMapLoadFactor,pathRednerLineWidthPixels, PlanAheadFaliureTimeoutMS, planAheadPrimaryTimeoutMS, primaryTimeoutMS, selectionLineWidth, selectionOpacity, slowPathTimeoutMS, smoothLook, toastTimer

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-11-05 14:09
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-11-05 14:09 UTC
Labels: bug, duplicate
