### ISSUE TITLE
when mining i got a unhandled exception

### ISSUE THREAD

**Issue by Lurmog** [cabaletta/baritone#4177] opened 2023-11-04 18:56 UTC
## Some information
Operating system: Windows 10 22H2
Java version: 18.0.2.1 64Bit
Minecraft version: 1.20.2
Baritone version: baritone-1.20.2-20231022.115809-1
Fabric Version: 0.14.24

Other mods (if used): Meteor Client

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/13257497/latest.log)

## Modified settings
maxFallHeightNoWater 159159

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-11-04 22:10
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-11-04 22:10 UTC
Labels: bug, duplicate
