### ISSUE TITLE
Elytra Flight

### ISSUE THREAD

**Issue by 9990765439** [cabaletta/baritone#3606] opened 2022-08-09 15:37 UTC
## Describe your suggestion
I would like to see Baritone be able to use the elytra to move faster with fireworks in hand or off hand.

## Settings
allowElytraFlight
assumeElytraHacks  (height control, speed control)

## Context
This will improve Baritone by adding another movment method instead of underground and surface.
Movment Method: AIR

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2022-08-26 19:03
Duplicate of #1852

**Closed by scorbett123** 2022-08-26 19:03 UTC
Labels: enhancement
