### ISSUE TITLE
Issue with #litematica

### ISSUE THREAD

**Issue by Tick-0** [cabaletta/baritone#4570] opened 2024-11-24 19:17 UTC
## Some information
Operating system: Windows 10
Java version: 23
Minecraft version: Fabric 1.21.3
Baritone version: Fabric 1.11.1
Other mods (if used): 
architectury-14.0.4-fabric
cloth-config-16.0.141-fabric
entity_model_features_fabric_1.21.3-2.3.0
entity_texture_features_fabric_1.21.3-6.2.7
fabric-api-0.107.0+1.21.3
iris-fabric-1.8.0-beta.8+mc1.21.3
journeymap-fabric-1.21.3-6.0.0-beta.29
litematica-fabric-1.21.3-0.20.0
minihud-fabric-1.21.3-0.33.0-sakura.6
ok_zoomer-fabric-11.0.0-beta.3
polytone-1.21.3-2.5.5-fabric
removewardeneffect-0.0.2-1.20.5-6
Roughly-Enough-Items-Mod-Fabric-1.21.3
seedmapper-2.0.0-beta.4
sodium-fabric-0.6.0-beta.4+mc1.21.3
worldedit-mod-7.3.9-beta-01-dist
xplus-autofish-1.3.4-fabric-mc1.21.3
malilib-fabric-1.21.3-0.22.0

## Exception, error or logs
https://pastebin.com/67uzFgge

## How to reproduce
have active Schematic in litematica
type #litematica

## Modified settings
buildInLayers

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [OwO] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2024-11-29 11:21
Duplicate of #4543

**Comment by ZacSharp** [comment] 2024-11-29 11:21
Fix is currently merged to 1.19.4 and on its way to 1.20 and 1.21

EDIT: The fix is merged into all supported branches

**Closed as completed by ZacSharp** 2024-11-29 11:21 UTC
Labels: bug, duplicate
