### ISSUE TITLE
Game crashes when using #goto and lags stupidly hard with #mine

### ISSUE THREAD

**Issue by bloxanne123** [cabaletta/baritone#4072] opened 2023-07-25 02:46 UTC
## Some information
Operating system: Windows 11
Java version: GraalVM Java 20
Minecraft version: 1.20
Baritone version: v1.10.1
Other mods (if used): Fabric API, LazyDFU, Lithium

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/12156566/latest.log)

Note: this doesn't include #mine but I ran it again and here it is (i turned down render distance to check if it was lagging due to that).
> [22:38:59] [Render thread/INFO]: [System] [CHAT] [B] > mine dirt
> [22:38:59] [Render thread/INFO]: Reloading ResourceManager: vanilla
> [22:38:59] [Render thread/INFO]: [System] [CHAT] [B] Mining [BlockOptionalMeta{block=Block{minecraft:dirt}}]
> [22:39:27] [Server thread/INFO]: Saving and pausing game...
> [22:39:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
> [22:39:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
> [22:39:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
> [22:39:55] [Server thread/INFO]: Changing view distance to 2, from 6

## How to reproduce
Join a server(!) or singleplayer. 
Run #goto x z (whatever coords, as long as they're a couple blocks away at the least)
Watch your game lag, and then crash.
Try #mine, it'll lag really hard. But it will work. Doesn't matter what block it is.

I am more annoyed about the crash than the mining...

## Modified settings
To get the modified settings run `#modified` in game
Just uploading a file since it's giving me all the settings, not just modified.
[modified.txt](https://github.com/cabaletta/baritone/files/12156597/modified.txt)

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

## Additional Info:
Java 17 from adoptium doesn't fix it.
I'm in a superflat world.
No GC args used.
I have sufficient memory.
The lag is really strange. Nothing fixes it. Not even sodium (which funnily enough caused a funky crash with RenderPath that I haven't been able to reliably reproduce, I don't have logs unfortunately)

**Comment by bloxanne123** [comment] 2023-07-25 03:01
Uh it crashes with the same error if you use #explore...

**Comment by bloxanne123** [comment] 2023-07-25 03:11
Okay...ignore those logs. I truly apologize but for some reason MINECRAFT TRUNCATED THOSE PARTS OF THE LOG.
I had to copy it from my console.
Okay.
Here are the two errors I get:
#explore: https://hastebin.com/share/gujixayiku.php
#goto: https://hastebin.com/share/orutupasod.php

**Comment by bloxanne123** [comment] 2023-07-25 03:12
also the logs are the same with java 17....and this is all with the same mod list as before (Baritone, FAPI, LazyDFU, Lithium)

**Comment by ZacSharp** [comment] 2023-07-26 16:44
Duplicate of #3453

**Closed by ZacSharp** 2023-07-26 16:44 UTC
Labels: bug, duplicate

**Comment by bloxanne123** [comment] 2023-07-26 18:57
So setting renderGoalXZBeacon to false should fix this?

**Comment by ZacSharp** [comment] 2023-07-26 23:47
Yes, that should make things work until the next release (or until 1.19.4 is merged into 1.20.1 if you use CI builds)

**Comment by Ethanjoyce2010** [comment] 2024-07-08 10:31
same prob but with #mine iron_ore

**Comment by ZacSharp** [comment] 2024-07-09 18:58
@Ethanjoyce2010 this issue was fixed a while ago so please mage sure that you are running an up to date and supported version of Baritone. If that is already the case, please open a new bug report.
