### ISSUE TITLE
Anyone knows the reason of crashing? Works in single player, crashes in a server.

### ISSUE THREAD

**Issue by Superpapotas** [cabaletta/baritone#2409] opened 2021-02-01 06:48 UTC
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/02/21 12:45 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_636.method_2911(class_636.java:281)
	at net.minecraft.class_636.method_2927(class_636.java:260)
	at net.minecraft.class_310.method_1574(class_310.java:1504)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:166)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at me.deftware.client.framework.main.Main.main(Main.java:43)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_636.method_2911(class_636.java:281)
	at net.minecraft.class_636.method_2927(class_636.java:260)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 729, 102
	Level dimension: minecraft:overworld
	Level spawn location: World: (181,80,174), Chunk: (at 5,5,14 in 11,10; contains blocks 176,0,160 to 191,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 105124218 game time, 104357252 day time
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:166)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at me.deftware.client.framework.main.Main.main(Main.java:43)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 264262560 bytes (252 MB) / 1021202432 bytes (973 MB) up to 6179520512 bytes (5893 MB)
	CPUs: 8
	JVM Flags: 5 total; -Xmn128M -Xmx5905M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC
	Launched Version: 1.16.5-Aristois
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 8 Graphics  GL version 4.6.14736 Compatibility Profile Context 20.9.1 27.20.12029.1000, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: Español (España)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx

**Comment by scorbett123** [comment] 2021-02-01 08:49
Duplicate of #2408

**Closed** 2021-02-01 10:13 UTC
Labels: bug
