### ISSUE TITLE
NullPointerException while joining a Replay Mod Replay

### ISSUE THREAD

**Issue by TheAwesome98-Real** [cabaletta/baritone#2769] opened 2021-05-23 10:29 UTC
## Some information
Operating system: `uname -a` output:
```
[user]@[hostname]:~$ uname -a
Linux [hostname] 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Java version: `java -version` output:
```
[user]@[hostname]:~$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```
Minecraft version: 1.16.5 with fabric 0.11.3
Baritone version: 1.6.3
Other mods (if used): Replay Mod 2.5.2

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[Crash Report](https://github.com/cabaletta/baritone/files/6527876/crash-2021-05-23_10.27.43-client.txt)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
1. Join a game and create a Replay
2. Log out and open the replay
3. Game crashes with NullPointerException

## Modified settings
To get the modified settings run `#modified` in game
chatControl = false

## Additional information
I think it might be caused by baritone not knowing where the world file is (to place the baritone directory in), because the replay is a "fake" local world, but it could be anything.
Searching for this issue resulted in "rename it from [name] to ![name]" this does not work, and none of the issues were resolved

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment] 2021-05-23 10:47
duplicate of #2619 (also see #2621 )

**Closed by wagyourtail** 2021-05-23 10:47 UTC

**Comment by TheAwesome98-Real** [comment] 2021-05-25 21:39
> duplicate of #2619 (also see #2621)

(#2621: that means I was correct about the issue)
If you read the body of my issue, you can see I searched for duplicates before posting, which didn’t help. However, thanks for linking the pull-request, now I know why this causes a crash, it’s only a matter of merging it.

**Comment by ejsupernova** [comment] 2022-01-05 09:52
Yes happened with me too
