### ISSUE TITLE
baritone cant mine

### ISSUE THREAD

**Issue by lengway** [cabaletta/baritone#3499] opened 2022-06-07 10:18 UTC
os: windows 10
Java: 17.0.1
minecraft: 1.18.2
issue: baritone giving me error every time im trying to enter !mine
log:
[16:10:32] [Render thread/INFO]: [CHAT] [Baritone] > mine minecraft:diamond_ore
[16:10:32] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[16:10:32] [Render thread/INFO]: [STDERR]: baritone.au: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[16:10:32] [Render thread/INFO]: [STDERR]: 	at baritone.hc.a(Unknown Source)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at baritone.hb.a(Unknown Source)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at baritone.ew.a(Unknown Source)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at baritone.ew.a(Unknown Source)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at baritone.hd.a(Unknown Source)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at baritone.hd.a(Unknown Source)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zdi000$sendChatMessage(class_746.java)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:378)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:371)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.method_25427(GuiChatOF.java:41)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:384)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:380)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:716)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:118)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:715)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:202)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:442)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1147)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[16:10:32] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[16:10:32] [Render thread/INFO]: [STDERR]: 	at baritone.z.a(Unknown Source)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at baritone.fe.b(Unknown Source)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at baritone.gg.a(Unknown Source)
[16:10:32] [Render thread/INFO]: [STDERR]: 	... 30 more
[16:10:32] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3296
[16:10:32] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
[16:10:32] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:10:32] [Render thread/INFO]: [STDERR]: 	... 33 more

**Comment by Stuntlover-TM** [comment] 2022-06-07 10:23
You need to do
`mine diamond_ore`
without the `minecraft:` infront, just the ID

**Comment by wagyourtail** [comment] 2022-06-07 10:24
update baritone to 1.8.3
duplicate of pinned issue

**Closed by wagyourtail** 2022-06-07 10:24 UTC
Labels: bug
