### ISSUE TITLE
sometimes can't place blocks 

### ISSUE THREAD

**Issue by BroSotos** [cabaletta/baritone#840] opened 2019-08-23 19:22 UTC
## Some information
Java version: 1.8_221
Minecraft version: 1.14.4 
Baritone version: 1.4.1

## How to reproduce
Any path where blocks need to be placed

https://www.youtube.com/watch?v=l8KejredBY4&feature=youtu.be

## Final checklist
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X ] I have not used any OwO's or UwU's in this issue.

**Comment by Allison-Z** [comment] 2019-11-12 11:42
having this problem aswell

**Comment by 0-x-2-2** [comment] 2019-11-12 16:45
If anyone else has this problem can you make a clip of every time this happens? My first thought is that 1.14.x+ changes the collision box of the LocalPlayer when sneaking. If you can reproduce this often having chat debug enabled can also help but it will fill up your chat.

**Comment by U5B** [comment] 2019-12-01 00:19
it seems like Baritone doesn't actually right click? since when I right click to place the block, it works fine and continues on its merry way

**Comment by ameer818** [comment] 2019-12-04 01:10
> it seems like Baritone doesn't actually right-click? since when I right-click to place the block, it works fine and continues on its merry way
> 
> EDIT: I fixed my issue by removing mods that edits the SNEAK function.

Do you mean client mods? How did you do it? Which ones?

**Comment by U5B** [comment] 2019-12-09 02:33
I had a mod named togglesneak in my mods folder. I removed that and
everything worked fine.

**Comment by dave752** [comment] 2021-01-13 00:44
I had this same problem, fixed it by setting my blockReachDistance to 3, as it didn't mine any blocks under me while at 1, and wouldn't pillar while at 2. (I do not have any sneak mods installed)

**Comment by l1ving** [comment] 2021-01-13 00:45
I'm closing this as user error. It's either client side mods interfering or server restrictions

**Closed by l1ving** 2021-01-13 00:45 UTC
Labels: bug
