### ISSUE TITLE
Program a path with multible waypoints.

### ISSUE THREAD

**Issue by DudeTux** [cabaletta/baritone#3079] opened 2021-11-12 12:44 UTC
I want to create a path with multible waypoints to be able to walk in a certain pattern.

## Context
I want this to be a feature to be able to use Litematica printer to make, making map arts easier.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-11-12 15:03
Duplicate of #176

**Closed by ZacSharp** 2021-11-12 15:03 UTC
Labels: duplicate, enhancement
