### ISSUE TITLE
Look for a certain command

### ISSUE THREAD

**Issue by AnimeniacSimey** [cabaletta/baritone#1368] opened 2020-03-07 18:28 UTC
Is there a command in baritone that allows you to just see the waypoint? For example if you use
`follow entity wither_skeleton` it shows you where to go rather than automatically going there on it's own. Thanks!

**Comment by S-B99** [comment] 2020-03-07 18:29
Duplicate of #928

**Closed by S-B99** 2020-03-07 18:29 UTC
Labels: question

**Comment by AnimeniacSimey** [comment] 2020-03-07 18:31
It doesn't answer my question though...

**Comment by S-B99** [comment] 2020-03-07 18:33
It's not added yet, as that issue is still opened
