### ISSUE TITLE
#Hunt Command Suggestion

### ISSUE THREAD

**Issue by IsaacDawg97** [cabaletta/baritone#4383] opened 2024-06-09 05:06 UTC
## Describe your suggestion
#Hunt Command similar to #Mine, but for entities.
I understand that I could use #follow entity coupled with KillAura, but it would also be nice if it MineScanned (or HuntScanned in this case) the drops and picked up all or a select few drops.

## Settings
The Settings could be similar to #Mine, but with an optional field afterwards to select which items to Scan for, such as...
#Hunt Wither_Skeleton Wither_Skeleton_Skull

## Context
Thought of it while farming WitherSkeletons in a fortress.

**Comment by ZacSharp** [comment] 2024-06-09 14:26
Duplicate of #1536

**Closed as completed by ZacSharp** 2024-06-09 14:26 UTC
Labels: duplicate, enhancement
