### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by BallisticJandle** [cabaletta/baritone#3977] opened 2023-06-11 04:29 UTC
Make a GUI with all the settings and commands
It would be opened with a random key like 'delete' (not backspace) 'insert' or that weird ` key
Would be a lot more convenient than a CLI
👍

**Comment by ZacSharp** [comment] 2023-06-11 22:41
Duplicate of #794

**Closed by ZacSharp** 2023-06-11 22:41 UTC
Labels: duplicate, enhancement
