### ISSUE TITLE
Allow Baritone to use water buckets to ascend walls

### ISSUE THREAD

**Issue by kittenswolf** [cabaletta/baritone#855] opened 2019-08-26 15:31 UTC
## Describe your suggestion
Allow Baritone to use water buckets to ascend walls, like this: https://www.reddit.com/r/Minecraft/comments/cvng2y/who_needs_ladders/

## Settings
A setting should be added that manages said behaviour.

## Context
This could be faster and cleaner than building a tower or mining.

## Final checklist
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by Ekibunnel** [comment] 2019-08-27 15:52
It would be very nice

**Comment by S-B99** [comment] 2020-02-27 15:16
Duplicate of #811

**Closed by S-B99** 2020-02-27 15:16 UTC
Labels: enhancement
