### ISSUE TITLE
[BUG] baritone crashed from mobile.

### ISSUE THREAD

**Issue by RubixYouTube** [cabaletta/baritone#4361] opened 2024-05-12 18:31 UTC
## Some information
Operating system: Android 11
Java version: 21
Minecraft version: 1.20.4
Baritone version: 1.10.2
Other mods (if used): It's Not

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latestlog.txt](https://github.com/cabaletta/baritone/files/15287285/latestlog.txt)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
`Add Baritone to Pojav (If Mobile)`
`Wait`
`Done!`

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2024-05-26 02:10
Duplicate of #4244

**Comment by ZacSharp** [comment] 2024-05-26 02:11
If you update Baritone (to a CI build, release is too old) the problem will be gone.
(Except you won't be able to use `#elytra`)

**Closed as completed by ZacSharp** 2024-05-26 02:10 UTC
Labels: bug, duplicate
