### ISSUE TITLE
Help needed with using the #mine feature

### ISSUE THREAD

**Issue by heyhowudoin** [cabaletta/baritone#4326] opened 2024-04-06 21:28 UTC
## Some information
Operating system:windows
Java version:1.20.2
Minecraft version:1.20.2
Baritone version:1.20.2
Other mods (if used): fabricplus

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[latest.log](https://github.com/cabaletta/baritone/files/14895030/latest.log)

Windows: `%appdata%/.minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

so it keeps saying that i cannot mine the block i want to mine and it says i have to report it here?
i read another user's post on here but i dont quite understand on how to fix the problem please help me

much love to the people that comment on how to fix it 😃

**Comment by ZacSharp** [comment] 2024-04-07 20:21
Does this happen when you are below y level 0?

**Comment by heyhowudoin** [comment] 2024-04-08 09:24
yeah it only happens when below y level 0

**Comment by ZacSharp** [comment] 2024-04-08 15:13
Then this is a known problem and already fixed in release v1.10.2, which is for Minecraft 1.20.4.
A release for 1.20.2 won't happen anymore (because 1.20.4 exists), but the fix is older and you can get a working version for 1.20.2 from [this comment](https://github.com/cabaletta/baritone/issues/4254#issuecomment-1922291720).

**Comment by ZacSharp** [comment] 2024-04-08 15:14
Duplicate of #4112

**Closed as completed by ZacSharp** 2024-04-08 15:14 UTC
Labels: bug, duplicate
