### ISSUE TITLE
#retrace

### ISSUE THREAD

**Issue by RaulThingy** [cabaletta/baritone#2743] opened 2021-05-13 21:20 UTC
Retraces your steps to go back to your base or if you got lost

**Comment by Filius-Patris** [comment] 2021-05-13 22:14
Ideally you should've set a home waypoint. Then you can navigate to it (`#wp goto home`).

**Comment by ZacSharp** [comment] 2021-05-13 22:32
Duplicate of #1621

**Comment by ZacSharp** [comment] 2021-05-13 22:33
And you missed to fill in the template

**Closed by ZacSharp** 2021-05-13 22:32 UTC
Labels: enhancement
