### ISSUE TITLE
How do I stop this screen twitching while clearing areas? 

### ISSUE THREAD

**Issue by Floppymnt** [cabaletta/baritone#4190] opened 2023-11-11 06:41 UTC
Not sure what is causing it. I've tried toggling freelook, messing with the toolswap and a bunch of other stuff but I can't find the issue. I know baritone has some twitching and thats unavoidable but this is making it where it take 3 times as long to mine a 3x3 area.

Video of my Issue. ---> https://youtu.be/FeeS4VbHRFc

**Comment by HybridWolfe7** [comment] 2024-02-16 05:44
I have the same problem as well I'm using the latest version which it for Minecraft 1.20.4.

**Comment by lostallmymoney** [comment] 2024-02-18 11:37
Same issue here. Please relabel as bug :( Lots of people have the same issue and are doing duplicate posts.

**Comment by ZacSharp** [comment] 2024-02-18 12:25
Relabeling as a bug won't help. There is #4154 and it neither stops people from asking nor did it make any progress towards solving the problem. What would help is someone finally [answering questions](https://github.com/cabaletta/baritone/issues/4154#issuecomment-1774175652) related to their problem instead of waiting until I close the issue after a couple days of silence.

**Comment by ZacSharp** [comment] 2024-02-18 12:27
Just getting an occasional "There is a problem" and at the same time being ignored whenever you try to find out what the problem is is frustrating.

**Comment by DavidPackard** [comment] 2024-02-19 11:43
I found that setting randomLooking113 and randomLooking to 0 seemed to resolve this.

**Comment by ZacSharp** [comment] 2024-02-20 00:07
Since this question is answered with this workaround I'll close it now. Look at #4154 for the current state of an actual fix.

**Closed as completed by ZacSharp** 2024-02-20 00:07 UTC
Labels: question

**Comment by cheslin23t** [comment] 2024-07-22 19:01
the twitching is intended as to avoid server antibotting plugins, the title should be reopened but relabeled as miscalculating reach while randomlooking is enabled
