### ISSUE TITLE
Baritone doesn't know how to place stairs properly

### ISSUE THREAD

**Issue by Milondzije** [cabaletta/baritone#524] opened 2019-07-11 16:15 UTC
Baritone won't build stairs propertly it places them upside down then break them then build it again and this goes on and on any fixes ?
![2019-07-12_13 14 47](https://user-images.githubusercontent.com/52794973/61124779-1ed13980-a4a8-11e9-9e47-62a1a1221057.png)
Like that

**Comment by scorbett123** [comment] 2021-10-30 14:04
Really this is a duplicate of #1326, fixing that issue would fix this.

**Closed by scorbett123** 2021-10-30 14:04 UTC
Labels: bug

**Comment by CHUNKUD** [comment] 2025-01-25 13:06
plz fix this its a big problem and i wanna build a fricking medieval house but its impossible whit this bug
