### ISSUE TITLE
Chainable commands

### ISSUE THREAD

**Issue by TypicalHog** [cabaletta/baritone#615] opened 2019-07-22 11:13 UTC
For example:
.b mine log 6
.b next mine stone 11
.b next mine coal_ore 3
.b next mine iron_ore 6
.b next mine diamond_ore

After getting enough logs it would start getting stone. (since it can't craft a stone pickaxe *yet* user should be able to do .b pause and then craft the pickaxe himself and do .b resume again)
Cancel would cancel all chained commands while some other command (pause, for example, would just pause the current one).
The next keyword can be something else, but I felt like it's appropriate.

Another example:
.b thisway 650
.b next mine diamond_ore 64
.b next home

And another one (useful for walking to a destination through a specific route):
.b goto x z
.b next goto x z
.b next goto x z

This would make baritone way more useful than it is right now. (not saying it's not useful atm, but it can always be better) It would also be a step towards full automation.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Fefect** [comment] 2019-07-22 20:21
I personally don't see the gain in putting the mining tiers through chainable comments (You're still forced to craft the items by yourself), though the second example might be useful. I might take a look at it, don't expect anything though.

**Comment by unsightedmetal6** [comment] 2019-07-23 23:48
> I personally don't see the gain in putting the mining tiers through chainable comments (You're still forced to craft the items by yourself), though the second example might be useful. I might take a look at it, don't expect anything though.

An option would be to automatically craft things. #craft? 

To OP:
This is a great idea, and one that I had on my mind. I would also like to be able to tell Baritone to do things "when it can," such as telling it to #thisway 300 AND #mine log 10 AND #goto chest.
That way it would start on that path, and when it comes across a tree or chest, it will do the respective action.

**Comment by SylveonBottle** [comment] 2019-08-02 05:25
This may be considered done if you're only looking for mining multiple items at the same time (which is what the first examples are suggesting).

The second set of suggestions (go to X first, then Z) might be a duplicate of #176.

Although doing things in combination to eachother (go to X, but also collect Y if you can, like @unsightedmetal6 suggested) would definitely be awesome. You could tell Baritone to walk to a far-off place, but also give priority to killing pigs (for food along the way) and occasionally mining logs (with a super low priority) to collect stuff along the way as to not be just a single trip.
Which is also a duplicate of #186, but it's a good idea.

**Comment by dominikaaaa** [comment] 2020-04-22 13:02
I'm closing this as a duplicate of #176, as it's the exact same concept.

**Closed by dominikaaaa** 2020-04-22 13:02 UTC
Labels: enhancement
