### ISSUE TITLE
game crashes when sand is mines

### ISSUE THREAD

**Issue by the-ragin-pyro** [cabaletta/baritone#491] opened 2019-07-08 04:39 UTC
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm...

fix it, i need to clear a desert. and im not doing it manually

also its a server, anarchy

**Comment by 0-x-2-2** [comment] 2019-07-11 10:29
Dupe of fixed issue #443. Update baritone and try again.

**Comment by AlexApps99** [comment] 2019-08-18 05:41
@the-ragin-pyro please close this issue if the problem is resolved. thanks

**Closed** 2019-08-18 19:45 UTC
