### ISSUE TITLE
Baritone scripting language pog?

### ISSUE THREAD

**Issue by n-o-T-I-n-s-a-n-e** [cabaletta/baritone#3577] opened 2022-07-23 16:15 UTC
Ok so hear me out.
<< Very cool suggestion starting here >>

## Make a scripting language for baritone that allows you to enhance baritone features

Example

1. Define a command like "harvest_sugarcane"

2. Write code
`
const blocks = findBlocksByName("sugar_cane")
var finalBlocks

blocks.foreach( (block) => {
  const blockBelow = blockAt( block.position.x, block.position.y -1, block.position.z)
  if (blockBelow.name  == "sugar_cane"  ) {
    finalBlocks.add(block)
  }
}
mine(finalBlocks);
// wont be perfect as i am writing this on my phone uwu
`
3. run command with '#harvest_sugarcane"

This would stop people requesting features as they can code it themselves

## Final checklist
- [X] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

# i know, very cool

**Comment by scorbett123** [comment] 2022-07-23 16:18
Duplicate of #881

**Closed by scorbett123** 2022-07-23 16:18 UTC
Labels: enhancement

**Comment by n-o-T-I-n-s-a-n-e** [comment] 2022-07-23 17:15
> Duplicate of #881

So is it coming? 😄

**Comment by scorbett123** [comment] 2022-07-24 09:58
It is unlikely to be added any time soon.
