### ISSUE TITLE
More legit camera movement

### ISSUE THREAD

**Issue by Lua51** [cabaletta/baritone#1218] opened 2020-01-01 05:55 UTC
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.
Is there a way to make the camera move slower when snapping onto a block/entity?

## Final checklist
- [yeah i don't see any.] I have not used any OwO's or UwU's in this issue.

**Comment by alexdieu** [comment] 2020-01-01 22:26
Yeah I think so !
You need to change the properties of the main code of baritone
I found the instruction you put speedfly : 1 and I think it should be good

**Comment by S-B99** [comment] 2020-02-28 16:20
Duplicate of #1048

**Closed by S-B99** 2020-02-28 16:20 UTC
Labels: question

**Comment by SennaFoxy** [comment] 2020-07-25 20:38
Would really like smooth camera motion when mining like Optifine can do it when you zoom in so they can probably add it to baritone as an option it would be great as it wouldn't make you look insanely suspicious toward mods on grinding servers where it could easily do tasks like clearing big areas in mines ect. (example https://gyazo.com/beff374f7bd307b428233f65ab046db3

I would also make it so you look where your going cause when your following a path sometimes u straight out run backwards which totally makes the mod unusable on servers where you need to walk far distances.

**Comment by dominikaaaa** [comment] 2020-07-25 20:55
I labelled this issue as a duplicate, if you would like your suggestion to be seen by people then you should comment on the original issue.
