### ISSUE TITLE
#mine not working for blocks like gravel

### ISSUE THREAD

**Issue by Lobeatec** [cabaletta/baritone#1277] opened 2020-02-07 04:24 UTC
## Some information
Operating system: Windows 10
Java version: 1.8.0_241
Minecraft version: 1.13.2
Baritone version: v1.3.5
Forge mods (if used): none
## Exception, error or logs
When i type "#mine gravel or #mine minecraft:gravel" It says "Error at argument 1: Expected ForOptionalBlockMetaData
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
When i type #mine gravel nothing happens

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by jhmiramon** [comment] 2020-02-07 13:39
Having the same issue on 13.2 with impact 4.8.3

**Comment by PublicByte** [comment] 2020-02-28 16:09
Duplicate of #571

**Closed** 2020-02-28 16:10 UTC
Labels: bug

**Comment by wagyourtail** [comment] 2020-03-01 10:01
Umm this wasn't a duplicate... of #571

**Comment by S-B99** [comment] 2020-03-01 13:27
Oh I did misread the issue. It still should be closed, as it is user error.
