### ISSUE TITLE
Option to collect a set amount of materials instead of infinitely mining the closed block in the selected blocks to mine. 

### ISSUE THREAD

**Issue by tomolone** [cabaletta/baritone#1378] opened 2020-03-09 19:13 UTC
## Describe your suggestion
Currently the bot will mine until it either dies, disconnects or has a full inventory. One option that I feel is missing is to gather a preset list of gather-able materials. This option would add extra arguments to #mine or add a new command in order to collect a preset list of materials.

## Settings
Optional syntax for #mine could be "#mine <stone,32 coal_ore,64, oak_log,64 ...> where the amount to gather is specified after the comma. Another way of implementing this could be by adding a separate command like "collect" with the same arguments as the proposed mine modification in order to keep things separated. 

## Context
If you have a list of materials that you want for a build it would be helpful to have Baritone collect a set-list of materials while you do something else. Currently you can not be sure it will actually collect said materials as it can decide to just mine 640 stone and no oak_log instead of 128 logs and 472 stone. I can see myself using this when I am starting on a new world/server and I do not have a ton of resources yet.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] I submitted this unfinished by mistake before please forgive me.

**Comment by S-B99** [comment] 2020-03-09 19:16
Duplicate of #1115

**Closed by S-B99** 2020-03-09 19:16 UTC
Labels: enhancement
