### ISSUE TITLE
Learn to the repo maintainer how issues tickets work

### ISSUE THREAD

**Issue by bphd** [cabaletta/baritone#1322] opened 2020-02-22 19:04 UTC
Learns him that there's a "reply" button to discuss in the SAME (yeah, the s-a-m-e) issue ticket about the issue in order to see if the suggestion is good enough to really correct the problem.

Like learn him that an issue is not 1 reply only and self-closing, that will be a greeeaaat improvement

Thanks

**Comment by S-B99** [comment] 2020-02-22 19:07
Please do not create off topic issues. This is not a bug report. Also please stop creating useless issues.

**Comment by S-B99** [comment] 2020-02-22 19:08
I'm closing your issues because you keep making new ones ignoring what I replied and not following the solution I sent.

**Closed by S-B99** 2020-02-22 19:07 UTC
Labels: bug

**Comment by bphd** [comment] 2020-02-22 19:09
Lie, you closed the first one without knowing if i listen to you or not

And second lie, i don't ignore, i test and tell you that your suggestions basically don't work

**Comment by S-B99** [comment] 2020-02-22 19:12
Please keep on topic and do not comment on issues not pertaining to this repo.

**Comment by bphd** [comment] 2020-02-22 19:19
You play the smart guy but you try to dodge a maximum the real question

You just dodge in order to not modify the code or understand the issue

What a life

Have you ever worked in a real company ? You act like that with the manager when he report you something that don't work on the currently developed app ? You think that it's a game ? What kind of wo/man are you ?

**Comment by S-B99** [comment] 2020-02-22 20:00
Please keep on topic of this repo.

**Comment by S-B99** [comment] 2020-02-22 20:02
>  dodge a maximum the real question
Is this even English?

> without knowing if i listen to you or not
So you made more issues, to complain that you didn't follow the instructions. Huh.

> Have you ever worked in a real company ?

Kiddo, I'm doing volunteer work for free. You're acting really immature and making personal complaints because you can't follow documentation. 

> You think that it's a game ? 

This is legitimately for a game made of of pixelated blocks.

> You act like that with the manager when he report you something that don't work on the currently developed app ?

Again, is this English?

**Comment by bphd** [comment] 2020-02-22 20:05
> Also where did I say I was making fun of you. If you have to defend something like that then you're most likely very young or immature.
Like you said, in the topic

I'm not english native, you try to dodge one more time the point

I make more issue because you closed them without listen to me, and i said that i try your instruction (who were not the real one, because the real point is to set this behaviour by default, not make it on my minecraft)

I can follow documentation but the point is actually not about the doc here

It's a game to make fun of people, not playing minecraft

Again, nice dodge

**Comment by S-B99** [comment] 2020-02-22 20:10
Please keep on topic for this issue.

**Comment by cookiedragon234** [comment] 2020-02-22 20:53
😕😕😕😕😕😕😕😕😕😕

**Comment by S-B99** [comment] 2020-02-22 20:54
My face right now
