### ISSUE TITLE
Continue on disconnect

### ISSUE THREAD

**Issue by freememememe** [cabaletta/baritone#2852] opened 2021-07-08 17:17 UTC
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
I'd like a function where if you lag out of a server but rejoin, you are still continuing your current path.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
None

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
Easier to AFK.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-07-08 19:32
Duplicate of  #421

**Closed by ZacSharp** 2021-07-08 19:32 UTC
Labels: duplicate, enhancement
