### ISSUE TITLE
Suggestion: Command to place light sources for large area.

### ISSUE THREAD

**Issue by McElligot** [cabaletta/baritone#3411] opened 2022-04-22 19:20 UTC
## Describe your suggestion
Hello! My suggestion is for a #light command.  Simply put, this would be a command that would light up an area around the player with light sources (like torches) in their inventory.  So, for instance, if you want to mob proof your base, you could tell the bot to simply "#light 200" from the center of your base, and any spawnable block within 200 blocks of you would then be made to have a light level where no mob could spawn.

## Settings
For settings, I see it working a couple different ways. These are in no particular order, and most are just suggestions/cool things that wouldn't be nessesary.
First is "#light [radius]", where it would make a radius sphere around you and light it up.  This could further be modified by something like "#set lightY [number]" which would change it from a sphere to instead a cylinder, with its height being the lightY value (so that way it doesnt go super far down).  (There are also probably better ways this can be done - this is merely a suggestion for how it might work)
Second is "#set minLightLevel [number]" - this would change the minimum light level for a light to be places.  Default for 1.18 would be 0, but can be changed to things like 7 for older spawning.
Third is "#sel light" - this would light up the area inside of 
Fourth is "#set lightOptimal [on/off]", which could enable or disable the saving of light sources - i.e. if the bot places it wherever there is a light level of 0, or if it finds the optimal spot to place a light
Fifth is #set acceptableLights [blocks]", which would tell the bot which blocks to use as light sources (i.e. torches, glowstone, etc)

## Context
This would help as it would allow for mob-proofing large areas, which typically takes a long time for a player to manually search for all spots a mob could spawn at.  This would then allow mob farms to be improved, as well as general things like base safety.

Thank you reading/considering! Feel free to reply with questions if you have them :)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Mathrandom7910** [comment] 2022-04-22 19:55
I dont really see this being implemented, use freecam to find caves, and clients like meteor have an auto spawn proofer

**Comment by scorbett123** [comment] 2022-04-22 22:13
Duplicate of #863

**Closed by scorbett123** 2022-04-22 22:13 UTC
Labels: enhancement
