### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Scorelord** [cabaletta/baritone#4186] opened 2023-11-07 20:04 UTC
## Some information
Operating system: Windows 11
Java version: 8 Update 391 (build 1.8.0_391-b13)
Minecraft version: 1.20.2
Baritone version: latest (1.20.2)
Other mods (if used):  none
[latest.log](https://github.com/cabaletta/baritone/files/13287788/latest.log)

## How to reproduce
trying to #mine anything, upon entering command baritone spits out the error message

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-11-07 20:18
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-11-07 20:18 UTC
Labels: bug, duplicate
