### ISSUE TITLE
baritone wont place string

### ISSUE THREAD

**Issue by Forcinq** [cabaletta/baritone#2923] opened 2021-08-06 19:02 UTC
## Some information
Operating system: Windows 10
Java version: Java 8 Update 291
Minecraft version: 1.16.5
Baritone version: 1.6.3
Other mods (if used): schematica, lunatrius core

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/6947491/latest.log)

## How to reproduce
1. Load a cactus farm schematic with schematica
2. tell it to start building by layers or not, either way still doesnt work
3. when it gets to the point where it needs to place string, it will send the error, and pause

## Modified settings
AllowInventory - True
BuildInLayers - True

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-08-06 21:38
Duplicate of #1992

**Closed by ZacSharp** 2021-08-06 21:38 UTC
Labels: bug, duplicate
