### ISSUE TITLE
Baritone continue after leaving server

### ISSUE THREAD

**Issue by domitp20** [cabaletta/baritone#1544] opened 2020-04-12 12:58 UTC
Hello, i wanted to build a big house in survival in a server,  is there any command that if i leave the server, that baritone continues there where i lefted the server?
Because, i write .b pause. Then i leave the world, and then i write .b resume, but  nothing happends. Is there any command for that?

**Comment by dominikaaaa** [comment] 2020-04-12 13:00
Duplicate of #1007

**Closed by dominikaaaa** 2020-04-12 13:00 UTC
Labels: question

**Comment by domitp20** [comment] 2020-04-12 13:11
But there is no answer wtf??
