### ISSUE TITLE
[Suggestion] Have Baritone fill shulker boxes when in mining mode

### ISSUE THREAD

**Issue by Leclowndu93150** [cabaletta/baritone#4457] opened 2024-08-03 12:52 UTC

**Comment by ZacSharp** [comment] 2024-08-07 11:39
This has been suggested long ago and someone even started implementing it in #1706, but never finished it.
Would be nice if someone else picked it up / rewrote it.
I'll close this as a duplicate of #605.

**Closed as completed by ZacSharp** 2024-08-07 11:39 UTC
Labels: duplicate, enhancement

**Comment by Leclowndu93150** [comment] 2024-08-07 11:43
my bad
