### ISSUE TITLE
User algorhytms in baritone

### ISSUE THREAD

**Issue by marsuh228** [cabaletta/baritone#1467] opened 2020-03-29 09:57 UTC
## Description
It should be added to baritone. What if my inventory is full or while mining someone is trying to interrupt me? For example: I have left baritone mining some **OrEs**, but my inventory has filled up with iron or coal, but I am not at a computer (in **toilet** actually). So, before mining, i would make an algorhytm to go to a waypoint (home currently) and use the selected chests to put specific items inside. 
Or after building a house I have to go to home, **ya** know.
_Chest if full? My problems_

## Quieres?
Various commands of selecting items, chests and steps of algorhytm, even vanilla or server commands like _/home_.

## Context
Just a bit of automatisation.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any **OwO**'s or f's in this issue.
- [x] Yes.

**Comment by CG573** [comment] 2020-03-29 13:38
This is a really good idea actually...

**Comment by S-B99** [comment] 2020-03-29 16:06
Duplicate of #269

**Closed by S-B99** 2020-03-29 16:06 UTC
Labels: enhancement
