### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by KonradMohr** [cabaletta/baritone#4559] opened 2024-11-18 13:40 UTC
problem: you cannot use boats. my best guess to fix this is that if you make the AI face the direction of where you are going

**Comment by ZacSharp** [comment] 2024-11-18 18:07
It isn't as easy as that. Boats are wider than players, they can't jump, etc.

**Comment by ZacSharp** [comment] 2024-11-18 18:07
Duplicate of #4034

**Closed as completed by ZacSharp** 2024-11-18 18:07 UTC
Labels: duplicate, enhancement
