### ISSUE TITLE
Mine blocks by block tag (in addition to by block id)

### ISSUE THREAD

**Issue by Picklejar05** [cabaletta/baritone#3598] opened 2022-08-08 03:32 UTC
## Describe your suggestion
you'll notice that if you look at a block (eg `oak_log`) with the debug menu, you'll see multiple tags in addition to the id (`logs`, `logs_that_burn`, `oak_logs`, `mineable/axe`). It would be helpful if you could use these tags to tell baritone to mine large groups of blocks without listing each block manually.

## Context
This would be useful because you could use the single command `#mine logs` to automatically mine any logs without first looking around to see what the nearest type is. You could also do something like `#mine diamond_ores` so that baritone doesn't ignore `deepslate_diamond_ore`.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-08-27 02:53
Duplicate of #1089

**Closed by ZacSharp** 2022-08-27 02:53 UTC
Labels: duplicate, enhancement
