### ISSUE TITLE
Build movement is trap in a dead cycle

### ISSUE THREAD

**Issue by zausa** [cabaletta/baritone#2754] opened 2021-05-18 07:28 UTC
Minecraft version:1.16.5
Baritone version:the latest

## How to reproduce
I'm building a mapart.

Bug1:
sometimes it will not break the blocks at the ground.while I  manually break the block ,it will keep moving .
![S__21143640](https://user-images.githubusercontent.com/44993908/118608644-7fd89f80-b7ec-11eb-9ad1-bd5f871bba56.gif)

Bug2:
when it encounter the structure like this , it will trap in this cycle and can't escape . 
after I manually build the next block, it will keep going
![S__21143642](https://user-images.githubusercontent.com/44993908/118608951-da71fb80-b7ec-11eb-8aa9-4253544c9058.gif) 

![S__21143641](https://user-images.githubusercontent.com/44993908/118608926-d47c1a80-b7ec-11eb-9591-588f579f4493.gif)

## Modified settings
allowInventory true
allowDiagonalDescend true
allowDiagonalAscend true
allowWalkOnBottomSlab false
allowParkour true
allowParkourPlace true
pauseMiningForFallingBlocks false
breakFromAbove true
mapArtMode true## Final checklist

- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-05-18 10:28
Please make a seperate issue for your first bug, because the rest of issue is a duplicate of #2173 and you should make one issue per problem.

**Comment by ZacSharp** [comment] 2021-05-18 10:29
Duplicate of #2173

**Closed by ZacSharp** 2021-05-18 10:28 UTC
Labels: bug
