### ISSUE TITLE
Possable pathfinding for water navigting based off of another mobs actions

### ISSUE THREAD

**Issue by SteamDoge9000** [cabaletta/baritone#3040] opened 2021-10-17 19:43 UTC
## Describe your suggestion
this may not be possable but I was exploring and dealing with some drowns and I thought, wait, how do they navigate though the water? and if its like a players then what if something based of their momvent in water could be applied to the navigation for baritone?

## Context
if this is possible and could work, it might help in making a navigation system to traverse water

In my mind for it to cross large ocans it will Dive a bit under the watter and swim using sprint and then after a set amount of time (can be a config value for seconds ) it will resurface and regain its bubbles before going back down and repeating the process till it reaches land

## Final checklist
- [x] I know how to properly use check boxes 
- [ X] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-10-17 20:07
Duplicate of #1483

**Closed by ZacSharp** 2021-10-17 20:07 UTC
Labels: duplicate, enhancement
