### ISSUE TITLE
Add "Ignore Not Exposed Ores" Option in AutoMine

### ISSUE THREAD

**Issue by Enteerman** [cabaletta/baritone#1168] opened 2019-11-28 03:23 UTC
## Describe your suggestion
This option should ignore ores that are not exposed to the air, because some servers use anti-Xray and they will replace not exposed stone with fake ores.

## Settings
There should be an option in automine that will automatically filter out not exposed ores.

## Context
For servers that use anti-Xray plugins, this would be very helpful to automine, because then we can only use legit mine, but we can also use Xray but only targeting exposed ores.

**Comment by koraseeq** [comment] 2019-11-28 20:57
`#legitMine` does that I think

**Comment by Enteerman** [comment] 2019-11-29 13:17
> 
> 
> `#legitMine` does that I think

LegitMine will only mine ores that baritone can see, I want a feature that use xray to find ores, but also ignoring buried ores.

**Comment by Mentalgen** [comment] 2019-11-30 00:58
Wouldn’t you need world data before coming to a chunk to see which ores are real? Most Anti-Xray plugins change the blocks physically and not just visually so it fucks everything up. I would expect only the server knows which ones are the real ores...which is where legitmine comes in since it wont go after any ores that are inside walls.

**Comment by SylveonBottle** [comment] 2019-11-30 16:14
Most anti-xray plugins will only obfuscate blocks that can not be seen normally. So if you're xraying and you see a vein in the open in a ravine, 99% of the cases that's a real ore. Pretty sure they do this so that it doesn't cause ores to just "pop in" infront of users who may lag slightly. 

With that being said, baritone technically doesn't have any form of anti-xray mining. Legitmine definitely works 100% for this case, but it also requires the bot to randomly stumble upon the ore and won't mine directly to ores that are in contact with (cave_)air. If you just want to get diamonds as fast as possible in a server with ore obfuscation, baritone should have a setting for ore obfuscators where it only targets blocks in contact with air.

**Comment by pozhiloy-enotik** [comment] 2020-08-30 12:39
30.08.2020
still the same problem

**Comment by Slhsmile** [comment] 2020-08-30 14:11
added this option pls :D

**Comment by RealIndrit** [comment] 2020-08-30 14:28
I swear some people really dont look through the settings

Toggle legitMine on and set the legitMineYlevel to whatever level the ore is usually spawning at

**Comment by SylveonBottle** [comment] 2020-08-30 14:30
guys calm down I'm waiting for a very important email and you fuckers keep ringing my phone making me jump out of my chair



> I swear some people really dont look through the settings
> 
> Toggle legitMine on and set the legitMineYlevel to whatever level the ore is usually spawning at

I swear some people really don't look through the comments
> LegitMine will only mine ores that baritone can see, I want a feature that use xray to find ores, but also ignoring buried ores.

**Comment by pozhiloy-enotik** [comment] 2020-08-30 14:32
> 
> 
> > `#legitMine` does that I think
> 
> LegitMine will only mine ores that baritone can see, I want a feature that use xray to find ores, but also ignoring buried ores.

@SylveonBottle @RealIndrit

**Comment by RealIndrit** [comment] 2020-08-30 14:32
" I want a feature that use xray to find ores, but also ignoring buried ores." this is a retarded suggestion that is made to break on any server using any kind of anti xray

**Comment by SylveonBottle** [comment] 2020-08-30 14:33
basically we WANT an xraying bot, we don't want to look legit. We just don't want the bot to go to ores spoofed by ore obfuscators  

![image](https://user-images.githubusercontent.com/17802843/91661779-bece9580-eaa3-11ea-83c0-13b1a4b98392.png)

@RealIndrit Imagine turning on legit mine with engine mode 2 and watching baritone fucking kill itself

**Comment by pozhiloy-enotik** [comment] 2020-08-30 14:36
@SylveonBottle That's the point. Maybe, we should make a vote to reopen this?

**Comment by SylveonBottle** [comment] 2020-08-30 14:37
> @SylveonBottle That's the point. Maybe, we should make a vote to reopen this?

I've demanded that we had this issue re-open since some idiot closed it because they couldn't be assed to listen to what OP and others was trying to describe

**Comment by RealIndrit** [comment] 2020-08-30 14:37
Actually, check if "in touch with air" isnt THAT bad idea.... might look into it

**Comment by SylveonBottle** [comment] 2020-08-30 14:39
fucking huzuni had an xray option to "hide buried ores" to bypass anti-xray's like ore obfuscator

**Comment by RealIndrit** [comment] 2020-08-30 14:40
> basically we WANT an xraying bot, we don't want to look legit. We just don't want the bot to go to ores spoofed by ore obfuscators
> 
> ![image](https://user-images.githubusercontent.com/17802843/91661779-bece9580-eaa3-11ea-83c0-13b1a4b98392.png)
> 
> @RealIndrit Imagine turning on legit mine with engine mode 2 and watching baritone fucking kill itself
> 
> Ore obuscators can't spoof ores near air blocks (or most don't since it's insanely computationally challenging to check the POV of every player just to hide fucking iron), so having a mode that can ignore BURIED ores and only go for ores near air blocks is what this suggestion is about.

Also, one problem here, I know that swedish server found a solution for this, which means they hide all ores, (and no it doesnt require that much computing) But in general this is true, which makes it worth to look into

**Comment by Mentalgen** [comment] 2020-08-30 14:42
yeah, no idea why it was closed either, no reason given :/
Been a while since I use Baritone but the #legitMine only goes in a single line till it runs into ores right? The whole point of the suggestion was that you *could* see the ores but the bot wasn't even trying to mine them. Make it so that if it sees that you're in a cave/ravine, to check for ores there. 

Also please explain more about the whole "hiding" ores, as in you have to walk next to the block to see the ore?

**Comment by dominikaaaa** [comment] 2020-08-30 15:31
legit mine will go and mine exposed ores. I closed this because #legitMine already exists and the original issue wasn't as clear.

**Comment by Enteerman** [comment] 2020-08-31 03:28
true

**Comment by Enteerman** [comment] 2020-08-31 03:39
Anti-Xray plugins creates fake ores but we know that exposed ores (that touch air, (flowing) water, lava) are real and with this option it can xray hidden ores e.g. in caves, lava pools, some servers checks transparent blocks in two block radius to be more lag-friendly, so it can be a number option (0 being off, others define radius)

**Comment by SylveonBottle** [comment] 2020-08-31 06:42
They also won't hide ores that are 1 block away from air as well (hidden behind a block).
Because if someone breaks the block, lag will result in them seeing fake gold/diamond etc.

So really this can be applied to "if it's within 2 blocks of an air block". 

Generally most anti-xray servers will have the fake ores disappear within a certain radius, so it can also be applied to "within X blocks of user are also real".

**Comment by cookiedragon234** [comment] 2020-08-31 10:58
Can’t reproduce, please mark this as invalid

**Comment by OccasionalBree** [comment] 2020-08-31 11:06
> Can’t reproduce, please mark this as invalid
@cookiedragon234 

What?

**Comment by OccasionalBree** [comment] 2020-08-31 11:10
+1, this would be a great thing

>  I want a feature that use xray to find ores, but also ignoring buried ores.

**Comment by cookiedragon234** [comment] 2020-08-31 11:13
> > Can’t reproduce, please mark this as invalid
> 
> @cookiedragon234 
> 
> 
> 
> What? 

What?

**Comment by SylveonBottle** [comment] 2020-08-31 12:09
> Can’t reproduce, please mark this as invalid

Ah yes, the "since I'm not having this issue, it means the issue doesn't exist" idiot.
AND the "I have no fucking clue where I am" commenter. 

Wrong issue, buddy. In fact wrong github project entirely. In fact, wrong website. You're looking for https://www.cartoonnetwork.com/

**Comment by dominikaaaa** [comment] 2020-08-31 12:39
Can you all cool it? I've seen nothing but hostility in this issue. I'm tempted to just ask leij to lock it because this is nuts

**Comment by OccasionalBree** [comment] 2020-08-31 13:07
>  I'm tempted to just ask leij to lock it because this is nuts

Issues won't be solved if you lock them

**Comment by SylveonBottle** [comment] 2020-08-31 13:36
> Can you all cool it? I've seen nothing but hostility in this issue. I'm tempted to just ask leij to lock it because this is nuts

Imagine not adding killaura because people were being mean in the comments section 😭

**Comment by Mentalgen** [comment] 2020-09-01 00:31
what the fuck happened here. This was just suggestion ;w;

**Comment by pozhiloy-enotik** [comment] 2020-09-03 17:51
Hello. Any progress on this?)

**Comment by Enteerman** [comment] 2020-09-04 12:05
This issue should be closed since I don't use baritone and I don't play minecraft anymore.

**Comment by SylveonBottle** [comment] 2020-09-04 14:44
> This issue should be closed because I don't use baritone and I don't play minecraft anymore.

If you close it because of that stupid reason, I'm going to create a new issue copy/pasted because I still use baritone and I still play minecraft.

**Closed** 2020-10-14 19:01 UTC
Labels: enhancement

**Comment by bytechef** [comment] 2020-10-15 11:14
> > Can’t reproduce, please mark this as invalid
> 
> Ah yes, the "since I'm not having this issue, it means the issue doesn't exist" idiot.
> AND the "I have no fucking clue where I am" commenter.
> 
> Wrong issue, buddy. In fact wrong github project entirely. In fact, wrong website. You're looking for [cartoonnetwork.com](https://www.cartoonnetwork.com/)

@SylveonBottle Please review the [Github Community Guidlines](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-community-guidelines) and [Baritone Code Of Conduct](https://github.com/cabaletta/baritone/blob/master/CODE_OF_CONDUCT.md), then rephrase your comment using the language of someone over the age of 8.

**Comment by SylveonBottle** [comment] 2020-10-15 22:36
> > > Can’t reproduce, please mark this as invalid
> > 
> > 
> > Ah yes, the "since I'm not having this issue, it means the issue doesn't exist" idiot.
> > AND the "I have no fucking clue where I am" commenter.
> > Wrong issue, buddy. In fact wrong github project entirely. In fact, wrong website. You're looking for [cartoonnetwork.com](https://www.cartoonnetwork.com/)
> 
> @SylveonBottle Please review the [Github Community Guidlines](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-community-guidelines) and [Baritone Code Of Conduct](https://github.com/cabaletta/baritone/blob/master/CODE_OF_CONDUCT.md), then rephrase your comment using the language of someone over the age of 8.

Ok boomer

**Comment by bytechef** [comment] 2020-10-16 10:39
> > > > Can’t reproduce, please mark this as invalid
> > > 
> > > 
> > > Ah yes, the "since I'm not having this issue, it means the issue doesn't exist" idiot.
> > > AND the "I have no fucking clue where I am" commenter.
> > > Wrong issue, buddy. In fact wrong github project entirely. In fact, wrong website. You're looking for [cartoonnetwork.com](https://www.cartoonnetwork.com/)
> > 
> > 
> > @SylveonBottle Please review the [Github Community Guidlines](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-community-guidelines) and [Baritone Code Of Conduct](https://github.com/cabaletta/baritone/blob/master/CODE_OF_CONDUCT.md?rgh-link-date=2020-10-15T22%3A36%3A56Z), then rephrase your comment using the language of someone over the age of 8.
> 
> Ok boomer

Not sure if you find this funny or something but I do not

**Comment by OccasionalBree** [comment] 2020-10-16 10:51
> Not sure if you find this funny or something but I do not 


What do you want now?

**Comment by l1ving** [comment] 2020-10-16 12:25
Petition to lock

**Comment by Mentalgen** [comment] 2020-10-18 05:33
It appears that someone has gone and implemented this function. As such I'm satisfied, and we should all now calm down and act like civil fuckin humans. Voting to lock

**Comment by LHill-16** [comment] 2021-08-17 01:26
What on earth happened here oh god

**Comment by SylveonBottle** [comment] 2021-08-17 01:43
> What on earth happened here oh god

Somebody made a suggestion that's really good and honestly I wish I could've made it myself.
Then somebody who didn't even read the suggestion closed the issue, stating "op didn't make himself clear enough", so I had to make it clear for him.
Then some dude got lost and thought he was replying to an issue report, I told him off, he cried, I made a joke, he cried some more.

Basically, just people trying to close this for the dumbest reasons until it was finally implemented.

**Comment by x4e** [comment] 2021-08-18 14:51
If you do not treat this discussion with respect I will be forced to ban you from the baritone repository.

**Comment by SylveonBottle** [comment] 2021-08-18 19:39
> If you do not treat this discussion with respect I will be forced to ban you from the baritone repository.

The issue's over, it got closed a while ago. What respect are you asking for? "Hey, thank you for closing this issue was being invalid, I'm sorry for thinking that you got lost since another staff member handled it way better than you"?

**Comment by scorbett123** [comment] 2021-08-18 20:25
This issue is closed and has been implemented, please stop arguing in this issue. It just notifies a bunch of people for no real reason.

> If you do not treat this discussion with respect I will be forced to ban you from the baritone repository.

I don't believe that you can do this either.

**Comment by leijurv** [comment] 2021-08-18 21:17
Lol I have no idea who x4e is but they definitely can't ban anyone from this repository.

**Comment by x4e** [comment] 2021-08-20 22:23
I have no idea who Leijurv is but they definitely can't tell me whether or not I can ban someone from this repository.

**Comment by SylveonBottle** [comment] 2021-08-20 23:06
So my original assumption is correct then? That x4e doesn't know where he is I mean

**Comment by leijurv** [comment] 2021-08-21 15:55
<img width="666" alt="Screen Shot 2021-08-21 at 11 55 08 AM" src="https://user-images.githubusercontent.com/3837873/130327652-25cf3c2f-c626-4042-b549-5adc20b11f14.png">

lmao owned

**Comment by Drakesdrs** [comment] 2021-08-21 16:46
bruh what is this
