### ISSUE TITLE
Baritone head shake when cleararea

### ISSUE THREAD

**Issue by ShulkerSakura** [cabaletta/baritone#4296] opened 2024-03-13 08:36 UTC
## Some information
Operating system: Linux
Java version: 21
Minecraft version: 1.20.4
Baritone version: 1.10.2
Other mods (if used): Optifabric, Coordinates hud,Entity Culling,Inventory Profile Next

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
sel 1 x y z
sel 2 x y z
sel cleararea

When using cleararea sometimes baritone will 
aim at two different blocks repeatedly like head shake,then baritone just stuck there.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2024-03-13 23:46
Duplicate of #4154

**Closed as completed by ZacSharp** 2024-03-13 23:46 UTC
Labels: bug, duplicate

**Comment by ZacSharp** [comment] 2024-03-13 23:47
Turn down / off `randomLooking113` (and `randomLooking`) to avoid this problem.
