### ISSUE TITLE
[Configuration Option] PreferAmount

### ISSUE THREAD

**Issue by 0Ariel0** [cabaletta/baritone#3887] opened 2023-03-26 22:37 UTC
## Describe your suggestion
This setting causes Baritone to always choose the side with the most blocks together.

Ex: Right has few blocks but is closer, Left has many more blocks but is further away. Baritone with this setting enabled will choose Left as it has more blocks.

## Settings
PreferAmount
Description: This setting causes Baritone to always choose the side with the most blocks together.

## Context
It will make it better for people to mine, and so it will attract a lot more people.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-03-28 00:53
Duplicate of #3812

**Comment by ZacSharp** [comment] 2023-03-28 00:54
Also you definitely knew about that one since you opened it. Please don't open duplicates.

**Closed by ZacSharp** 2023-03-28 00:53 UTC
Labels: duplicate, enhancement
