### ISSUE TITLE
New command like #locate (structure name, biome name or a player/entity to get her XYZ) and make Baritone more intelligent to use boats in water.

### ISSUE THREAD

**Issue by F6347** [cabaletta/baritone#3420] opened 2022-04-26 19:52 UTC

**Comment by Mathrandom7910** [comment] 2022-04-27 01:34
duplicate of #3294 and using vehicles such as boats is noted at the bottom of [FEATURES.md](https://github.com/cabaletta/baritone/blob/master/FEATURES.md) as unlikely to be added.

**Closed** 2022-04-27 16:29 UTC
Labels: enhancement
