### ISSUE TITLE
I want to use  baritone auto builder , but I don't want to get banned are  there  any settings I can use?   to  help prevent that

### ISSUE THREAD

**Issue by Boi1234242424242** [cabaletta/baritone#1614] opened 2020-04-24 03:00 UTC
And  before  people say Don't  cheat  or something   just skip my thread  because  (I just need  help)

**Comment by sportshead** [comment] 2020-04-24 03:02
Duplicate #1609

**Comment by Boi1234242424242** [comment] 2020-04-24 03:04
dude   I just need help with the settings it's a baritone git hub baritone is a  cheat anywhere... So there  definitely are certain settings that would help

**Comment by dominikaaaa** [comment] 2020-04-24 14:43
Duplicate of #1609

**Closed by dominikaaaa** 2020-04-24 14:43 UTC
Labels: question

**Comment by Boi1234242424242** [comment] 2020-04-25 01:37
Fuck off u stupid faggot

**Comment by sportshead** [comment] 2020-04-25 06:50
@leijurv can you block this guy

**Comment by Aaron2550** [comment] 2020-04-25 13:30
The best thing to do is call the devs you want help from stupid faggots because then they'll ignore you and have one less dumbass to deal with @Boi1234242424242

**Comment by dominikaaaa** [comment] 2020-04-25 16:04
I'm sure personal insults on a professional platform will get you the answer you're seeking.

**Comment by leijurv** [comment] 2020-04-26 18:11
30 day block
