### ISSUE TITLE
Silent mine

### ISSUE THREAD

**Issue by LuckyMika** [cabaletta/baritone#3777] opened 2023-01-02 00:36 UTC
## Describe your suggestion
Basically like any hacked client does it's killaura. You send the look packets to the server instead of changing the view angles locally.

## Settings
A setting to turn it on or off and possibly a setting to change the head rotation when in third person, meaning your view angles dont change but it looks like your character is looking at the block.

## Context
On simple servers with just your friends it makes the experience much easier since you don't just snap to blocks and can instead look around for things such as mobs to prepare to pause baritone and engage in combat. This all just makes the experience much better overall.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by rycbar0** [comment] 2023-01-02 00:46
duplicate of #2271

**Closed** 2023-01-02 00:52 UTC
Labels: enhancement
