### ISSUE TITLE
Save and quit issue

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#10] opened 2018-08-15 13:47 UTC

**Comment by HowardStark** [comment] 2018-08-15 17:49
Can you toss in the exception? I though we’d fixed this.

**Comment by leijurv** [comment] 2018-08-15 18:14
there wasnt an exception, just a hang

**Comment by HowardStark** [comment] 2018-08-16 00:59
Couldn't reproduce. Closing for now.

**Closed by HowardStark** 2018-08-16 00:59 UTC
