### ISSUE TITLE
Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null

### ISSUE THREAD

**Issue by JoShMiQueL** [cabaletta/baritone#3762] opened 2022-12-18 17:27 UTC
## Some information
Operating system: `Microsoft Windows 10 Professional`
Java version: `17.0.5`
Minecraft version: `1.19.3`
Baritone version: `1.8.3`

## Exception, error or logs
```
[19:14:37] [Render thread/INFO]: [System] [CHAT] [Baritone] > mine diamond_ore
[19:14:37] [Render thread/INFO]: Reloading ResourceManager: vanilla
[19:14:38] [Render thread/INFO]: [System] [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[19:14:38] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:147)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.runCommand(ExampleBaritoneControl.java:142)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(ExampleBaritoneControl.java:67)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:69)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:69)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zdj000$sendChatMessage(class_634.java:3673)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:253)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[19:14:38] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(WorldScanner.java:118)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(WorldScanner.java:112)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(MineCommand.java:48)
[19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:142)
[19:14:38] [Render thread/INFO]: [STDERR]: 	... 28 more
```
## How to reproduce
Write in chat `mine diamond_ore`

**Comment by rycbar0** [comment] 2022-12-18 17:31
this is a known issue see #3756
also pls use the unoptimised version to submit logs as they are more readable

**Comment by JoShMiQueL** [comment] 2022-12-18 18:17
> ## Some information
> 
> Operating system: `Microsoft Windows 10 Professional` Java version: `17.0.5` Minecraft version: `1.19.3` Baritone version: `1.8.3`
> ## Exception, error or logs
> 
> ```
> [19:14:37] [Render thread/INFO]: [System] [CHAT] [Baritone] > mine diamond_ore
> [19:14:37] [Render thread/INFO]: Reloading ResourceManager: vanilla
> [19:14:38] [Render thread/INFO]: [System] [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
> [19:14:38] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:147)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(CommandManager.java:84)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.runCommand(ExampleBaritoneControl.java:142)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(ExampleBaritoneControl.java:67)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onSendChatMessage$2(GameEventHandler.java:69)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(GameEventHandler.java:69)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zdj000$sendChatMessage(class_634.java:3673)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:253)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> [19:14:38] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(WorldScanner.java:118)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(WorldScanner.java:112)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(MineCommand.java:48)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager$ExecutionWrapper.execute(CommandManager.java:142)
> [19:14:38] [Render thread/INFO]: [STDERR]: 	... 28 more
> ```
> 
> ## How to reproduce
> 
> Write in chat `mine diamond_ore`

Updated logs

**Comment by ZacSharp** [comment] 2022-12-18 20:33
Duplicate of #3756

**Closed by ZacSharp** 2022-12-18 20:33 UTC
Labels: bug, duplicate
