### ISSUE TITLE
Anti-Baritone plugin easily blocks Baritone and kicks the player in seconds

### ISSUE THREAD

**Issue by VirxEC** [cabaletta/baritone#891] opened 2019-09-01 19:20 UTC
## Some information
Operating system: Windows 10
Java version: 8
Minecraft version: 1.14.4
Baritone version: Newest for 1.14.4
Forge mods (if used): Forge not used

## Exception, error or logs
You can find your logs in `%appdata%/.minecraft/logs/` (Windows) or `/Library/Application\ Support/minecraft/logs` (Mac).

## How to reproduce
Download the anti-cheat plugin called Matrix from https://www.spigotmc.org/resources/matrix-anticheat-hack-killaura-blocker-machine-learning-1-8-1-12-1-13-1-14.64635/, and boot up a server with it. Open Minecraft with Baritone. Personally, I just did #mine oak_log, and the plugin kicked me in seconds with the default settings for Baritone. Please add a legit mode to Baritone where the head moves slower, blocks are placed slower, and everything overall just looks legit to the point where a human can't tell. It might be slower, but that's why it's an option. Also, it should be slower because humans are just slower than computers in general.

## Final checklist
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by LoganDark** [comment] 2019-09-01 22:41
This isn't a bug, it's a suggestion. It's not a bug that Baritone can be detected by Matrix, it's a suggestion for Baritone to attempt to bypass it.

**Comment by VirxEC** [comment] 2019-09-01 22:43
tnx sorry

**Comment by LoganDark** [comment] 2019-09-01 22:43
Well you don't need to close it, @leijurv can just retag it.

**Closed** 2019-09-01 22:43 UTC
Labels: bug

**Comment by VirxEC** [comment] 2019-09-01 22:44
I already ported it to a suggestion... https://github.com/cabaletta/baritone/issues/895

**Comment by LoganDark** [comment] 2019-09-01 22:45
That was incredibly rash, but okay
