### ISSUE TITLE
litematica creative inv

### ISSUE THREAD

**Issue by kittenvr** [cabaletta/baritone#4109] opened 2023-08-20 12:32 UTC
## Describe your suggestion
if you do #litematica and cant find the blocks instead of saying cannot find blocks it just does /give or picks it out of creative invetory

## Settings
weather or not to use /give or open creative inv

## Context
this would be way easier for users

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by kittenvr** [comment] 2023-08-20 12:49
> 

im in creative not operator


> baritone is intended for survival usage if you are in creative there are ways to build schematics magnitudes easier and faster for example litematicas paste mode.

**Comment by Nekiplay** [comment] 2023-08-21 09:02
> > 
> 
> im in creative not operator
> 
> > baritone is intended for survival usage if you are in creative there are ways to build schematics magnitudes easier and faster for example litematicas paste mode.

use litematica printer mod

**Comment by ZacSharp** [comment] 2023-09-05 16:12
Duplicate of #1675

**Closed by ZacSharp** 2023-09-05 16:12 UTC
Labels: duplicate, enhancement
