### ISSUE TITLE
smooth rotate

### ISSUE THREAD

**Issue by pizzav-xyz** [cabaletta/baritone#4115] opened 2023-08-24 11:20 UTC
## Describe your suggestion
make single action smooth rotate

## Settings
wether its on or not and speed

## Context
better bypass

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by pizzav-xyz** [comment] 2023-08-24 11:23
i know this is very hard but i know the baritone team is capable to do it

**Comment by scorbett123** [comment] 2023-08-24 11:28
Duplicate of #2034

**Closed as not planned by scorbett123** 2023-08-24 11:28 UTC
Labels: enhancement

**Comment by pizzav-xyz** [comment] 2023-08-24 11:32
> Duplicate of #2034

it still didnt get added 2 years later tho
