### ISSUE TITLE
ability to move while baritone is doing its thing

### ISSUE THREAD

**Issue by SirJosh3917** [cabaletta/baritone#482] opened 2019-07-07 12:00 UTC
i have had the unfortunate pleasure of doing `#mine portal` and getting stuck in a portal :)
![](https://upl.sirjosh3917.com/RoyalblueEkaltadeta.png)

(enabling portal hacks fixed it but i would like to have human control while doing stuff so i can fight enemies while baritone does its thing)

**Comment by Haxified** [comment] 2019-07-07 12:15
🦍

**Comment by usereewrjrjeejr** [comment] 2019-07-07 12:35
Turn on kill aura 🤡🤡🤡

**Comment by AlexApps99** [comment] 2019-08-18 05:44
@SirJosh3917 while mining the pickaxe is needed to mine blocks. You cannot use two tools at once, so please elaborate what you mean or close the issue.

**Comment by SirJosh3917** [comment] 2019-08-21 00:59
@AlexApps99 i had run the command `#mine portal`, and baritone had travelled to the portal and was trying to mine it. it was unsuccessful as you can tell, but it stayed inside of the portal and didn't let me move around or get out, so i was stuck in a never ending loop of trying to mine the portal, and if someone hit me out, baritone would walk straight back into the portal without giving me a chance to type `#cancel`.

**Comment by AlexApps99** [comment] 2019-08-21 22:18
Looking around and using tools is possible while baritone isn't, walking around is possible when baritone isn't.

There is no practical way to allow control while baritone is busy unless it's a keybind to temporarily pause baritone and resume afterwards. The problem is that you cannot type any command in chat when inside a portal and adding keybinds is outside the scope of baritone as it's primarily command-based.

There is no solution unless unmineable blocks are added to a blacklist so they cannot be mined, or baritone gives up mining a block after it has no progress mining it for a certain time period.

**Comment by S-B99** [comment] 2020-03-29 16:15
This seems like an extreme edge case and for the most part it's impossible to move without stopping baritone from doing it's thing.

**Closed by S-B99** 2020-03-29 16:15 UTC
