### ISSUE TITLE
doesn't mine with baritone only keeps walking

### ISSUE THREAD

**Issue by ghost** [cabaletta/baritone#4253] opened 2024-01-24 20:27 UTC
## Some information
Operating system:
Java version:8 update 391 (build 1.8.0_391-b13)
Minecraft version:1.20.1
Baritone version:baritone-api-fabric-1.20.1-elytra-beta-v1
Other mods (if used): 
fabric-api-0.87.0+1.20.1
litematica-fabric-1.20.1-0.15.0
malilib-fabric-1.20.1-0.16.0
minihud-fabric-1.20.1-0.27.0
shulkerboxtooltip-fabric-4.0.2+1.20
voxelmap-1.20-1.12.8
Wurst-Client-v7.39-MC1.20.1
## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`
[latest.log](https://github.com/cabaletta/baritone/files/14044304/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
I going to mine with baritone but when i was in the came i turn it on and i just keept walking without mining the block (deepslate iron ore) and he was just going somewhere idk
## Modified settings
To get the modified settings run `#modified` in game
assumeExternalAutoTool true
assumeWalkOnWater true
assumeWalkOnLava true
allowDiagonalAscend true
blocksToAvoid powder_snow,sweet_berry_bush,kelp_plant,seagrass,tall_seagrass,ice
allowParkour true
allowParkourPlace true
blockReachDistance 4.5
costHeuristic 4.6
mobAvoidanceRadius 16
pathingMapLoadFactor 0.75
primaryTimeoutMS 500
failureTimeoutMS 2000
planAheadPrimaryTimeoutMS 4000
planAheadFailureTimeoutMS 5000
slowPathTimeoutMS 40000
toastTimer 5000
pathRenderLineWidthPixels 5.0
goalRenderLineWidthPixels 3.0
cachedChunksOpacity 0.5
allowOnlyExposedOresDistance 0
worldExploringChunkOffset -1
buildInLayers true
mineDropLoiterDurationMSThanksLouca 250
followOffsetDirection 0.0
colorCurrentPath 255,0,0
colorNextPath 255,0,255
colorBlocksToBreak 255,0,0
colorBlocksToPlace 0,255,0
colorBlocksToWalkInto 255,0,255
colorBestPathSoFar 0,0,255
colorMostRecentConsidered 0,255,255
colorGoalBox 0,255,0
colorInvertedGoalBox 255,0,0
colorSelection 0,255,255
colorSelectionPos1 0,0,0
colorSelectionPos2 255,200,0
selectionOpacity 0.5
selectionLineWidth 2.0
elytraFireworkSpeed 1.0
elytraConserveFireworks true
elytraAutoJump true
elytraNetherSeed 1141873160
elytraTimeBetweenCacheCullSecs 180
elytraTermsAccepted true

## Final checklist
- [x] I know how to properly use check boxes 
- [ x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2024-01-24 23:46
Duplicate of #4112

**Closed as completed by ZacSharp** 2024-01-24 23:46 UTC
Labels: bug, duplicate
