### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by VoidedKN0X** [cabaletta/baritone#1500] opened 2020-04-03 20:13 UTC
## What do you need help with?
is there a way to make baritone use nearby chests when it need blocks? even when the blocks have never entered inventory?

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment] 2020-04-03 20:14
Duplicate of #495 / #269

**Closed by S-B99** 2020-04-03 20:14 UTC
Labels: question
