### ISSUE TITLE
Baritone not placing strings 

### ISSUE THREAD

**Issue by marvingaye56** [cabaletta/baritone#2705] opened 2021-04-29 23:09 UTC
## Some information
Operating system: Windows 10
Java version: Latest
Minecraft version: 1.12.2
Baritone version: standalone forge 1.2.13
Other mods (if used): Schematica 1.12

## Exception, error or logs

Error in game : 

Unable to do it. Pausing. resume to resume, cancel to cancel

## How to reproduce
1 Make or download cactus farm schematic with string in it.
2 load the schematic
3 try to build using #schematica
4 stings will not be placed

**Comment by scorbett123** [comment] 2021-05-02 19:15
Duplicate of #1992

**Closed by scorbett123** 2021-05-02 19:15 UTC
Labels: bug
