### ISSUE TITLE
Trying to #mine emerald_ore but says An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

### ISSUE THREAD

**Issue by Snattuw** [cabaletta/baritone#4170] opened 2023-10-28 11:04 UTC
## Some information
Operating system: windows 11
Java version: jkd 17
Minecraft version: 1.20.2
Baritone version: Null version (This is normal in a dev environment)
Other mods (if used): 
3d Skin Layers
Better f3
boathud
bobby
custom crosshair mod
essential
freecam
fullbrightness toggle
iris
litematica
lithium
malilib
meteor client
midnightcontrols
Minecraft
mod menu
shulkerbox tooltip
simple voice chat
sodium
wi zoom
worldedit
worldedit cui
[latest.log](https://github.com/cabaletta/baritone/files/13195552/latest.log)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
i typed #mine emerald_ore

## Modified settings
To get the modified settings run `#modified` in game
[Baritone] All modified settings:
[Baritone] allowParkourAscend (Boolean)
[Baritone] blockReachDistance (Float)
[Baritone] cachedChunksOpacity (Float)
[Baritone] colorBestPathSoFar (Color)
[Baritone] colorBlocksToBreak (Color)
[Baritone] colorBlocksToPlace (Color)
[Baritone] colorBlocksToWalkInto (Color)
[Baritone] colorCurrentPath (Color)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-10-28 19:59
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-10-28 19:59 UTC
Labels: bug, duplicate
