### ISSUE TITLE
baritone schematic string

### ISSUE THREAD

**Issue by DoomedButton327** [cabaletta/baritone#3547] opened 2022-07-08 11:40 UTC
i try to build a cactus farm with string but it doesnt place and the baritone gets stuck on the cactus what must i do?? version 1.18.2

**Comment by ZacSharp** [comment] 2022-07-11 20:30
Duplicate of #1992

**Comment by ZacSharp** [comment] 2022-07-11 20:30
I'm afraid we don't know a solution to this problem.

**Closed by ZacSharp** 2022-07-11 20:30 UTC
Labels: duplicate, question
