### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by moonies44** [cabaletta/baritone#2433] opened 2021-02-06 01:10 UTC
Hello. i hope im in the right place.
Baritone , which is being used from the client METEOR (newest version is in that client im told by developers) when turning off "assumewalkonlava" and "assumewalkonwater" , baritone fails to know this and continue's to walk into lava , and water to path. i have turned this off in the module , and also by doing #modified , and then clicking the assume , and turning to false

I have also disabled "jesus" incase this was making baritone walk on water and lava on it own will. to no avail. baritone will continue to walk on water and lava , despite modules being disabled , and jesus being turned off. ultimately leading to "swimming in lava" and drowning.

## Some information
Operating system: windows 10
Minecraft version: 1.16.4
Baritone version: Latest commit as of 06/02/2021
Forge mods (if used):  Meteor client

## Exception, error or logs
No logs indicate .

## How to reproduce
turn off assumewalkonlava and assumewalkonwater

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by l1ving** [comment] 2021-02-06 01:49
Please add a brief but descriptive title

**Comment by l1ving** [comment] 2021-02-06 01:49
I can't reproduce this issue. Please provide alternate steps to reproduce it or more information such as a video. Also make sure you are using the latest version.

**Comment by moonies44** [comment] 2021-02-06 02:31
Alright please leave open I’ll be able to get a video in here tomorrow thank you

**Comment by moonies44** [comment] 2021-02-07 23:08
https://user-images.githubusercontent.com/66435479/107162174-52808800-6999-11eb-99ab-e2dbfdf7fb61.mp4

dispite turning off "assume walk on lava , and assumewalk on water" , it still.. walks on water?

**Comment by ZacSharp** [comment] 2021-02-08 00:16
Your video shows Baritone swimming in water, not walking on water.

**Comment by moonies44** [comment] 2021-02-08 00:17
> Your video shows Baritone swimming in water, not walking on water.

But shouldn't these settings be **avoiding** water , not going into it. lets say it was lava , is baritone supposed to walk me straight into lava then?

**Comment by ZacSharp** [comment] 2021-02-08 00:21
No. Normal behaviour (with `assumeWalkOnWater` and `assumeWalkOnLava` set to false) Baritone will act like a player and swim in water while avoiding lava.
If you set `assumeWalkOnWater` to true, Baritone will assume that you have jesus enabled and try to walk on water.
If you set `assumeWalkOnLava` to true, Baritone will assume that you have jesus enabled *and fireresistance* and try to walk on lava.
I'm not sure whether `assumeWalkOnLava` works without `assumeWalkOnWater`.

**Comment by moonies44** [comment] 2021-02-08 00:30
Okay so if im understanding .. assumewalkonwater and assumewalkonlava both set to true will then allow you to walk on water , and lava , with jesus on **(or swim if jesus if disabled)**

But with both turned off it will try to swim in water / lava anyways ? i remember using this a way back and it was able to avoid lava entirely ( weather is go around it , build over it ) is this no longer possible at all?

**Comment by ZacSharp** [comment] 2021-02-08 00:36
What is so difficult about this?
I said it acts like a player would, and I hope you don't jump into lava just because some Baritone setting is set to false.
These settings tell Baritone that jesus is enabled and to walk on the respective liquid instead of **swimming in water** and **avoiding lava, yes that means bridging where necessary**
Enabling either of them while jesus is disabled will likely fail because it's impossible to follow a path over water by moving in water.

**Comment by ZacSharp** [comment] 2021-02-08 00:59
Someone close this please, it is caused by the user misunderstanding the documentation as well as Baritones behaviour and not a bug.

**Comment by moonies44** [comment] 2021-02-08 01:01
> Someone close this please, it is caused by the user misunderstanding the documentation as well as Baritones behaviour and not a bug.

assumewalkonlava is false , and it walks in lava , though in the chart you state it "avoids lava" ok

**Comment by ZacSharp** [comment] 2021-02-08 01:05
Then upload a video showing how it walks into lava with `assumeWakOnLava` and jesus turned off.
You only showed intended behaviour.

**Closed** 2021-02-08 01:16 UTC
Labels: bug

**Comment by PATXS** [comment] 2021-03-08 07:53
i know this is closed, but i have the same thing happening to me, and i recorded it happening with lava unlike the OP. i'll attach the video below (at the end you can also see that it actually toggles the setting _back on_ once i reconnect to the server).

i am only using meteor client's (0.4.1, latest) built-in baritone integration, on fabric 1.16.5 (loader 0.11.2). let me know if i should open an issue on meteor's github page instead, or if any more info is needed.

here is the video, i make sure the setting is turned off multiple times and yet it immediately goes over lava when mining. 

https://cdn.discordapp.com/attachments/454378929113792512/818390656199950376/2021-03-08_02-36-56.mp4 (too big for github)

**Comment by ZacSharp** [comment] 2021-03-08 08:17
Try it again without meteor, if it doesn't happen open an issue there, if it does happen without Meteor, open a new issue here, because this one is just garbage.

**Comment by julioysmaelhernandezalbarran-jpg** [comment] 2026-03-30 20:51
Alguien me dice porque cuando intento entrar con el meteor cliente me saca y me aparece el error -1
