### ISSUE TITLE
#sel command pathfinding 

### ISSUE THREAD

**Issue by LunalikeMoon** [cabaletta/baritone#2717] opened 2021-05-05 12:10 UTC
when i use baritone or the #sel command it ceeps happening that he trys to place a block to reach for a speciffic block but the sel arear is in the was so we build a block and then destroy it can someone help me ?

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-05-05 19:17
I think adding the block it uses for scaffolding to `buildIgnoreBlocks` helps (unless it needs it for the schematic as well).

**Comment by ZacSharp** [comment] 2021-05-06 09:08
Duplicate of #2173

**Closed by ZacSharp** 2021-05-06 09:08 UTC
Labels: question
