### ISSUE TITLE
I can't use the death waypoints

### ISSUE THREAD

**Issue by Mcriarty** [cabaletta/baritone#3623] opened 2022-08-16 14:39 UTC
## Some information
Operating system:Windows 11
Java version:8
Minecraft version:1.19.2
Baritone version:baritone-fabric-standalone-1.8.3-134-g43d6eadf
Other mods (if used): 

## How to reproduce
Just die 2 times and type #wp goal death and it'll say that multiple waypoints were found. It then proceeds to ask you which one you mean and wants you to click on the wanted one. The click just doesn't do anything so it's impossible to use the death waypoints.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2022-08-16 15:17
Duplicate of #3587.

**Closed by scorbett123** 2022-08-16 15:17 UTC
Labels: bug
