### ISSUE TITLE
 An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

### ISSUE THREAD

**Issue by freshTsunami** [cabaletta/baritone#3783] opened 2023-01-08 10:39 UTC
## Some information
Operating system: Windows 10
Java version: Version 8 Update 351
Minecraft version: 1.19.3
Baritone version: Baritone-fabric-1.19.3-SNAOSHOT.jar

## Other mods: 
AppleSkin
Architectury API (Fabric/Forge)
Cloth Config API (Fabric/Forge)
Fabric API
JourneyMap
Mod Menu
Replanting Crops (Fabric)
Roughly Enough Items Fabric/Forge (REI)
WI Zoom
WorldEdit
WorldEdit CUI (Fabric)

## Exception, error or logs

[11:23:36] [Render thread/INFO]: [System] [CHAT] [Baritone] > mine moss_block
[11:23:36] [Render thread/INFO]: [System] [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[11:23:36] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[11:23:36] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(Unknown Source)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.a(Unknown Source)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.a(Unknown Source)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(Unknown Source)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zdj000$sendChatMessage(class_634.java)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:253)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[11:23:36] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[11:23:36] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source)
[11:23:36] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(Unknown Source)
[11:23:36] [Render thread/INFO]: [STDERR]: 	... 28 more

## How to reproduce

Im Playing on a Server and just type #mine moss_block in The chat

## Modified settings

No Modified settings

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-01-08 14:04
Duplicate of #3756

**Closed by ZacSharp** 2023-01-08 14:04 UTC
Labels: bug, duplicate
