### ISSUE TITLE
Closing doors

### ISSUE THREAD

**Issue by marsuh228** [cabaletta/baritone#1450] opened 2020-03-26 05:31 UTC
I would like to suggest the baritone function closing doors.

Just imagine. You are running from something or someone or just going to your .b wp home and you have got a door at the entrance. It's not so convinient when you go in and just leave it open. Baritone can already open doors, but why cannot he close them?

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment] 2020-03-26 13:52
Duplicate of #389 and there is a pull here #1445

**Closed by S-B99** 2020-03-26 13:52 UTC
Labels: enhancement
