### ISSUE TITLE
would anyone mind telling me a step by step guide on how to import this on the latest mc version

### ISSUE THREAD

**Issue by gravitygo** [cabaletta/baritone#612] opened 2019-07-22 07:30 UTC

**Comment by mrphax0r** [comment] 2019-07-22 08:30
No. Use the installer, building is not for you.

**Comment by mrphax0r** [comment] 2019-07-22 08:33
@gravitygo dupe of #610

**Comment by StijnSimons** [comment] 2019-07-22 12:43
Wait until an official version is out.

**Closed by StijnSimons** 2019-07-22 12:43 UTC
Labels: question
