### ISSUE TITLE
A way to collect materials or locate things from only within a selection

### ISSUE THREAD

**Issue by RepeatGitHub** [cabaletta/baritone#3039] opened 2021-10-17 18:32 UTC
For on servers, so that Baritone doesn't automatically go to a spot where the user doesn't want it to go.

For the command syntax, it could probably be #sel mine <number> <block> or something along those lines.

- [x] I know how to properly use check boxes.
- [x] I have not used any OwO's or UwU's in this issue.
- [x] I like jazz.
- [x] I should probably get a GitHub profile picture.

**Comment by ZacSharp** [comment] 2021-10-17 20:03
Duplicate of #2597

**Comment by ZacSharp** [comment] 2021-10-17 20:03
Duplicate of #2054

**Comment by ZacSharp** [comment] 2021-10-17 20:03
Duplicate of #1114

**Comment by ZacSharp** [comment] 2021-10-17 20:03
When will you guys learn to search before creating issues?

**Closed by ZacSharp** 2021-10-17 20:03 UTC
Labels: duplicate, enhancement
