### ISSUE TITLE
Baritone cant find / locate spawners and , also cant mine it

### ISSUE THREAD

**Issue by Shaurya4356** [cabaletta/baritone#3576] opened 2022-07-23 05:30 UTC
## Some information
Operating system:win 10
Java version: 18
Minecraft version:1.18.2
Baritone version:1.8.3
Other mods (if used): meteor client/fabric loader 1.14.6

stands still on #find spawner
it actually walks here and there, but not to any spawner on #mine
i did #set reset all , then #set prefersilktouch true

possible reason: on #find, it stands still(cuz baritone doesnt knows what spawners look like)
and on #mine it just tries to explore in other chunks

update: same results with forge
tried removing other mods , reseting settings
tried 1.17.1/1.18/1.18.1/1.18.2 same results(fabric+forge)
cleared my .minecraft folder same results
BUT. works on 1.12.2(impact client)
tried removing blocktoavoidbreaking/disallow breaking
and everything
still , cant find it

**Comment by ZacSharp** [comment] 2022-07-23 09:26
`#find` only outputs positions found in the cache and thus will neither move nor find blocks that are not cached with their positions (though spawners should be findable, maybe you haven't found one yet?).
The problem with `#mine` is that spawners are in `blocksToAvoidBreaking` and the default avoidance penalty (`avoidBreakingMultiplier`) is high enough to completely stop Baritone from mining spawners in most cases. Removing spawners from `blocksToAvoidBreaking` fixes this.

**Comment by ZacSharp** [comment] 2022-07-23 09:26
Duplicate of #3143

**Closed by ZacSharp** 2022-07-23 09:26 UTC
Labels: bug, duplicate
