### ISSUE TITLE
Light area feature

### ISSUE THREAD

**Issue by DauntingPear7** [cabaletta/baritone#863] opened 2019-08-28 14:35 UTC
## Describe your suggestion
This feature would work similarly to the clear area feature but it would take a selected area and find blocks where the light level is low enough for hostile mobs to spawn and would place a light emitting block on it or near it to light it up.

## Settings
You could choose the light level acceptable or the block to place and if it should place on walls or not or if it should prioritize on the ground or on walls.

## Context
Lighting up areas is extremely tedious and its super easy to miss a spot so having a bot do it would make it a lot easier.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue. None.

**Comment by scorbett123** [comment] 2022-04-23 07:43
Duplicate of #1347

**Closed by scorbett123** 2022-04-23 07:43 UTC
Labels: enhancement
