### ISSUE TITLE
#mine an unhandled exception occured

### ISSUE THREAD

**Issue by palpex** [cabaletta/baritone#3354] opened 2022-03-24 17:19 UTC
## Some information
Operating system: Windows 11
Java version: 
Minecraft version:1.16.5
Baritone version: 1.6.2 (because1.6.2 crashed my game while i was walking)
Other mods (if used): 
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[GraveStone Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Architectury API (Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-forge)
[Morpheus (by Quetzi)](https://www.curseforge.com/minecraft/mc-mods/morpheus)
[PackMenu (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/packmenu)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[FTB Ranks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-forge)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Stay True Modded Compats (by wedge1453)](https://www.curseforge.com/minecraft/texture-packs/stay-true-modded-compats)
[Dynamic Surroundings (by OreCruncher)](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Light Overlay (Rift/Forge/Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/light-overlay)
[The One Probe (by McJty)](https://www.curseforge.com/minecraft/m
c-mods/the-one-probe)
[Create Plus (by Robocraft999)](https://www.curseforge.com/minecraft/mc-mods/create-plus)
[Cloth Config API (Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
Log:
[latest.log](https://github.com/cabaletta/baritone/files/8343968/latest.log)
## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment] 2022-03-25 00:03
ahh. I see you have flywheel, it has compatibility issues with baritone. iirc you can try `/flywheel chunkCaching off` and see if that fixes it

**Comment by palpex** [comment] 2022-03-25 15:24
It works, thank you <3

**Comment by ZacSharp** [comment] 2022-03-25 21:24
Closing as a duplicate of #2974

**Closed by ZacSharp** 2022-03-25 21:24 UTC
Labels: bug
