### ISSUE TITLE
It dose not mine the specified block

### ISSUE THREAD

**Issue by Slavnik1** [cabaletta/baritone#4193] opened 2023-11-15 18:50 UTC
## Some information
Operating system: windows 10
Java version: 1.8.0_381
Minecraft version: 1.20.2
Baritone version: 1.20.2-20231022.115809-1
Other mods (if used): None Mods used

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: [latest.log](https://github.com/cabaletta/baritone/files/13368130/latest.log)

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
I just run the command #mine minecraft:AnyBlock (In my case any block) and in the chat appears in red font an error that says ,,An unhandled exception occurred. The error is in your game log, please report this at https://github.com/cabaletta/baritone/issues,, Note: i have never used any different settings to baritone other than the setting my client modifies at the time of the issue to only thing modified was the max fall height without water below

## Modified settings
The modified setting: maxFallHeightNoWater 159159

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-11-15 22:50
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-11-15 22:50 UTC
Labels: bug, duplicate

**Comment by ZacSharp** [comment] 2023-11-15 22:52
Also why did you state that you used no mods but later said you are using a client and the log shows meteor, lithium and sodium being loaded?
