### ISSUE TITLE
When will support for 1.17 come out?

### ISSUE THREAD

**Issue by HarryPlays2021** [cabaletta/baritone#2810] opened 2021-06-14 13:39 UTC
When is 1.17 coming out?

**Comment by ZacSharp** [comment] 2021-06-14 15:40
Duplicate of #2807

**Closed by ZacSharp** 2021-06-14 15:40 UTC
Labels: question

**Comment by ZacSharp** [comment] 2021-06-14 15:41
When will you guys understand to
1. search for existing issues before creating new ones
2. don't ask for updates right away, it usually doesn't help
