### ISSUE TITLE
Water drop cancelled by zombie

### ISSUE THREAD

**Issue by nandordena** [cabaletta/baritone#1009] opened 2019-10-03 10:09 UTC
Date: 03/10/2019
TravelTime: 1703:06:35
https://clips.twitch.tv/TriangularPunchyPineappleRickroll

**Comment by Lolfaceftw** [comment] 2019-10-03 11:28
It's not a bug, it's the hack client that chose to fight the zombie rather than place the buckets.

**Comment by leijurv** [comment] 2019-10-07 02:36
@Lolfaceftw is correct, this is an issue with impact's kill aura ignoring baritone's isSafeToCancel system for unpausable movements such as parkour jumps and water bucket falls. closing in favor of https://github.com/ImpactDevelopment/ImpactIssues/issues/1713

**Closed by leijurv** 2019-10-07 02:36 UTC
Labels: bug
