### ISSUE TITLE
I need help with a problem

### ISSUE THREAD

**Issue by FemboyFoxy** [cabaletta/baritone#3892] opened 2023-03-30 05:01 UTC
Basically when I updated to the 1.19.4 version of Baritone every time I go into a world or server I'm stuck crouching and its not crouch toggle or stuck key because when I spam shift my character un-crouches for a second then goes back down and I know its Baritone because when I remove the folder and the api it doesn't stay crouching anymore 

I use Fabric and have litematica in the mods folder with Baritone can anyone help me?

**Comment by rycbar0** [comment] 2023-03-30 08:12
what are your `#modified` settings. are you running any commands or is it crouching when entering the world? try `#cancel` to shut down any running processes. have you tried restarting minecraft?

**Comment by ZacSharp** [comment] 2023-03-30 10:15
Do other inputs (WASD and space) work or are you stuck in place?

**Comment by FemboyFoxy** [comment] 2023-03-30 17:14
for the two people that responded thank you I'm new to GitHub stuff like this so i don't really know how to respond specifically but for Rycbar0 the only setting i have on are allowInventory true, allowParkour true, allowParkourPlace true . and for ZacSharp i can move but its quiet slow since it is constantly crouching and i can fly but cant go up and have to hold space when flying or else it will just go down.

**Comment by FemboyFoxy** [comment] 2023-03-30 18:12
Alright i figured it out apparently Y turns on a constant shift for sum reason

**Comment by ZacSharp** [comment] 2023-03-30 21:45
This is odd
1. As far as I know Baritone simulates all inputs via `InputOverrideHandler` and `InputOverrideHandler` by design cannot "press" WASD, shift or space without blocking all of them.
2. Baritone doesn't interact with your keyboard at all so pressing keys (especially keys without any meaning assigned to them) shouldn't trigger Baritone bugs.

For 1. I thought about it maybe "pressing" (quotes because as I said there is no keyboard interaction) shift every other tick, however testing that on 1.12.2 and 1.17.1 (which version are you using btw?) resulted in visible rapid (un)sneaking and thus can't explain the behavior you described.

**Closed** 2023-04-06 01:21 UTC
Labels: question
