### ISSUE TITLE
Better Support for the #blocksToAvoid & #blocksToAvoidBreaking

### ISSUE THREAD

**Issue by SteamDoge9000** [cabaletta/baritone#3027] opened 2021-10-10 21:29 UTC
## Describe your suggestion
I find that configuring and retyping the setting for the value of blocks that you want to avoid breaking (because modded stuff sometimes gets the bot stuck (ie: stalagnates, etc)) and I was wondering why not use the mechoned commands above and add some sub-commands to it?

*Add: adds the block you are holding to the list (not set); if your holding nothing then it will pull the block that you are looking at (selected block) instead [will give an error if your looking at air]
*Remove: does the opposite of the previous statement; removes blocks from the list 
these 2 addional things to both command will make configuring the bot to specific things in these 2 areas signifigantly easier and less time consuming

adional ideas:

setDefault:
* save: This command takes the current list that you have and saves it and will make it so you can set your personal default (might be best to have this viewed in a seperate txt file? your call)
* load: will load the list that you have ran #command setDefault save and will load back that configuration (running it without a saved list will load back the default configuration (from when you fist installed this mod)
* reset: Self-explanatory; will clear the personal "default" list and also set the list back to the original configurations (can be reverted by clicking on something specifying to undo)

Example line for format: #blocksToAvoid setDefault save

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
this would make configuring the bot to break and work around other blocks 100x easier than it currently is to set up the damn thing; especially useful when you have to deal with modded blocks

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-10-10 21:35
Duplicate of #2196

**Closed by ZacSharp** 2021-10-10 21:35 UTC
Labels: duplicate, enhancement
