### ISSUE TITLE
baritone gets stuck when jumps in water and goes across a block

### ISSUE THREAD

**Issue by MalikPanter** [cabaletta/baritone#3331] opened 2022-03-18 12:27 UTC
in my test world when baritone fell down in some water and the next task is to walk across a block it gets stuck

https://user-images.githubusercontent.com/98454089/159002849-977b786d-82e7-495b-8a94-bf20a4685c57.mp4

.

:).

**Comment by scorbett123** [comment] 2022-03-18 13:40
Duplicate of #3200

**Closed by scorbett123** 2022-03-18 13:41 UTC
Labels: enhancement
