### ISSUE TITLE
Picking up items command

### ISSUE THREAD

**Issue by snah69420** [cabaletta/baritone#3935] opened 2023-05-08 02:18 UTC
Is there a command to pick up items in the player's surroundings? Like, for example #pickup (item_name)

**Comment by rycbar0** [comment] 2023-05-08 20:14
you can use the `#follow entity item` command to walkt to items. this command can not differentiate between different item types. as the default settings only will get you close to a follow goal you also have to change the following setting to actually pick up the items: `#followRadius 0`

**Comment by ZacSharp** [comment] 2023-05-09 00:50
Duplicate of #1043

**Closed by ZacSharp** 2023-05-09 00:50 UTC
Labels: duplicate, enhancement

**Comment by solara322** [comment] 2024-05-27 12:29
Hey, I found a solution.
You need the module “Item Sucker” from the build https://github.com/Zgoly/Meteorist
With these settings.  
![image](https://github.com/cabaletta/baritone/assets/40701744/74df7ef7-55b3-4923-a911-891ed946450d)
