### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by enzipenzo** [cabaletta/baritone#2765] opened 2021-05-20 12:02 UTC
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

I'm trying to plant wart on soul sand using baritone, and it doesn't work. It says that it'll plant and shows green boxes wherever I go, but they don't do anything. I have enough wart, and I've tried selecting the same level as the soul sand, and higher than it

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-05-20 12:18
Duplicate of #1877

**Closed by ZacSharp** 2021-05-20 12:18 UTC
Labels: question

**Comment by ZacSharp** [comment] 2021-05-20 12:19
Also see https://github.com/cabaletta/baritone/issues/2577#issuecomment-801251717 for more related issues
