### ISSUE TITLE
Autoeat Feature

### ISSUE THREAD

**Issue by vMarvin114** [cabaletta/baritone#2326] opened 2021-01-04 12:21 UTC
Hello

It would be really nice if Baritone eat something when the player is hungry !

**Comment by scorbett123** [comment] 2021-01-04 12:27
Many clients already have this, and as baritone is not currently in active development I strongly doubt that this will ever be done as baritone is meant to be used in conjunction with other clients not as a standalone mod. This is also a duplicate of #496.

**Comment by l1ving** [comment] 2021-01-04 13:32
Out of scope

**Closed by l1ving** 2021-01-04 13:32 UTC
Labels: enhancement
