### ISSUE TITLE
Idek what the problem is. I guess can't use it. Using newest version of everything literally installed it 10 min ago.

### ISSUE THREAD

**Issue by Gabocota** [cabaletta/baritone#3362] opened 2022-03-26 03:50 UTC
[21:33:33] [Render thread/INFO]: [CHAT] [Baritone] > mine iron_ore
[21:33:33] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[21:33:33] [Render thread/INFO]: [STDERR]: baritone.au: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[21:33:33] [Render thread/INFO]: [STDERR]: 	at baritone.hc.a(Unknown Source)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at baritone.hb.a(Unknown Source)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at baritone.ew.a(Unknown Source)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at baritone.ew.a(Unknown Source)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at baritone.hd.a(Unknown Source)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at baritone.hd.a(Unknown Source)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zza000$sendChatMessage(class_746.java)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:378)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:371)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:384)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:380)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:472)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:472)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1150)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[21:33:33] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3296
[21:33:33] [Render thread/INFO]: [STDERR]: 	at baritone.z.a(Unknown Source)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at baritone.fe.b(Unknown Source)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at baritone.gg.a(Unknown Source)
[21:33:33] [Render thread/INFO]: [STDERR]: 	... 32 more
[21:33:33] [Render thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3296
[21:33:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[21:33:33] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[21:33:33] [Render thread/INFO]: [STDERR]: 	... 35 more

![image](https://user-images.githubusercontent.com/88735758/160223622-a2f1a36b-ee36-4b6d-9ec9-502dd9bf3940.png)

really don't know what could be the issue

**Comment by zukey26** [comment] 2022-03-26 03:55
Possible duplicate of https://github.com/cabaletta/baritone/issues/3339

**Comment by zukey26** [comment] 2022-03-26 03:57
Also why do you have two instances of baritone in your mods folder

**Comment by Gabocota** [comment] 2022-03-26 04:02
By trying to fix it I tried to put them together to see if that was going to fix it idk but neither work. Yeah I think it is the wrong version. But for me there's no 
1.8.3

**Closed** 2022-03-26 04:45 UTC
Labels: bug
