### ISSUE TITLE
Multiple goals

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [cabaletta/baritone#2984] opened 2021-09-05 11:58 UTC
## Describe your suggestion
U can set Multiple goals at the same time 

## Settings
if baritone goes to the first goal first
if possible non baritone affecting goals

## Context
u could use goals as waypoints or make baritone walks to every goal once at a time

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2021-09-05 15:21
The ability to queue goals is a duplicate of #176, I don't really understand what your meaning by "non baritone affecting goals". 

If you can explain why this isn't a duplicate of #176, then this can be reopened.

**Closed by scorbett123** 2021-09-05 15:21 UTC
Labels: enhancement
