### ISSUE TITLE
crash found when mining.

### ISSUE THREAD

**Issue by Antiswitcher** [cabaletta/baritone#481] opened 2019-07-07 11:39 UTC
"java.util.NoSuchElementException: No value present" is a crash that happens when mining sand. crash occured while on a server.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/7/19 6:29 AM
Description: Unexpected error

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at baritone.bl.a(Unknown Source)
	at baritone.ac.update(Unknown Source)
	at baritone.bo.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$2591/2049040852.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onTick(Unknown Source)
	at cft.handler$runTick$zeh000(SourceFile)
	at cft.m(SourceFile:1244)
	at cft.c(SourceFile:821)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Optional.get(Optional.java:135)
	at baritone.bl.a(Unknown Source)
	at baritone.ac.update(Unknown Source)
	at baritone.bo.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$2591/2049040852.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onTick(Unknown Source)
	at cft.handler$runTick$zeh000(SourceFile)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['Antiswitcher'/20315, l='MpServer', x=2135.54, y=60.00, z=676.52]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-36,70,277), Chunk: (at 12,4,5 in -3,17; contains blocks -48,0,272 to -33,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 22726673 game time, 22883677 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 3 total; [aml['Falling Block'/12233609, l='MpServer', x=2135.50, y=61.81, z=677.50], ctj['Antiswitcher'/20315, l='MpServer', x=2135.54, y=60.00, z=676.52], amm['Sand'/12233607, l='MpServer', x=2135.88, y=61.69, z=677.58]]
	Retry entities: 0 total; []
	Server brand: Travertine (git:Travertine-Bootstrap:1.13-SNAPSHOT:f244724:92) <- TacoSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(SourceFile:418)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:408)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 872996440 bytes (832 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.6
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 550 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU G4560 @ 3.50GHz

**Comment by 0-x-2-2** [comment] 2019-07-07 13:41
dupe of #443?

**Comment by leijurv** [comment] 2019-07-07 17:21
Yeah it is, this will be fixed in next release (which i will do soon™)

**Closed by leijurv** 2019-07-07 17:21 UTC
