### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by KurejiRin** [cabaletta/baritone#4218] opened 2023-12-16 18:51 UTC
## suggestion
it should jump and sprint/run

# Context
gotta go fast

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-12-17 01:13
Duplicate of #563

**Closed as completed by ZacSharp** 2023-12-17 01:13 UTC
Labels: duplicate, enhancement
