### ISSUE TITLE
When using the command #farm crop is not harvested by tool with Fortune

### ISSUE THREAD

**Issue by CloseTape12** [cabaletta/baritone#3647] opened 2022-09-06 00:47 UTC
when farming, need to use tools with a luck charm because it is more effective than a sword or silk

add tool presence check with luck

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-09-06 17:59
Duplicate of #2495

**Closed by ZacSharp** 2022-09-06 17:59 UTC
Labels: duplicate, enhancement
