### ISSUE TITLE
1.20.2 unhandeled exception on servers only

### ISSUE THREAD

**Issue by RadNotRed** [cabaletta/baritone#4160] opened 2023-10-20 21:27 UTC
## Some information
Operating system: 6.5.7-arch1-1
Java version: OpenJDK 17.0.9
Minecraft version: 1.20.2
Baritone version: 1.20.2 self build
Other mods (if used): 
[Additive 1.20.2 modpack](https://modrinth.com/modpack/additive/version/1.21.0+1.20.2.fabric)

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/13058665/latest.log)

## How to reproduce
Go onto a server and try to mine an item, it will give
```
Mining... (block properties)
An unhandeled exception occurred. The error is in your game's log,...
```
This does NOT happen on single player.

## Modified settings
To get the modified settings run `#modified` in game
allowJumpAt256
allowParkourPlace
assumeWalkOnWater
blockPlacementPentalty
chatControl
itemSaver
preferSilkTouch

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-10-20 23:40
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-10-20 23:40 UTC
Labels: bug, duplicate
