### ISSUE TITLE
Unusable advice when entering #follow <player>

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1627] opened 2020-04-26 13:44 UTC
## Some information
Operating system:
Java version: 8
Minecraft version: any
Baritone version: any
Forge mods (if used): none

## Exception, error or logs
[15:38:03] [main/INFO]: [CHAT] [Baritone] > follow _Rxn_7W7R
[15:38:03] [main/INFO]: [CHAT] [Baritone] Error at argument #1: Expected bc

then i tried this:
[15:39:40] [main/INFO]: [CHAT] [Baritone] > follow bc _Rxn_7W7R
[15:39:40] [main/INFO]: [CHAT] [Baritone] Error at argument #1: Expected bd

here all together:
[15:41:49] [main/INFO]: [CHAT] [Baritone] > follow _Rxn_7W7R
[15:41:49] [main/INFO]: [CHAT] [Baritone] Error at argument #1: Expected bc
[15:41:54] [main/INFO]: [CHAT] [Baritone] > follow bc _Rxn_7W7R
[15:41:54] [main/INFO]: [CHAT] [Baritone] Error at argument #1: Expected bd
[15:41:57] [main/INFO]: [CHAT] [Baritone] > follow bd _Rxn_7W7R
[15:41:57] [main/INFO]: [CHAT] [Baritone] Error at argument #1: Expected bd

## How to reproduce
(at first i didnt understand how this works, then i looked it up at github)
Look up
-> i was quite irritated what i should do, cause when typing...
so pls replace the output with:
Usage: <bla>

## Modified settings
unrelevant

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by LoganDark** [comment] 2020-04-26 14:46
Someone removed the proguard exception for the commands module, naughty naughty

**Comment by dominikaaaa** [comment] 2020-04-26 14:47
Duplicate of #1608

**Closed by dominikaaaa** 2020-04-26 14:47 UTC
Labels: bug

**Comment by UltraBlackLinux** [comment] 2020-04-28 08:01
thats no duplicate, just had this username, when i tested the duplicate, didnt want to chose another one

**Comment by dominikaaaa** [comment] 2020-04-28 15:08
Oh. Well then this is user error.
