### ISSUE TITLE
1.16.5 Forge Crashes by Baritone

### ISSUE THREAD

**Issue by GangstaPichu** [cabaletta/baritone#2937] opened 2021-08-15 07:19 UTC
## Some information
Operating system: Windows 10
Java version: 8 update 291 (build 1.8.0_291-b10)
Minecraft version: 1.16.5
Baritone version: 1.6.3 for the 1.16.5 (Should be latest version)
Other mods (if used): 240 or so mods are being used. It's a whole pack. Valhelsia 3 off of curseforge. 

## Exception, error or logs
(Sent all of the crash logs from baritone thusfar)

[crash-2021-08-15_01.43.00-client.txt](https://github.com/cabaletta/baritone/files/6987659/crash-2021-08-15_01.43.00-client.txt)
[crash-2021-08-15_01.34.42-client.txt](https://github.com/cabaletta/baritone/files/6987660/crash-2021-08-15_01.34.42-client.txt)
[crash-2021-08-15_01.23.59-client.txt](https://github.com/cabaletta/baritone/files/6987661/crash-2021-08-15_01.23.59-client.txt)
[crash-2021-08-15_01.20.01-client.txt](https://github.com/cabaletta/baritone/files/6987662/crash-2021-08-15_01.20.01-client.txt)
[crash-2021-08-15_01.15.31-client.txt](https://github.com/cabaletta/baritone/files/6987663/crash-2021-08-15_01.15.31-client.txt)
[crash-2021-08-14_22.19.53-client.txt](https://github.com/cabaletta/baritone/files/6987665/crash-2021-08-14_22.19.53-client.txt)

## How to reproduce
Well, it full on broke. Can't use the mining at all. If you stand on a cog wheel from the create mod it just crashes your game. It also was crashing the game when I was doing nothing. Just sat afk and would come back to a crash log on screen. This all happened over time. Started off with just the random crashes. I removed and replaced the file when I was stuck in a infinite crashing stage when standing on such cog wheels. I think specifically it was the mechanical cog to transport liquids from machines. The game just wouldn't load up. That when the mining feature broke. Said it couldn't path to the areas. Just a whole bunch of null exceptions in the chat for pathing.

## Modified settings
Replace Netherwart True

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment] 2021-08-15 07:29
duplicate of #2148

**Closed by wagyourtail** 2021-08-15 07:29 UTC
Labels: bug
