### ISSUE TITLE
crash while mining gravel

### ISSUE THREAD

**Issue by scottbeebiwan** [cabaletta/baritone#517] opened 2019-07-10 21:45 UTC
[crash-2019-07-10_14.41.28-client.txt](https://github.com/cabaletta/baritone/files/3379502/crash-2019-07-10_14.41.28-client.txt)

**Comment by 0-x-2-2** [comment] 2019-07-11 10:25
Dupe of fixed issue #491. Update baritone and try again.

**Closed** 2019-07-11 21:14 UTC
