### ISSUE TITLE
Soul Sand and Baritone

### ISSUE THREAD

**Issue by WalterWhiteDrugDeal** [cabaletta/baritone#2536] opened 2021-03-05 18:02 UTC
Soul sand and baritone do not like each other very much. Soul sand is not a full block, you can see if you go from a full block such as sand or wood, and then step on soul sand you sink down a little. Therefore baritone thinks it's about to fall off a cliff when stepping on soul sand and so it doesn't step on the soul sand. I noticed there is a settings command to adjust baritones settings. It would be nice if baritone saw soul sand as a full block or if you could add a setting where baritone ignores the slight height adjustment in soul sand. I am trying to afk farm my nether wart and baritone not being able to go onto soul sand does not make this process very easy.

**Comment by scorbett123** [comment] 2021-03-05 18:10
This is a duplicate of #1877.

**Comment by WalterWhiteDrugDeal** [comment] 2021-03-05 18:32
> This is a duplicate of #1877.

Oh my bad.

**Comment by WalterWhiteDrugDeal** [comment] 2021-03-05 18:33
> This is a duplicate of #1877.

yea but see it never got fixed.

**Comment by scorbett123** [comment] 2021-03-05 18:37
He does give a "shit", he just doesn't have the time. This project is mostly out of development meaning that bugs like that have a low chance of getting fixed. It isn't game breaking. It would also add complexity to the code, something that is already quite complex. It is easier to just say that it can't be walked on than having lots of different edge cases.

**Comment by WalterWhiteDrugDeal** [comment] 2021-03-05 18:41
I think I might have a way to do this. I'll put glass above my soul sand with many different pathfinding options, because there won't be a way down, baritone wont simply jump off. So then it'll reach through the wholes and get the nether wart.

**Closed** 2021-03-05 19:19 UTC
Labels: enhancement
