### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null

### ISSUE THREAD

**Issue by Martine1231** [cabaletta/baritone#3517] opened 2022-06-18 07:05 UTC
having a issue. unable to execute commands
[2022-06-17-7.log.gz](https://github.com/cabaletta/baritone/files/8933099/2022-06-17-7.log.gz)

**Comment by ZacSharp** [comment] 2022-06-18 09:54
Duplicate of #3255

**Closed by ZacSharp** 2022-06-18 09:54 UTC
Labels: duplicate
