### ISSUE TITLE
can't water bucket fall if a passable and replacable block like bushes is above the goal

### ISSUE THREAD

**Issue by leijurv** [cabaletta/baritone#14] opened 2018-08-16 00:59 UTC
it raytraces and thinks it's looking at bushes so it doesn't place the water

**Comment by HowardStark** [comment] 2018-08-16 01:04
Low effort duplicate of #15

**Comment by leijurv** [comment] 2018-08-16 01:04
LOL HES FUMING

**Comment by leijurv** [comment] 2018-08-16 01:04
> duplicate
> which is 14 and which is 15 huh?

**Closed by HowardStark** 2018-08-16 01:04 UTC
