### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by RUGMJ7443** [cabaletta/baritone#3191] opened 2022-01-09 12:32 UTC
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

If in future you want to add elytra support you could do the following,

build up to max hight using a nerd poll and then fly at one block above max height so that the bot dosnt encounter any blocks in its path

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
maybe you could change the height that it flys at?

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

It would allow for much faster, far distanced travel

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2022-01-09 12:34
Duplicate of #2328

**Closed by scorbett123** 2022-01-09 12:34 UTC
Labels: enhancement
