### ISSUE TITLE
bot got stuck in one place when swimming (space holding)

### ISSUE THREAD

**Issue by Mer00z** [cabaletta/baritone#3222] opened 2022-01-27 12:01 UTC
like, bot cant swim this is prop bcs im on 1.18

**Comment by zaxophone** [comment] 2022-01-30 22:55
I have the same issue, it gets stuck in one place trying to mine while swimming in 1.18

**Comment by Brzydall** [comment] 2022-01-31 22:08
Same issue

**Comment by NormalHuman-Anything** [comment] 2022-02-14 02:24
same in 1.18.1

**Comment by bokja** [comment] 2022-02-24 21:17
Hmm yes wen fix i pray bump for peeps

**Comment by wagyourtail** [comment] 2022-02-25 00:06
is this is #3200 duplicate?

**Comment by TheMeq** [comment] 2022-02-25 00:08
My issue specifically might be, not sure about OP.

**Comment by scorbett123** [comment] 2022-04-15 20:56
This is a duplicate of #3200

**Closed by scorbett123** 2022-04-15 20:56 UTC
Labels: bug
