### ISSUE TITLE
minecommand     Sudden error.

### ISSUE THREAD

**Issue by wancor1** [cabaletta/baritone#4226] opened 2023-12-24 02:22 UTC
## Translation is used.(I'm not very good at English.)

Operating system:windows 11
Java version:21
Minecraft version:1.20.1
Baritone version:fabric-1.20.1-elytra-beta-v1

I got this bug with mine command.

## logs
[11:13:05] [pool-14-thread-100/ERROR]: Uncaught exception in thread "pool-14-thread-100"
java.lang.ArrayIndexOutOfBoundsException: null
	at jdk.internal.reflect.GeneratedConstructorAccessor135.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689) ~[?:?]
	at java.util.stream.SliceOps$1.opEvaluateParallelLazy(SliceOps.java:151) ~[?:?]
	at java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:434) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at baritone.r.a(Unknown Source) ~[baritone-api-fabric-1.20.1-elytra-beta-v1.jar:?]
	at baritone.r.scanChunkRadius(Unknown Source) ~[baritone-api-fabric-1.20.1-elytra-beta-v1.jar:?]
	at baritone.ej.a(Unknown Source) ~[baritone-api-fabric-1.20.1-elytra-beta-v1.jar:?]
	at baritone.ej.a(Unknown Source) ~[baritone-api-fabric-1.20.1-elytra-beta-v1.jar:?]
	at baritone.ej.b(Unknown Source) ~[baritone-api-fabric-1.20.1-elytra-beta-v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -4 out of bounds for length 24
	at baritone.r.a(Unknown Source) ~[baritone-api-fabric-1.20.1-elytra-beta-v1.jar:?]
	at baritone.r.a(Unknown Source) ~[baritone-api-fabric-1.20.1-elytra-beta-v1.jar:?]
	at baritone.r.b(Unknown Source) ~[baritone-api-fabric-1.20.1-elytra-beta-v1.jar:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.SliceOps$SliceTask.doLeaf(SliceOps.java:629) ~[?:?]
	at java.util.stream.SliceOps$SliceTask.doLeaf(SliceOps.java:572) ~[?:?]
	at java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

## How to reproduce
 sorry. I don't know, it was so sudden.

## Modified settings
allowJumpAt256
allowParkour

**Comment by ZacSharp** [comment] 2023-12-26 01:00
Did it happen when you moved below y level 0?

**Comment by ZacSharp** [comment] 2023-12-31 21:16
Assuming this is a duplicate of #4112

**Comment by ZacSharp** [comment] 2023-12-31 21:16
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-12-31 21:16 UTC
Labels: bug, duplicate

**Comment by wancor1** [comment] 2024-01-12 20:13
I think it's the same as #4112 because y=0 or less.
Sorry. Thank you.
