### ISSUE TITLE
AutoCraft

### ISSUE THREAD

**Issue by 1Jack007** [cabaletta/baritone#3123] opened 2021-12-07 17:40 UTC
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

If I want to make a tunnel and would use my netherite Pickaxe with Mending and the durabilty is low it should craft a new Wood/Stone/Iron/Diamond Pickaxe with my materials (if I have them) and should then just mine with my (temporaily) pickaxe to Coal/Diamonds and then it should switch then to my Mending Netherite Pickaxe.

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

Craft a new pickaxe when xyz durabilty is left
Mine xyz ore with your normal Pickaxe

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

If I have only the Netherite Pickaxe in my inventory and if I would say Baritone that it should do a tunnel which is 1 million blocks long and I sleep then, it wouldn't stop mining then if my pickaxe breaks.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-12-07 21:47
Duplicate of #295

**Closed by ZacSharp** 2021-12-07 21:48 UTC
Labels: duplicate, enhancement
