### ISSUE TITLE
Rapidly sneaking when placing a block -- can't place.

### ISSUE THREAD

**Issue by Lolfaceftw** [cabaletta/baritone#1342] opened 2020-02-28 14:17 UTC
Operating system: Windows 10 Pro x64
Java version: 1.8 
Minecraft version: 1.14.4
Baritone version: 1.4.3
Forge mods (if used): none

Log:
[latest.txt](https://github.com/cabaletta/baritone/files/4267418/latest.txt)

1.) Let Baritone place a block by sneaking.
2.) Characters sneaks rapidly; not placing a block. I have to right click to make it place it.

- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment] 2020-02-28 14:19
Duplicate of #840

**Closed by S-B99** 2020-02-28 14:19 UTC
Labels: bug

**Comment by Lolfaceftw** [comment] 2020-02-28 14:20
@S-B99  What his solution did not work, he had mods while I have none.

**Comment by S-B99** [comment] 2020-02-28 14:21
It's still a duplicate of that issue.

**Comment by S-B99** [comment] 2020-02-28 14:22
That issue doesn't even have any additional mods.

**Comment by Lolfaceftw** [comment] 2020-02-28 14:23
![image](https://user-images.githubusercontent.com/19776239/75556292-e4d59780-5a78-11ea-8d28-4cb45954416c.png)
The issue is the same, but the solution is not?

**Comment by S-B99** [comment] 2020-02-28 14:26
Someone who commented on that issue had a similar issue but the issue is still opened because the real issue is not fixed.

**Comment by Lolfaceftw** [comment] 2020-02-28 14:28
Can you refer that open issue?

**Comment by S-B99** [comment] 2020-02-28 14:28
#840.

**Comment by S-B99** [comment] 2020-02-28 14:29
Please notice using your oculi that the issue is still opened and the original issue was not using any other mods. Some random ass commented had another mod which caused the exact same bug but that's not the original reported issue, which has not been fixed.

**Comment by Lolfaceftw** [comment] 2020-02-28 14:31
Oh okay, I thought the one who commented was the author my bad. I do hope that the issue will be fixed some time because it's really annoying especially when bridging in the nether. I fell one time in lava because of that damn bug.
