### ISSUE TITLE
Specify alternative tool based on item name.

### ISSUE THREAD

**Issue by TheMeq** [cabaletta/baritone#3281] opened 2022-02-25 15:37 UTC
## Describe your suggestion
Please can we have a config that allows us to specify an alternative tool type based on a blocks name? I play on a server that has custom blocks based on things like Noteblocks, for example they use a custom block called "Mud" and when i try to clear it, the automatic tool selected is a axe. I would like to specify that "Mud" gets removed with the Shovel tool instead. Another is "Coal Ore", it is currently replaced with a different kind of noteblock and also attempts to be removed with an Axe, but I would like to specify it should be removed with a pick. This would be super useful. 

## Settings
The ability to list a block, either by it's Name "Dried Mud", or it's qualified item name (funserver:dried_mud) and which tool it should use?

`{`
`	"shovel": ["funserver:dried_mud", "funserver:packed_dirt"],`
`	"pickaxe": ["funserver:iron_ore", "funserver:diamond_ore"]`
`}`

## Context
Players would be able to circumvent servers that use custom block types for items when mining. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-02-26 11:51
I'd say this is a duplicate of #2942, even though that one suggests using slots rather than tool names.
Also even if this was a thing already it likely wouldn't help you because the block you are mining is still `minecraft:noteblock` and not `funserver:dried_mud` and you could only tell Baritone to mine *any* noteblock with a shovel.
The only real solution for you would be an autotool mod written specifically for that server so it can distinguish between the various custom blocks (though unless the server does some crazy things it should be possible to make it useable for many more servers).

**Closed by ZacSharp** 2022-02-26 11:51 UTC
Labels: duplicate, enhancement
