### ISSUE TITLE
unhandled exception while using #mine. The error message told me to put it here

### ISSUE THREAD

**Issue by Blizzen** [cabaletta/baritone#4331] opened 2024-04-10 09:46 UTC
## Some information
Operating system: Win10
Java version: Java 8 update 351
Minecraft version: 1.20.1 (fabric 0.15.7)
Baritone version: baritone-api-fabric-1.20.1-elytra-beta-v1
Other mods (if used): 

architectury-9.2.14-fabric.jar
baritone-api-fabric-1.20.1-elytra-beta-v1.jar
cloth-config-11.1.118-fabric.jar
fabric-api-0.87.0+1.20.1 (2).jar
fabric-language-kotlin-1.10.18+kotlin.1.9.22.jar
light-overlay-8.0.0 (2).jar
litematica-fabric-1.20.1-0.15.3.jar
malilib-fabric-1.20.1-0.16.1.jar
meteor-client-0.5.4-1922.jar
rusherhack-loader.jar
mods\worldedit-mod-7.2.15.jar
mods\WorldTools-fabric-1.2.4+1.20.1.jar
XaeroPlus-2.3+fabric-1.20.1-WM1.38.1-MM24.0.2.jar
XaerosWorldMap_1.38.1_Fabric_1.20.jar
Xaeros_Minimap_24.0.2_Fabric_1.20.jar

## Exception, error or logs
[baritoneerror1.txt](https://github.com/cabaletta/baritone/files/14930496/baritoneerror1.txt)

## How to reproduce
1.) use #mine
2.) get error

## Modified settings
allowvines
anticheatcompat
avoidbreakingmultiplier
blockbreakadditionalpenalty
blockreachdistance
blockstoavoid
blockstoavoidbreaking
buildertickscanradius
buildignoreblocks
elytraminimumdurability
elytratermsaccepted
failuretimeoutms
freelook
itemsaver
minedroploiter
okifair
prefersilktouch
startatlayer

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2024-04-12 21:30
Known bug. You'll have to use a newer version of Baritone.

**Comment by ZacSharp** [comment] 2024-04-12 21:30
Duplicate of #4195

**Closed as completed by ZacSharp** 2024-04-12 21:30 UTC
Labels: bug, duplicate
