### ISSUE TITLE
Turning off auto switch

### ISSUE THREAD

**Issue by StabbyHam** [cabaletta/baritone#3032] opened 2021-10-15 03:34 UTC
Is there a way to turn off my baritone automatically switching from my pickaxe to my hand? im mining beacons and it wont use the beacon pickaxe that has haste

**Comment by wagyourtail** [comment] 2021-10-15 03:37
`#disableAutoTool` (possibly a duplicate of #1985)

**Closed by wagyourtail** 2021-10-15 03:37 UTC
Labels: question
