### ISSUE TITLE
farming addition

### ISSUE THREAD

**Issue by DaCrazyRaccoon** [cabaletta/baritone#3006] opened 2021-09-21 06:15 UTC
## Describe your suggestion
Add bamboo to the .b farm command that would let us plant on moss blocks‌, grass blocks, dirt, coarse dirt, rooted dirt, gravel, mycelium, podzol, sand, or red sand.

## Settings
We could have an option turn off some of these blocks

## Context
Bamboo is useful for furnaces and making sticks, it grows really fast and can be hard to keep up with. It is also a plant that can be farmed and would make sense for it to be included in that command.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-09-21 21:47
Duplicate of #1448

**Closed by ZacSharp** 2021-09-21 21:47 UTC
Labels: duplicate, enhancement
