### ISSUE TITLE
Schematica

### ISSUE THREAD

**Issue by K9Paradox** [cabaletta/baritone#694] opened 2019-07-30 06:33 UTC
## Describe your suggestion
If possible add compatibility for .litematic files alongside of .schematic files. Since Litematica is basically an updated version of Schematica, and works with 1.14.4 but lacks a "print/build" feature.

## Settings
Exact same settings as the ones for schematica , just allow for the added compatibility of using .litmatic files aswell 

## Context
Would allow for the most updated version of a schematic like a mod to work with Baritone. Which in return would be a benefit to anyone using it on 1.14.4 to build amazing structures 
## Final checklist
- [Ok ] I have not used any OwO's or UwU's in this issue.

**Comment by plootia** [comment] 2019-07-30 22:59
duplicate of #668?

**Comment by Nikki-Devil** [comment] 2019-08-05 13:25
#668 Is probably the same suggestion ^^"

**Closed** 2019-08-18 21:44 UTC
Labels: enhancement
