### ISSUE TITLE
Error #mine >0 height (or whatever it's called, I don't know)

### ISSUE THREAD

**Issue by AntidoteAvailable** [cabaletta/baritone#4201] opened 2023-11-21 20:54 UTC
## Some information
Operating system: Windows 10 x64
Java version: 21.0.1
Minecraft version: fabric 1.20.2 (Multi MC)
Baritone version: 
Meteor Client dev build 0.5.5
![изображение](https://github.com/cabaletta/baritone/assets/151463972/101087dc-db7b-408c-ae3a-d923386fb788)

Other mods (if used): 

![изображение](https://github.com/cabaletta/baritone/assets/151463972/8bd46367-ab2b-4056-b654-7abdc18e37ec)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

https://paste.ee/p/nUjkn

## How to reproduce

![изображение](https://github.com/cabaletta/baritone/assets/151463972/d6bacdb4-ec1f-4945-acd2-a7e00b59eef1)

Add your steps to reproduce the issue/bug experienced here:
Initially #mine doesn't search for diamond_ore and deepslate_diamond_ore at the same time, and at altitude y<0 (not y>0, sorry) when diamond_ore is entered, it crashes and can't find ore at all

## Modified settings
![изображение](https://github.com/cabaletta/baritone/assets/151463972/628efced-ed98-42b4-ac6d-ecb5cafbdf51)
![изображение](https://github.com/cabaletta/baritone/assets/151463972/6fd5b784-3675-45c4-b47e-a6c7b35f3b63)
![изображение](https://github.com/cabaletta/baritone/assets/151463972/6aa94ab5-08b3-4f3c-8f66-54b4a266b706)
![изображение](https://github.com/cabaletta/baritone/assets/151463972/b7b8aeff-98be-42e3-b01c-755b15653fc2)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-11-21 23:23
Are you sure it's only y>0 and not y<0 ?

**Comment by Tendas240** [comment] 2023-11-22 14:52
im sure he means y<0.
i got the exact same issue but no one knows how to fix atm apparently.
if someone actually does please provide help or a working version for 1.20.2.

**Comment by AntidoteAvailable** [comment] 2023-11-22 15:25
> Are you sure it's only y>0 and not y<0 ?

it's error only y<0, i'm sorry, I misspelled it.

**Comment by wagyourtail** [comment] 2023-11-22 18:20
> im sure he means y<0. i got the exact same issue but no one knows how to fix atm apparently. if someone actually does please provide help or a working version for 1.20.2.


https://github.com/cabaletta/baritone/actions/runs/6710920414

**Comment by ZacSharp** [comment] 2023-11-22 23:25
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-11-22 23:25 UTC
Labels: bug, duplicate
