### ISSUE TITLE
#follor player ... Throws Unhandled Exception

### ISSUE THREAD

**Issue by Feriixu** [cabaletta/baritone#2361] opened 2021-01-16 18:26 UTC
## Some information
Operating system: Win 10
Java version: 1.8.0_271
Minecraft version: 1.16.4
Baritone version: 1.6.2
Forge mods (if used): Optifine

## Exception, error or logs

```
[16Jan2021 19:21:04.898] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] > follow player MysteriousVixen1
[16Jan2021 19:21:04.898] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] Following these types of entities:
[16Jan2021 19:21:04.899] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: baritone.ay: java.lang.NullPointerException
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.hc.a(Unknown Source)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.hb.a(Unknown Source)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.ez.a(Unknown Source)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.ez.a(Unknown Source)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.hd.a(Unknown Source)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at baritone.hd.a(Unknown Source)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.entity.player.ClientPlayerEntity.handler$zza000$sendChatMessage(ClientPlayerEntity.java)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.entity.player.ClientPlayerEntity.func_71165_d(ClientPlayerEntity.java)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.gui.screen.Screen.func_231159_b_(Screen.java:308)
[16Jan2021 19:21:04.899] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.gui.screen.Screen.func_231161_c_(Screen.java:297)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.optifine.gui.GuiChatOF.func_231161_c_(GuiChatOF.java:41)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.gui.screen.ChatScreen.func_231046_a_(SourceFile:98)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener.lambda$onKeyEvent$4(KeyboardListener.java:457)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:424)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:622)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:621)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:384)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996)
[16Jan2021 19:21:04.900] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16Jan2021 19:21:04.901] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [baritone.ay:a:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[16Jan2021 19:21:04.902] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[16Jan2021 19:21:04.903] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at baritone.command.defaults.FollowCommand.a(Unknown Source)
[16Jan2021 19:21:04.903] [Render thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 46 more
```

## How to reproduce
use #follow player <name>

## Modified settings
none

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.
OwO

**Comment by scorbett123** [comment] 2021-01-16 18:35
Duplicate of #2358

**Comment by l1ving** [comment] 2021-01-17 20:29
fixed on master

**Closed by l1ving** 2021-01-17 20:29 UTC
Labels: bug
