### ISSUE TITLE
Is it possible to use AI for baritone to learn some things?

### ISSUE THREAD

**Issue by LysiBee** [cabaletta/baritone#2848] opened 2021-07-05 22:09 UTC
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-07-05 22:41
If you have the knowledge I'm sure there is a way you could add some sort of ai to Baritone, but I assume this is some sort of suggestion and thus a duplicate of #1622.

Also the term AI is really general and by many of its definitions Baritone is already an AI. You are probably talking about neural networks, which are only some sort of AI.

**Closed by ZacSharp** 2021-07-05 22:41 UTC
Labels: duplicate, question
