### ISSUE TITLE
Show path but don't follow (mine, goto, etc)

### ISSUE THREAD

**Issue by OnlyCS** [cabaletta/baritone#3848] opened 2023-02-20 15:58 UTC
## Describe your suggestion
It would allow the user full control over the player, while still pathfinding.

## Settings
There could be a setting to turn this on or off

## Context
It would allow, e.g. avoidance of mobs, or places that you would not want to go, better

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-02-20 22:17
Duplicate of #431

**Closed by ZacSharp** 2023-02-20 22:17 UTC
Labels: duplicate, enhancement
