### ISSUE TITLE
General water bucket bugginess

### ISSUE THREAD

**Issue by DashGit** [cabaletta/baritone#160] opened 2018-09-12 19:02 UTC
Just some general issues with the 'place water bucket to avoid fall damage' mechanic. It should be noted that all of these happen on the 'commit 72eec13' build and not the latest build available, so if these issues have been patched since then feel free to close this issue. (said build is available [here](https://github.com/cabaletta/baritone/blob/master/IMPACT.md) for testing.)

- Sometimes, when a water bucket is placed, Baritone will not pick it back up and attempt to continue along with the path. This isn't reproducible (at least not in any way I can think of at the moment) but if you give yourself a water bucket and have Baritone navigate a few hundred blocks or so out in an amplified world, this should happen.

- Baritone will attempt to recalculate the path around 80% to 90% of the time upon dropping down using a water bucket, displaying the message in chat "Something has changed in the world and this movement has become impossible. Cancelling." It will continue onwards after the recalculation but it slows pathing down significantly when going from a high Y value to a low Y value utilizing water buckets.

**Comment by leijurv** [comment] 2018-09-12 20:51
Duplicate of #98 and #123, but thanks! 

I'll also update the version available for download there now.

**Closed by leijurv** 2018-09-12 20:51 UTC
Labels: duplicate
