### ISSUE TITLE
Crash when standing on bit collection block (Fabric 1.16.5)

### ISSUE THREAD

**Issue by Unconventional10** [cabaletta/baritone#2978] opened 2021-08-30 23:43 UTC
Baritone will crash the entire game when standing/being on a bits and chisels bit collection block

**Comment by ZacSharp** [comment] 2021-08-31 20:51
Duplicate of #2148

**Comment by ZacSharp** [comment] 2021-08-31 20:51
Also fill in the template next time

**Closed by ZacSharp** 2021-08-31 20:51 UTC
Labels: bug, duplicate, invalid
