### ISSUE TITLE
Create a Mineral Distribution Map

### ISSUE THREAD

**Issue by GodGun968** [cabaletta/baritone#3617] opened 2022-08-12 13:13 UTC
## Describe your suggestion
Create a Mineral Distribution Map use for Servers with mineral obfuscation but cracked map seeds
This allows you to create a single world with seeds, then scan the location of minerals and record these locations,Then the baritone can be based on the Mineral Distribution Map Instead of the server's minerals to mine, this can bypass the mineral obfuscation
## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
I don't konw
## Context
I came across this and thought it would be interesting,It's a whim
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2022-08-15 09:03
Essentially just a duplicate of #3431, anyway this is out of scope

**Closed by scorbett123** 2022-08-15 09:03 UTC
Labels: enhancement

**Comment by GodGun968** [comment] 2022-08-15 15:19
> Essentially just a duplicate of #3431, anyway this is out of scope

okay,thanks
