### ISSUE TITLE
Game keeps crashing after adding baritone

### ISSUE THREAD

**Issue by nightsper** [cabaletta/baritone#4337] opened 2024-04-19 03:35 UTC
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [✓] I know how to properly use check boxes 
- [✓] I have not used any OwO's or UwU's in this issue.

I added meteor client and launched the game and it worked fine but after I added baritone the game keeps crashing. I'm on fabric 1.20.4
Here's the log
[latestlog (3).txt](https://github.com/cabaletta/baritone/files/15032776/latestlog.3.txt)

**Comment by ZacSharp** [comment] 2024-04-19 12:27
Duplicate of #4244

**Comment by ZacSharp** [comment] 2024-04-19 12:27
Just update Baritone and it should work.

**Comment by ZacSharp** [comment] 2024-04-19 12:27
(Except `#elytra` will tell you it's not supported on your system)

**Closed as completed by ZacSharp** 2024-04-19 12:27 UTC
Labels: bug, duplicate

**Comment by nightsper** [comment] 2024-04-20 01:33
> Just update Baritone and it should work.

Wdym by update? I'm using the latest version for fabric, aren't I?

**Comment by nightsper** [comment] 2024-04-20 01:39
This is the file I added to my mods folder https://github.com/cabaletta/baritone/releases/download/v1.10.2/baritone-api-fabric-1.10.2.jar

And this is what happened rn when I tried to launch fabric (it crashed)
[latestlog.txt](https://github.com/cabaletta/baritone/files/15046530/latestlog.txt)

**Comment by ZacSharp** [comment] 2024-04-20 20:34
The release is too old :smile:. You need a build made after March 29 (i.e. including [this](https://github.com/cabaletta/baritone/pull/4280) pull request). If you are logged in you can pick the topmost entry from [this list](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.20.4), scroll down and download the file called "Artifacts". It contains all the files included in a normal release.

**Comment by nightsper** [comment] 2024-04-21 02:20
> The release is too old 😄. You need a build made after March 29 (i.e. including [this](https://github.com/cabaletta/baritone/pull/4280) pull request). If you are logged in you can pick the topmost entry from [this list](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=event%3Apush+is%3Asuccess+branch%3A1.20.4), scroll down and download the file called "Artifacts". It contains all the files included in a normal release.



I added this file (baritone-api-fabric-1.10.2-1-g6d067136.jar) from this artifacts folder https://github.com/cabaletta/baritone/actions/runs/8475101949 to my mods folder and it still crashed I don't know what I'm doing wrong
Here's the log 
[latestlog.txt](https://github.com/cabaletta/baritone/files/15050447/latestlog.txt)

**Comment by ZacSharp** [comment] 2024-04-21 16:18
That one is on Meteor to fix. If you report this to Meteor, you should also send them [these](https://github.com/cabaletta/baritone/commit/d51b23bd1ea09e940b18874b6a0f52843735f48c#diff-20ac2ad58ae3e02c48339b26e344680be33dbcf2f3ac2902a944e0e07ff7cbb7R55) [two](https://github.com/MeteorDevelopment/meteor-client/blob/8a7079652a6bd42cc6acc5cfe8eb917e5d1d0199/src/main/java/meteordevelopment/meteorclient/pathing/BaritoneSettings.java#L80) links in addition to your log file.
