### ISSUE TITLE
Error thrown when using mine command under Y level 0

### ISSUE THREAD

**Issue by AverageKiki** [cabaletta/baritone#4212] opened 2023-12-07 04:33 UTC
Whenever using the mine command under Y level 0 it shows "An unhandled exception occured. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues"

## Some information
Operating system: Windows
Java version: 8
Minecraft version: 1.20.2
Baritone version: Null version (File says 1.20.2)
Other mods (if used): 

## How to reproduce
Go below Y level 0 and use mine command for any blocks

## Modified settings
avoidance (Boolean)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-12-08 21:07
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-12-08 21:07 UTC
Labels: bug, duplicate
