### ISSUE TITLE
The flight path finding

### ISSUE THREAD

**Issue by youll1** [cabaletta/baritone#3521] opened 2022-06-21 17:00 UTC
Play in the server can be obtained by means such as buying flight permissions, but the baritone is still in flight mode pathfinding, in an automated build some building when a large number of repeated use soil to high, whether can be added to the set of flight path finding, since can pathfinding in the ground and avoid obstacles, Wayfinding in the air may also be possible

**Comment by ZacSharp** [comment] 2022-06-21 20:24
This is a duplicate of 12 out of [these 18 issues](https://github.com/cabaletta/baritone/issues?q=is%3Aissue+fly).
You just opened the 13th duplicate.

**Closed by ZacSharp** 2022-06-21 20:24 UTC
Labels: duplicate, enhancement
