### ISSUE TITLE
The #follow command don't work

### ISSUE THREAD

**Issue by TheDogHusky** [cabaletta/baritone#2358] opened 2021-01-15 12:01 UTC
## Some information
Operating system: Windows 10
Java version: I don't know
Minecraft version: 1.15.2
Baritone version: 1.5.3
Forge mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`
Log here: https://pastebin.com/TLkfe6CZ
## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
1 - do #follow player <player>
2 - And the error come !
## Modified settings
To get the modified settings run `#modified` in game
Nothing
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by TheDogHusky** [comment] 2021-01-15 12:10
For modified: [12:57:50] [main/INFO]: [CHAT] [Baritone] > modified
[12:57:50] [main/INFO]: [CHAT] [Baritone] All modified settings:
[12:57:50] [main/INFO]: [CHAT] [Baritone] chatControl (Boolean)
[12:57:50] [main/INFO]: [CHAT] [Baritone] --
[12:57:50] [main/INFO]: [CHAT] [Baritone] --
[12:57:50] [main/INFO]: [CHAT] [Baritone] --
[12:57:50] [main/INFO]: [CHAT] [Baritone] --
[12:57:50] [main/INFO]: [CHAT] [Baritone] --
[12:57:50] [main/INFO]: [CHAT] [Baritone] --
[12:57:50] [main/INFO]: [CHAT] [Baritone] --
[12:57:50] [main/INFO]: [CHAT] [Baritone] << | >> 1/1

**Comment by scorbett123** [comment] 2021-01-15 12:14
I think that this could be to do with the "_" at the front of the name of the player you are trying to follow, have you had this issue with following other players or just this one?

**Comment by TheDogHusky** [comment] 2021-01-15 17:38
That do that with all players I try to follow

**Comment by TheDogHusky** [comment] 2021-01-15 17:39
I find this error with my friend Triforce66

**Comment by TheDogHusky** [comment] 2021-01-17 17:17
Ah. Sorry for opening !

**Comment by scorbett123** [comment] 2021-01-17 17:28
Why? That one is a duplicate of this one.

**Comment by TheDogHusky** [comment] 2021-01-17 17:43
okay

**Comment by TheDogHusky** [comment] 2021-01-17 17:43
i'm sorry for opening this ticket because already have a ticket with this error

**Comment by scorbett123** [comment] 2021-01-17 17:46
This other one was created after you opened this one, so therefore the other person should be sorry, not you. Unless there is another issue that I can't find that this is a duplicate of.

**Comment by TheDogHusky** [comment] 2021-01-17 17:48
okay

**Closed** 2021-01-17 20:29 UTC
Labels: bug
