### ISSUE TITLE
Better Lava Avoidance

### ISSUE THREAD

**Issue by Z3r0ut** [cabaletta/baritone#2126] opened 2020-10-28 12:28 UTC
## Describe your suggestion
To make the bot goes further away from Lava Source blocks and Flowing blocks.

## Settings
#AvoidanceSourceLavadistance
#AvoidanceFlowingLavadistance

## Context
I did die so many times just because the Bot took a path 1 block next to flowing lava cause it touched it for a small moment. Like that i almost certainly die in the nether.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by berrely** [comment] 2020-10-28 12:31
Possible duplicate of #1560

**Closed** 2020-10-28 12:54 UTC
Labels: enhancement
