### ISSUE TITLE
Trace the path without walking

### ISSUE THREAD

**Issue by phaalonso** [cabaletta/baritone#1101] opened 2019-10-26 04:48 UTC
All of us know how clear and open is a baritone user, so i have a suggestion for the goals. My suggestion is a command or a parameter that the baritone will show you the path but dont walk, the user has to done the walking by himself. This will help us mislead the staffs and anti-cheats

**Comment by mrphax0r** [comment] 2019-10-26 10:55
Great idea!

**Comment by TheK0tYaRa** [comment] 2019-10-27 15:08
It defeats half of the idea, but it still has usage. Unless you want to be accused of using Xray while going manually by the path to diamonds xD

**Comment by Footsiefat** [comment] 2019-11-07 20:42
I see what you mean but its still a great idea for normal traversing to a location

**Comment by o0ZzM4g1c** [comment] 2019-11-08 10:37
like #b gps start

**Comment by S-B99** [comment] 2020-03-29 16:20
Duplicate of #431

**Closed by S-B99** 2020-03-29 16:20 UTC
Labels: enhancement
