### ISSUE TITLE
When i use the command mine happens this error.

### ISSUE THREAD

**Issue by Francis4409** [cabaletta/baritone#3665] opened 2022-09-18 15:21 UTC
## Some information
Operating system: Windows 10
Java version: 1.8.0_341-b10
Minecraft version: 1.19
Baritone version: 1.8.3
Other mods (if used):  Supplementaries, Traveler's Backpack, Journey Map, Farmer's Delight, AquaCulture2, Configured, JEI, Serene Seasons

## Exception, error or logs

[debug.log](https://github.com/cabaletta/baritone/files/9595135/debug.log)

[latest.log](https://github.com/cabaletta/baritone/files/9595133/latest.log)

## Modified settings
No one

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
![Screenshot_69](https://user-images.githubusercontent.com/108157187/190914655-d70764ed-1d17-4975-b991-c266d8203e0b.png)

- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-09-18 21:36
Duplicate of #1642

**Closed by ZacSharp** 2022-09-18 21:36 UTC
Labels: bug, duplicate
