### ISSUE TITLE
Crashes when standing on certain blocks from immersive engineering

### ISSUE THREAD

**Issue by jazzybo** [cabaletta/baritone#2349] opened 2021-01-11 18:40 UTC
Not a huge issue obviously but whenever you stand on some blocks from this mod the game just crashes
Operating system: Windows 10
Java version: Latest
Minecraft version: 1.16.4
Baritone version: 1.6.2
Forge mods (if used): the entire valhelsia 3 modpack

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
launch the modpack with baritone in the mods folder
stand on a coke oven from immersive engineering
## Modified settings
To get the modified settings run `#modified` in game
....
## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x
[latest.log](https://github.com/cabaletta/baritone/files/5797688/latest.log)
 ] I have not used any OwO's or UwU's in this issue.

**Comment by jazzybo** [comment] 2021-01-11 18:41
sorry put the log in the wrong spot lol

**Comment by l1ving** [comment] 2021-01-11 18:41
Try uninstalling the "immersive engineering" mod

**Comment by jazzybo** [comment] 2021-01-14 18:32
> Try uninstalling the "immersive engineering" mod

well yeah i know that would work but I'm using it in a modpack server so that would kind of defeat the purpose lol, it's not like i need a fix for it i thought i would just bring it to attention. i did fix it by just having to seperate modpack versions installed, one with baritone and one without.

**Comment by wagyourtail** [comment] 2021-05-19 13:28
duplicate of #2148

**Closed by wagyourtail** 2021-05-19 13:28 UTC
Labels: bug, duplicate
