### ISSUE TITLE
Fix for nether pathing & future movement of lava

### ISSUE THREAD

**Issue by Jacob345k** [cabaletta/baritone#1363] opened 2020-03-06 06:40 UTC
Hey, so if you add like a "Blockstoavoid Radius" type thing, where you can avoid lava or cactus in a radius of like 16 blocks, that would signifigantly increase safety in the nether. Thanks for listening to my ted talk.

**Comment by S-B99** [comment] 2020-03-06 14:32
Duplicate of #806

**Closed by S-B99** 2020-03-06 14:32 UTC
Labels: enhancement
