### ISSUE TITLE
auto crafting and scripting lists

### ISSUE THREAD

**Issue by TheAverageGamer** [cabaletta/baritone#1800] opened 2020-06-17 15:03 UTC
What this would do is you could tell it to mine say 20 logs make crafting table and sticks, make pickaxe mine, make stone pickaxe, get 5 iron and make iron sword and pickaxe... and so on. Just make it so you can write tasks for it to complete then move onto the next task.

**Comment by dominikaaaa** [comment] 2020-06-17 15:07
Duplicate of #880

**Comment by dominikaaaa** [comment] 2020-06-17 15:07
try searching next time

**Closed by dominikaaaa** 2020-06-17 15:07 UTC
Labels: enhancement

**Comment by NatoBoram** [comment] 2020-12-28 03:17
#880 was closed in favour of #295
