### ISSUE TITLE
Running follow on a player that is not within range throws a nullpointer

### ISSUE THREAD

**Issue by psrcek** [cabaletta/baritone#2763] opened 2021-05-19 23:49 UTC
## Some information
Operating system: `Artix Linux, kernel version 5.12.2`
Java version: `openjdk version "11.0.11" 2021-04-20`
Minecraft version: `1.16.5`
Baritone version: `v1.6.3`
Other mods (if used): `Impact nightly 2021-03-08 (current latest)`

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
```log
[01:38:34] [main/INFO]: [CHAT] [B] > follow player [REDACTED]
[01:38:34] [main/INFO]: [CHAT] [B] Following these types of entities:
[01:38:34] [main/INFO]: [CHAT] [B] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[01:38:34] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[01:38:34] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[01:38:34] [main/INFO]: [STDERR]: 	at baritone.y.a(Unknown Source)
[01:38:34] [main/INFO]: [STDERR]: 	at baritone.y.onSendChatMessage(Unknown Source)
[01:38:34] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[01:38:34] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
[01:38:34] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[01:38:34] [main/INFO]: [STDERR]: 	at dzm.handler$sendChatMessage$zej000(SourceFile)
[01:38:34] [main/INFO]: [STDERR]: 	at dzm.f(SourceFile)
[01:38:34] [main/INFO]: [STDERR]: 	at dot.b(SourceFile:313)
[01:38:34] [main/INFO]: [STDERR]: 	at dot.a(SourceFile:293)
[01:38:34] [main/INFO]: [STDERR]: 	at dnq.a(SourceFile:150)
[01:38:34] [main/INFO]: [STDERR]: 	at dka.b(SourceFile:92)
[01:38:34] [main/INFO]: [STDERR]: 	at dot.a(SourceFile:435)
[01:38:34] [main/INFO]: [STDERR]: 	at dka.a(SourceFile:92)
[01:38:34] [main/INFO]: [STDERR]: 	at dka.c(SourceFile:162)
[01:38:34] [main/INFO]: [STDERR]: 	at aob.execute(SourceFile:94)
[01:38:34] [main/INFO]: [STDERR]: 	at dka.b(SourceFile:162)
[01:38:34] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[01:38:34] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[01:38:34] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[01:38:34] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)
[01:38:34] [main/INFO]: [STDERR]: 	at dez.e(SourceFile:308)
[01:38:34] [main/INFO]: [STDERR]: 	at djz.e(SourceFile:1068)
[01:38:34] [main/INFO]: [STDERR]: 	at djz.e(SourceFile:681)
[01:38:34] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:215)
[01:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:38:34] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[01:38:34] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[01:38:34] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[01:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:38:34] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:38:34] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[01:38:34] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[01:38:34] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[01:38:34] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[01:38:34] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[01:38:34] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[01:38:34] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[01:38:34] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
[01:38:34] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[01:38:34] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[01:38:34] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[01:38:34] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[01:38:34] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[01:38:34] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[01:38:34] [main/INFO]: [STDERR]: 	at baritone.command.defaults.FollowCommand.execute(Unknown Source)
[01:38:34] [main/INFO]: [STDERR]: 	... 39 more
```

## How to reproduce
Run follow on a player that's not in range.

## Modified settings
```log
[01:45:02] [main/INFO]: [CHAT] [B] > modified
[01:45:02] [main/INFO]: [CHAT] [B] All modified settings:
[01:45:02] [main/INFO]: [CHAT] [B] allowInventory (Boolean)
[01:45:02] [main/INFO]: [CHAT] [B] allowParkour (Boolean)
[01:45:02] [main/INFO]: [CHAT] [B] assumeStep (Boolean)
[01:45:02] [main/INFO]: [CHAT] [B] assumeWalkOnWater (Boolean)
[01:45:02] [main/INFO]: [CHAT] [B] chatControl (Boolean)
[01:45:02] [main/INFO]: [CHAT] [B] legitMine (Boolean)
[01:45:02] [main/INFO]: [CHAT] [B] legitMineIncludeDiagonals (Boolean)
[01:45:02] [main/INFO]: [CHAT] [B] shortBaritonePrefix (Boolean)
[01:45:02] [main/INFO]: [CHAT] [B] << | >> 1/1
```

## Final checklist
- [x] I know how to properly use check boxes 
- [X] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [X] I have included logs, exceptions and / or steps to reproduce the issue.
- [X] I have not used any OwO's or UwU's in this issue.

**Comment by FloGo3308** [comment] 2021-05-20 06:50
This bug has been in baritone for a really long time, why has no one fixed this yet???

**Comment by Flurrrr** [comment] 2021-05-20 06:52
I can assure you there are **many** bugs that have been in baritone for a pretty long time, probably just low priority as it doesn't really affect anything

**Comment by FloGo3308** [comment] 2021-05-20 06:58
> as it doesn't really affect anything

it crashes your entire game on a simple operation...

**Comment by ZacSharp** [comment] 2021-05-20 08:09
Duplicate of #1926

**Closed by ZacSharp** 2021-05-20 08:09 UTC
Labels: bug
