### ISSUE TITLE
Unable to use Mine command with Y <0

### ISSUE THREAD

**Issue by ktwrd** [cabaletta/baritone#4189] opened 2023-11-10 08:24 UTC
## Some information
Operating system: Windows 10 LTSC (21H2)
Java version: 17.0.4
Minecraft version: 1.20.2
Baritone version: 1.2.19-591-g9bf890a7 (Fabric)
Fabric Loader Version: 0.14.23
Fabric API Version: 0.90.0+1.20.2
Other mods (if used):
```
architectury-10.0.8-fabric.jar
baritone-api-fabric-1.2.19-591-g9bf890a7.jar
BetterPingDisplay-Fabric-1.20.2-1.1.1.jar
bobby-5.0.2.jar
bsvsb-3.0.3.jar
cloth-config-12.0.109-fabric.jar
CraftPresence-2.2.3+1.20.2.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
fabric-api-0.90.0+1.20.2.jar
fabrishot-1.10.0.jar
Female-Gender-Mod-fabric-1.20.2-3.1.jar
indium-1.0.27+mc1.20.1.jar
iris-mc1.20.2-1.6.10.jar
modern-beta-fabric-6.4.1+1.20.jar
modmenu-8.0.0.jar
morechathistory-1.19.1-1.1.1.jar
NoFog-1.3.4_1.16.5-1.20.1-fabric.jar
nvidium-0.2.1-beta.jar
plasmovoice-fabric-1.20.2-2.0.7.jar
RoughlyEnoughItems-13.0.666.jar
shulkerboxtooltip-fabric-4.0.5+1.20.2.jar
sodium-fabric-mc1.20.2-0.5.3.jar
Wurst-Client-v7.38-MC1.20.2.jar
XaerosWorldMap_1.35.0_Fabric_1.20.2.jar
```

## Exception, error or logs
```
[16:14:55] [Render thread/INFO]: [CHAT] [Baritone] > mine coal_ore
[16:14:55] [Render thread/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:coal_ore},properties={}}]
[16:14:55] [Render thread/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 24
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.r.a(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.r.a(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.r.b(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.SliceOps$SliceTask.doLeaf(SliceOps.java:629)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.SliceOps$SliceTask.doLeaf(SliceOps.java:572)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.SliceOps$1.opEvaluateParallelLazy(SliceOps.java:151)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:434)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.r.a(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.r.scanChunkRadius(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.ej.a(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.ej.a(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.ej.mine(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.api.process.IMineProcess.mine(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.bb.execute(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.bt.execute(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.bu.a(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at baritone.bu.onSendChatMessage(Unknown Source)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zde000$baritone$sendChatMessage(class_634.java)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:251)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:98)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:406)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:414)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:402)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:486)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:486)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:287)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1297)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:856)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:253)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
[16:14:55] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
[16:14:55] [Render thread/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
```

## How to reproduce
- Go a position where Y is <0
- Use the mine command
- Baritone walks to try and find a path but doesn't detect any blocks matching the filter.

## Modified settings
None

![screenshot](https://res.kate.pet/upload/8a3f4a6841de/javaw_KPqKxiaGbk.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-11-10 21:01
Duplicate of #4112

**Comment by ZacSharp** [comment] 2023-11-10 21:01
Probably the most informative of the duplicates, but still number 14 on the list. If you rebuild from a945cfaa3c48e6efcece0f84404d7065bce29a7b or use the [CI build](https://github.com/cabaletta/baritone/actions/runs/6710920414) the problem will be gone and you get another major but less noticeable fix on top.

**Closed as completed by ZacSharp** 2023-11-10 21:01 UTC
Labels: bug, duplicate
