### ISSUE TITLE
Legit Headturn

### ISSUE THREAD

**Issue by CG573** [cabaletta/baritone#1470] opened 2020-03-29 13:34 UTC
## Describe your suggestion
A setting so that the player won't snap to wherever they want to look but rather turns their head at an adjustable speed.

## Settings
#LegitFacing (to toggle it between true/false)
#lookspeed [number] (to change the speed at which the head turns)

## Context
This would improve two things:
 a) It looks nicer to watch from a first-person perspective.
 b) It looks less suspicious to other players.

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have not used any OwO's or UwU's in this issue.
- [x] Y E S

**Comment by S-B99** [comment] 2020-03-29 16:09
Duplicate of #1048

**Closed by S-B99** 2020-03-29 16:09 UTC
Labels: enhancement
