### ISSUE TITLE
Baritone having problems with following player

### ISSUE THREAD

**Issue by UltraBlackLinux** [cabaletta/baritone#1569] opened 2020-04-14 21:25 UTC
## Some information
Operating system: linux
Java version: 8
Minecraft version: 1.15.2
Baritone version: 1.5.2
Forge mods (if used): 

## Exception, error or logs
[Log.txt](https://github.com/cabaletta/baritone/files/4477853/Log.txt)

## How to reproduce
follow player

## Modified settings
parkour (place)
backtrackCostFavoringCoefficient 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2020-07-31 23:30
This is a duplicate of #1184 
The callstacks aren't exactly equal but I think that's just because it's a different version and not because it's a different bug

**Closed** 2020-07-31 23:32 UTC
Labels: bug
