### ISSUE TITLE
When building baritone says I'm missing 4x null

### ISSUE THREAD

**Issue by MilkCrispie** [cabaletta/baritone#3432] opened 2022-05-02 19:20 UTC
When I'm building with baritone it keeps pausing the build and telling me I'm missing 4x null

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment] 2022-05-02 22:51
fix your schematic so it doesn't contain nulls

**Comment by ZacSharp** [comment] 2022-05-02 23:37
No, there's really a bug that causes null to end up in the error message even with a sane schematic.
Canceling and restarting the builder "fixes" it, until whatever causes this happens again.

**Comment by ZacSharp** [comment] 2022-05-02 23:46
This is possibly a duplicate of #3428 (which is probably a duplicate as well but it is so detailed I'd rather close the older ones instead)

**Closed** 2022-05-23 20:46 UTC
Labels: question
