### ISSUE TITLE
make baritone work with litematica 

### ISSUE THREAD

**Issue by krispyking24** [cabaletta/baritone#2928] opened 2021-08-09 12:09 UTC
schematica is for pre 1.13 litematica is the same thing but for 1.13+

**Comment by ehylo** [comment] 2021-08-09 14:34
There is already a pr for support for `*.litematic` and im assuming an issue aswell, for now you can use `*.schem` which is for 1.13+ and you can use world edit to make these and baritone should be able to build them

**Comment by ZacSharp** [comment] 2021-08-09 19:34
Duplicate of #668

**Comment by ZacSharp** [comment] 2021-08-09 19:35
The pull request was #2338 and now is #2544

**Closed by ZacSharp** 2021-08-09 19:34 UTC
Labels: duplicate, enhancement
