### ISSUE TITLE
Error pathfinding when using .b mine

### ISSUE THREAD

**Issue by Antipoison7** [cabaletta/baritone#4150] opened 2023-10-08 03:49 UTC
## System Information
Operating system: Windows 10 Home
Java version: Version 8 Update 371 (build 1.8.0_371-b11)
Minecraft version: 1.20.2
Baritone version: baritone-1.20.2
Other mods (if used): Fabric Api, Aristois Build 473
Server: Minecraft Realm

## Reproduce
Type '.b mine (Block)' 
eg. '.b mine diamond_ore'

## Modified settings
avoidance (True)
chatControl (False)
prefix(@)

[2023-10-08-4.log.gz](https://github.com/cabaletta/baritone/files/12839725/2023-10-08-4.log.gz)
[2023-10-08-5.log.gz](https://github.com/cabaletta/baritone/files/12839726/2023-10-08-5.log.gz)

**Comment by ZacSharp** [comment] 2023-10-08 08:52
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-10-08 08:52 UTC
Labels: bug, duplicate
