### ISSUE TITLE
don't mine below gravel if above player

### ISSUE THREAD

**Issue by o0ZzM4g1c** [cabaletta/baritone#1249] opened 2020-01-16 21:24 UTC
## Config:
Win10 x64
Java 8u241 x64
MC 1.12.2
Impact 4.8.3
baritone 1.2.11

## Describe your suggestion
While automining stone by eg, don't mine block above head if gravel is above this block.
Consider gravel as dangerous at coord > Y+3 of the player, as it gives damage.

![gravel](https://user-images.githubusercontent.com/43145135/72563851-d52a3700-38ae-11ea-9d7c-2b517b8f1457.png)

**Comment by PublicByte** [comment] 2020-02-28 16:09
Duplicate of #571

**Closed** 2020-02-28 16:10 UTC
Labels: enhancement

**Comment by SylveonBottle** [comment] 2021-12-07 21:28
I think this is separate from #571

If you mine a stone block with gravel on top of it, this technically wouldn't be "mine gravel from top" - you're simply mining a stone block. however, doing this would result in the gravel falling on you and you taking suffocation damage - which is what this issue is claiming.

**Comment by o0ZzM4g1c** [comment] 2021-12-08 08:37
It's the same behavior intent than mining stone with lava on top of it, but for gravel the only condition (risk for the player) is if he is under the mined block.

**Comment by SylveonBottle** [comment] 2021-12-08 08:56
To be fair, under no circumstances should this ever damage baritone. Baritone doesn't walk around to specific blocks when clearing an area. It simply moves when needed to reach new blocks, then proceeds to mine all the blocks barely within reach distance.

however, this could totally be a problem if baritone attempts to tower up to break a block which happens to have gravel above it, knocking baritone off the tower. I still don't see a proper way of avoiding this however. 


I do suppose a feature could be implimented similar to  https://github.com/cabaletta/baritone/issues/571#issuecomment-512797372, something like `#set instabreakgravel`, where if baritone detects falling gravel/sand it will attempt to place a torch down at the bottom-most block to instantly break all of the gravel.
This would prevent suffication damage (#1249), increase the mining speed of gravel (#571), and just in general be a really neat feature for clearing areas out.
