### ISSUE TITLE
Farm command should take an item parameter.

### ISSUE THREAD

**Issue by xzntrc** [cabaletta/baritone#3380] opened 2022-04-06 07:54 UTC
## Describe your suggestion
I don't see why the farm command takes in a radius and not a specified block. I have a sugar cane farm right next to a wheat farm, when I only want sugarcane, it goes out and gets wheat too.

## Settings
the Farm command should take an item as a parameter like the mine command, and if possible the radius as well.

## Context
It would allow easier farming of the same resource 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-04-06 14:26
Duplicate of #2315

**Closed by ZacSharp** 2022-04-06 14:26 UTC
Labels: duplicate, enhancement
