### ISSUE TITLE
Make baritone not commit die via mobs (read ik you probably have had this posted before)Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Jdeere27** [cabaletta/baritone#3291] opened 2022-03-01 21:22 UTC
So I know someone has probably said this before but I have a few suggestions on how to go about this. The main goal is to get baritone to stop killing itself so much by running straight into a million mobs. So a few idea on how to go about this: 1: have baritone take a different path. If this is too hard, maybe have it consider going around mobs. For example, there are 2 ways it could go, both of which are the same length but one with mobs. Have whether or whether not there are hostile mobs there be a deciding factor. 2: attack the mobs. I'm sure the devs over at Inertia client would be happy to share their kill aura with you. Besides that, if there are mobs around have it hide, pause, and think. Tell Baritone the player's hp, if low tell Baritone to eat whatever is in the hotbar (add a setting for things like rotten flesh, spider eyes, golden apple, etc. or to turn this feature off) and at the same time route a path, taking into consideration: A: Skeletons with their arrows (possible solution: placing blocks to fight off everything else without having to worry about them, then kill them as it did all the other mobs) B: Creepers posing a threat to said solution to skeletons (possible solutions: A: Building up B: Prioritize hitting creepers over other mobs if they get closer than X blocks and/or using anything with knock back against them C: Set them off with flint and steel to nuke all the other mobs then rebuilding skeleton shield or something) C: Endermen (Possible solution: not looking period same with zombie pigmen) you kinda get the jist of what im saying, if you actually did read all of this congrats but im tired of dying while telling it to go mine also the ability to set a keybind to pause etc. would be nice.

**Comment by Justgamer101** [comment] 2022-03-01 23:23
#avoidance command,
duplicate of countless issues/request

auto log
armor
ka
auto eat

**Closed** 2022-03-04 21:23 UTC
Labels: duplicate, enhancement
