### ISSUE TITLE
Minecraft crashing when walking over/near modded blocks with Baritone installed

### ISSUE THREAD

**Issue by Nekron297** [cabaletta/baritone#2752] opened 2021-05-17 18:48 UTC
## Some information
Operating system: Windows 10
Java version: 11.0.8
Minecraft version: 1.16.5 (Forge version 36.1.0)
Baritone version: Baritone API Forge 1.6.3
Other mods (if used): Immersive Engineering, Immersive Petroleum, Applied Energistics 2, Origins(Forge), Create, Curios, Eidolon

[crash-2021-05-17_14.16.18-client.txt](https://github.com/cabaletta/baritone/files/6496150/crash-2021-05-17_14.16.18-client.txt)

I first encountered this issue the other day. It was a few days after I installed baritone, so I didnt immediately link it to baritone. But after looking at logs, it seems the game crashes when I come into contact with modded blocks, such as multiblocks, fluid pipes (From immersive engineering 2), fluix cables (From applied energistics 2) and other suck modded blocks. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-05-17 19:09
It's a know problem that Baritone can't deal with odd shaped blocks.
I think @wagyourtail already had a look at this, but I'm not sure if there is code you could just build and use.

**Comment by Nekron297** [comment] 2021-05-17 19:18
Well here's hoping. I was so confused when I kept crashing. I thought it was because i was phasing through them with the phantom Origin. Ill keep an eye on this to see if wag has anything

**Comment by wagyourtail** [comment] 2021-05-19 13:28
duplicate of #2148

**Closed by wagyourtail** 2021-05-19 13:28 UTC
Labels: bug, duplicate
