### ISSUE TITLE
Swimming and water bridging

### ISSUE THREAD

**Issue by RocketNinja15** [cabaletta/baritone#2881] opened 2021-07-20 18:46 UTC
## Describe your suggestion
This would allow the bot to swim, and not just bob on the surface of the water. Water bridging would not allow the bot to swim, and would bridge over water

## Settings
Swim = true of false
Water bridge = true or false
Bubbles left = 1,2,3,4 etc

## Context
Right now, water is very inconvenient for the bot  

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-07-20 19:41
Duplicate of #1483

**Closed by ZacSharp** 2021-07-20 19:41 UTC
Labels: enhancement

**Comment by ZacSharp** [comment] 2021-07-20 19:42
And for the water bridging:<details><summary>It already does it if necessary</summary>
![2021-07-20_21 27 28](https://user-images.githubusercontent.com/68165024/126385619-7d52d3de-9300-4eee-b8e7-ef2c423b24f4.png)
</details>

**Comment by imanairconditioner** [comment] 2021-07-28 20:14
Baritone often gets stuck in water for me, either going back and forth or staying put. It's extremely detrimental to the use of Baritone beyond its initial novelty factor, besides managing to brick itself inside things it's building. It'd be insanely helpful if Baritone didn't require babysitting incase it gets stuck in these ways.

**Comment by ZacSharp** [comment] 2021-07-28 22:07
@imanairconditioner  this issue suggests making Baritone able to use 1.13+ sprint swimming (already suggested) and making Baritone able to bridge over water (already implemented). Your comment is a complaint about Baritones builder getting stuck in water and the need to babysit it, which is completely unrelated. Please do not comment unrelated things on random issues.

**Comment by eM-Krow** [comment] 2023-01-23 00:23
Ok but it's been almost 2 years now. Still hasn't been fixed unfortunately.
