### ISSUE TITLE
add so baritone can jump from slab to slab

### ISSUE THREAD

**Issue by MalikPanter** [cabaletta/baritone#3332] opened 2022-03-18 14:12 UTC
the title says it all. :). becouse rn it cant what i have tested.

## Final checklist
- [ ] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by asdfugil** [comment] 2022-05-03 11:55
duplicate of #405

**Closed** 2022-05-03 12:22 UTC
Labels: enhancement
