### ISSUE TITLE
Building out Chat Message handling system

### ISSUE THREAD

**Issue by averycowan** [cabaletta/baritone#230] opened 2018-10-21 07:01 UTC
Queued commands or more involved commands aren't possible with the currest system. I'd like to build up a simple but rigorous syntax for more complicated and standardized commands. Reverse compatibility is mandatory.

**Comment by leijurv** [comment] 2018-10-21 20:28
Sounds good! I'd suggest some unit tests to guarantee backwards compatibility. e.g. right now BaritoneAutoTest sets the goal and paths directly, it could instead simulate a chat command "goal 69 420" "path" etc

**Comment by wagyourtail** [comment] 2022-01-14 23:40
maybe we should actually move baritone's command stuff to be ontop of brigadier... might make our lives easier...

**Comment by ZacSharp** [comment] 2022-01-15 00:16
Can we use brigadier in 1.12.2? How would it help?
If you are talking about things like `/execute` then that's already covered by the "new" command system (this issue was opened when command handling was a bunch of `if`s).
And for the queued commands the real problem is how processes work (fire-and-forget activation, cancelling when loosing control, being effectively singletons)

**Comment by wagyourtail** [comment] 2022-01-15 01:12
yes, brigadier can be used on 1.12, you kinda have to shade it yourself tho since mojang isn't using it. (I use it in jsmacros on 1.8.9)
also if this was back when it was if/else'ing, what we currently have is more robust. the main thing with brigadier tho is generally standardizing it more and imo the way baritone currently handles command args is kinda bad and this would make that generally a lot easier.

**Comment by ZacSharp** [comment] 2022-01-15 01:57
I think because even though we have a command system that could handle them we still don't have the commands this issue is about.

**Comment by wagyourtail** [comment] 2022-01-15 02:00
in that case, duplicate of #176

**Closed** 2022-01-15 22:02 UTC
Labels: enhancement
