### ISSUE TITLE
#build .litematic support (and #create ?)

### ISSUE THREAD

**Issue by Nikki-Devil** [cabaletta/baritone#668] opened 2019-07-27 01:21 UTC
## What is _.litematic_ ?
It's the new schematic extention (from the mod [Litematica](https://www.curseforge.com/minecraft/mc-mods/litematica)).

## Why ?
Because (for now) old schematics are not support and the new schematics are "_.litematic_".

## # Create ?
I would like a feature for create with a A coordonate and a B coordonate schematic (or _.litematic_) with Baritone.

## Why ?
Because for now, if Baritone really support # build ; we have to create schematic with a mod, so, quit and reload Minecraft with a schematic mod (for now [Litematica](https://www.curseforge.com/minecraft/mc-mods/litematica)). (So it's long... very long)

## Please
I think it is really important, because Baritone will never be compatible with new schematics (in 1.13 and newer versions of Minecraft).

**Comment by plootia** [comment] 2019-07-27 01:22
agreed, this would be an AMAZING feature. I can make a guide on converting
schematics to litematics if necessary.

**Comment by GrimReaperFloof** [comment] 2019-07-29 00:23
Yeah. That would be really nice. But that's Litematica's format. I heard there's also the Sponge Schematic format, but I can't find any conversion tools for it or anything. Or maybe Litematica's format is based off of it. Does anyone have more info on this?

**Comment by Nikki-Devil** [comment] 2019-07-29 21:22
@plootia Probably have info on this ?

**Comment by plootia** [comment] 2019-07-29 22:44
I do not have any Java experience, but [this](https://github.com/maruohon/litematica/blob/master/src/main/java/fi/dy/masa/litematica/schematic/LitematicaSchematic.java) seems to be a good place to start.

**Comment by Kioyo** [comment] 2019-08-02 17:14
Is there a way to install litematic separately but use in unison?

**Comment by FTC55** [comment] 2019-09-07 16:43
Experimenting with it rn. Might send a pull request if i get anywhere.

**Comment by Nikki-Devil** [comment] 2019-11-27 19:51
It is add or in comming ?

**Comment by Mhowser** [comment] 2020-02-24 05:52
Any update to this?

**Comment by S-B99** [comment] 2020-02-24 05:53
No, the issue is still opened.

**Comment by Mhowser** [comment] 2020-02-24 05:54
Darn, I hope it will be implemented soon.

**Comment by Mhowser** [comment] 2020-03-02 21:32
> Yeah. That would be really nice. But that's Litematica's format. I heard there's also the Sponge Schematic format, but I can't find any conversion tools for it or anything. Or maybe Litematica's format is based off of it. Does anyone have more info on this?

Here is some info https://github.com/maruohon/litematica/issues/53

**Comment by maruohon** [comment] 2020-03-02 22:39
Litematica will include support for converting between it's own format, Sponge schematics, vanilla Structure Block templates, and the old MCEdit/Schematica format. So it's not necessarily required to support the Litematica format directly in Baritone, the Sponge schematic format would be sufficient, and that format is also used by World Edit etc. anyway.

That conversion support currently exists in the 1.12 codebase (master branch), but the 1.13.2+ versions don't have it yet, nor do the pre-compiled 1.12 builds yet.
The relevant code for the schematics in Litematica is here, in case you do want to support the Litematica format, or just basically lift the support for the other formats as well from the Litematica code base:

https://github.com/maruohon/litematica/tree/master/src/main/java/fi/dy/masa/litematica/schematic

**Comment by 0-x-2-2** [comment] 2020-03-22 09:16
Baritone already supports Sponge format so this should be fine.

**Comment by numpadd** [comment] 2021-02-09 10:32
With Baritone now being supported on Fabric, is there any chance this would be possible now?

**Comment by scorbett123** [comment] 2021-02-09 10:43
There is a pull, it hasn't been merged yet. This is therefore possible, however when it will finally be merged is unknown due to some issues with it.

**Comment by minebotter** [comment] 2021-09-12 15:00
@scorbett123 any updates?

**Comment by scorbett123** [comment] 2021-09-12 15:01
Nope

**Comment by NormalHuman-Anything** [comment] 2022-02-15 07:33
still no pull?

**Comment by ZacSharp** [comment] 2022-02-15 20:13
Just look up 4 comments and follow the link in https://github.com/cabaletta/baritone/issues/668#issuecomment-775846194, at the bottom you'll find the notice that it was closed in favor of #2544. So not "still no pull"; there's two.

**Comment by JaaiDead** [comment] 2022-02-22 17:43
Any Updates On this?

**Comment by 5HT2** [comment] 2022-04-15 09:26
I might look into doing this once I have a free weekend, now that I'm poking at Minecraft again

**Comment by scorbett123** [comment] 2022-04-15 13:53
> I might look into doing this once I have a free weekend, now that I'm poking at Minecraft again

I'm glad that you're getting back into mc again. If you are working on this I recommend you look at #2544 which is a (stale) pr for litematics.

**Comment by ZacSharp** [comment] 2022-10-29 22:03
Done in #3672

**Closed by ZacSharp** 2022-10-29 22:03 UTC
Labels: enhancement
