### ISSUE TITLE
swimming

### ISSUE THREAD

**Issue by kittenvr** [cabaletta/baritone#3728] opened 2022-11-13 12:20 UTC
## Describe your suggestion
make the bot swim if you are in the water, it goes down and sprints.

## Settings
/

## Context
this will make the bot go faster through the water

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-11-13 22:15
Duplicate of #1483

**Closed by ZacSharp** 2022-11-13 22:15 UTC
Labels: duplicate, enhancement
