### ISSUE TITLE
Get the missing material by baritone it self when auto-build

### ISSUE THREAD

**Issue by zausa** [cabaletta/baritone#2704] opened 2021-04-29 02:34 UTC
## Describe your suggestion

We can set where we put the material for if we need anything not in bag , it can automatically 'goto' and open the chest to get what we need.

## Settings
We can customize the (x,y,z) for where we  store  the items ,if  missing the items is no on the list , pop out the error message like usual.
Also , the number for one times to avoid the bag full. 

## Context
It can  implement complete auto-build . It would be a little problem if we still need to stare at the screen when we start to auto_build.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2021-05-19 16:47
Duplicate of #1098

**Closed by scorbett123** 2021-05-19 16:47 UTC
Labels: enhancement
