### ISSUE TITLE
Make camera movement when mining smoother and randomize mining pattern

### ISSUE THREAD

**Issue by skybotflyer** [cabaletta/baritone#1298] opened 2020-02-15 05:52 UTC
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

Is there a way to make the camera movement smoother and not a flick?

Also, when using **#sel ca**, is there a way to randomize the mining pattern instead of having it mine left to right repeatedly? It makes it look very suspicious, especially on prison servers, since no one mines like that. 

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by PublicByte** [comment] 2020-02-28 16:15
Please split up the issue into "Make camera movement when mining smoother" and "Randomize mining pattern."

**Comment by PublicByte** [comment] 2020-02-28 16:16
Also, this isn't a question.

**Comment by S-B99** [comment] 2020-02-28 16:23
Camera movement is a duplicate of #1218 and see #1292 for the other.

**Closed by S-B99** 2020-02-28 16:23 UTC
Labels: question
