### ISSUE TITLE
add ability to till dirt with a hoe (and strip wood with axe too ig)

### ISSUE THREAD

**Issue by CaszGamerMD** [cabaletta/baritone#4191] opened 2023-11-13 07:07 UTC
## Describe your suggestion
when it comes to turning dirt or grass into farmland it should till the dirt with a hoe, not break it and try to place block
i guess same thing could apply to wood > stripped

## Settings
if a setting is needed rightclickblockchange - could also right click logs with an axe to strip if part of a build

## Context
ability to make farm or fix farm land

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue. (but it was tempting)

**Comment by ZacSharp** [comment] 2023-11-13 20:41
Duplicate of #827

**Closed as completed by ZacSharp** 2023-11-13 20:41 UTC
Labels: duplicate, enhancement

**Comment by ZacSharp** [comment] 2023-11-13 20:45
The problem of `BuilderProcess` not being able to use right click actions for blocks like doors, levers, snow, etc. is known, but there is no way to detect what happens to a block if you click on it (unless you solve the halting problem) and hardcoding some actions is not a good solution.
