### ISSUE TITLE
Mine function wont work no marter what block or variation of block type i use

### ISSUE THREAD

**Issue by Aphrodite6969** [cabaletta/baritone#3447] opened 2022-05-12 20:33 UTC
## Some information
Operating system: Windows 64
Java version: no clue (prolly most recent)
Minecraft version: 1.18.2
Baritone version: 1.18.2
Other mods (if used): fabric with soduim

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

[latest.log](https://github.com/cabaletta/baritone/files/8682400/latest.log)

## How to reproduce
type #mine (any block) and it doesnt work
## Modified settings
To get the modified settings run `#modified` in game
legitmine boolean
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by wagyourtail** [comment] 2022-05-12 21:23
duplicate of pinned issue. update baritone to 1.8.3

**Closed by wagyourtail** 2022-05-12 21:23 UTC
Labels: bug
