### ISSUE TITLE
Can't build schematics

### ISSUE THREAD

**Issue by PleaseDoHelp** [cabaletta/baritone#1494] opened 2020-04-01 22:37 UTC
## Some information
Operating system: Windows 10
Java version: Java 8 Update 241
Minecraft version: 1.14.4
Baritone version: 1.14.4 (Impact 4.8.3)
Forge mods (if used): None

## Exception, error or logs

[23:27:17] [main/INFO]: [CHAT] [Baritone] > build groudon.schematic
[23:27:17] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[23:27:17] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[23:27:17] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3794/766686984.accept(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[23:27:17] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zef000(SourceFile)
[23:27:17] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[23:27:17] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[23:27:17] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[23:27:17] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.sendMessage(GuiChatOF.java:41)
[23:27:17] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[23:27:17] [main/INFO]: [STDERR]: 	at cya.lambda$onKeyEvent$4(KeyboardListener.java:440)
[23:27:17] [main/INFO]: [STDERR]: 	at cya$$Lambda$3770/1293032118.run(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[23:27:17] [main/INFO]: [STDERR]: 	at cya.a(KeyboardListener.java:407)
[23:27:17] [main/INFO]: [STDERR]: 	at cya$$Lambda$1540/788045379.invoke(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[23:27:17] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[23:27:17] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[23:27:17] [main/INFO]: [STDERR]: 	at cuo.k(MainWindow.java:503)
[23:27:17] [main/INFO]: [STDERR]: 	at cuo.c(MainWindow.java:342)
[23:27:17] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[23:27:17] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[23:27:17] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[23:27:17] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[23:27:17] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:27:17] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:27:17] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:27:17] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:27:17] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
[23:27:17] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[23:27:17] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[23:27:17] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[23:27:17] [main/INFO]: [STDERR]: 	... 33 more
[23:27:19] [Server thread/INFO]: Saving and pausing game...
[23:27:19] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_nether
[23:27:19] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:overworld
[23:27:19] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_end
[23:27:27] [pool-5-thread-2/INFO]: [STDOUT]: Saving region -1,0 to disk C:\Users\x\AppData\Roaming\.minecraft\saves\New World\baritone\DIM0\cache
[23:27:27] [ForkJoinPool.commonPool-worker-9/INFO]: [STDOUT]: Saving region 0,0 to disk C:\Users\x\AppData\Roaming\.minecraft\saves\New World\baritone\DIM0\cache
[23:27:28] [ForkJoinPool.commonPool-worker-9/INFO]: [STDOUT]: Saved region successfully
[23:27:28] [pool-5-thread-2/INFO]: [STDOUT]: Saved region successfully
[23:27:28] [pool-5-thread-2/INFO]: [STDOUT]: World save took 59ms
[23:27:37] [main/INFO]: [CHAT] [Baritone] > build groudon.schematic
[23:27:37] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred.The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[23:27:37] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[23:27:37] [main/INFO]: [STDERR]: 	at baritone.cb.execute(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at baritone.w.a(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at baritone.w.onSendChatMessage(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at baritone.cd.a(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at baritone.cd$$Lambda$3794/766686984.accept(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[23:27:37] [main/INFO]: [STDERR]: 	at baritone.cd.onSendChatMessage(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at dmp.handler$sendChatMessage$zef000(SourceFile)
[23:27:37] [main/INFO]: [STDERR]: 	at dmp.f(SourceFile)
[23:27:37] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:318)
[23:27:37] [main/INFO]: [STDERR]: 	at dcl.sendMessage(SourceFile:311)
[23:27:37] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.sendMessage(GuiChatOF.java:41)
[23:27:37] [main/INFO]: [STDERR]: 	at dbl.keyPressed(SourceFile:129)
[23:27:37] [main/INFO]: [STDERR]: 	at cya.lambda$onKeyEvent$4(KeyboardListener.java:440)
[23:27:37] [main/INFO]: [STDERR]: 	at cya$$Lambda$3770/1293032118.run(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at dcl.wrapScreenError(SourceFile:441)
[23:27:37] [main/INFO]: [STDERR]: 	at cya.a(KeyboardListener.java:407)
[23:27:37] [main/INFO]: [STDERR]: 	at cya$$Lambda$1540/788045379.invoke(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[23:27:37] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[23:27:37] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[23:27:37] [main/INFO]: [STDERR]: 	at cuo.k(MainWindow.java:503)
[23:27:37] [main/INFO]: [STDERR]: 	at cuo.c(MainWindow.java:342)
[23:27:37] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:1023)
[23:27:37] [main/INFO]: [STDERR]: 	at cyc.e(SourceFile:976)
[23:27:37] [main/INFO]: [STDERR]: 	at cyc.b(SourceFile:410)
[23:27:37] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:155)
[23:27:37] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:27:37] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:27:37] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:27:37] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:27:37] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
[23:27:37] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[23:27:37] [main/INFO]: [STDERR]: Caused by: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
[23:27:37] [main/INFO]: [STDERR]: 	at baritone.gp.<init>(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at baritone.dy.build(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	at baritone.al.execute(Unknown Source)
[23:27:37] [main/INFO]: [STDERR]: 	... 33 more
[23:27:38] [Server thread/INFO]: Saving and pausing game...
[23:27:38] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_nether
[23:27:38] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:overworld
[23:27:38] [Server thread/INFO]: Saving chunks for level 'New World'/minecraft:the_end

**Comment by raptortech-js** [comment] 2020-11-23 16:37
This is a duplicate of https://github.com/cabaletta/baritone/issues/506

**Closed** 2021-02-10 14:21 UTC
Labels: bug
