### ISSUE TITLE
1.14.4 Standalone Baritone is not working properly with #find and #goto <block>

### ISSUE THREAD

**Issue by jhmaster2000** [cabaletta/baritone#698] opened 2019-07-30 22:40 UTC
Im in a superflat world and I tried to run #goto chest to find a village, it said "No known locations", so I did /locate Village and found one myself, for testing, I did #goto chest again from inside the Village and it still said "No known locations", even standing from like 10 blocks away from the chest (In the same chunk!) with it inside my point of view. In the same conditions #find chest also returns no results. While #mine chest works, so this is a command-specific issue.

**Comment by leijurv** [comment] 2019-07-30 22:48
Version of minecraft?

**Comment by CheatTriggers** [comment] 2019-07-30 22:53
> Version of minecraft and version of baritone?

I stated in the title but ok:
Baritone: 1.14.4
Minecraft 1.14.4 Vannila No Optifine

Should also state its a singleplayer world so it cant be a server anticheat blocking it

**Comment by StijnSimons** [comment] 2019-08-01 17:59
My man baritone has subversions

**Comment by AlexApps99** [comment] 2019-08-18 05:28
@CheatTriggers when did you install that version of baritone? Please try again on latest version and attach screenshots

**Comment by AlexApps99** [comment] 2019-08-18 05:31
Nevermind, close this as it is a duplicate of #523 and was patched in #554.

**Comment by 0-x-2-2** [comment] 2019-08-18 19:52
This is unrelated to that issue he is trying to mine a chest that is a block.

**Comment by SilentStormm** [comment] 2019-09-03 19:51
Got the same issue in 1.13.2 (latest public release)

**Closed** 2022-02-24 06:10 UTC
