### ISSUE TITLE
i have a problem for 1.12.2 with baritone

### ISSUE THREAD

**Issue by TYtiany** [cabaletta/baritone#3655] opened 2022-09-11 10:44 UTC
## What do you need help with?
An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

## Final checklist
- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.
[18:39:01] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] > mine minecraft:stone
[18:39:01] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:stone},meta=null}]
[18:39:01] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.IllegalArgumentException: No enum constant net.minecraft.item.Item.ToolMaterial.COPPER
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cd.execute(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.z.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.z.onSendChatMessage(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zze000(EntityPlayerSP.java)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:424)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:411)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.optifine.gui.GuiChatOF.func_175275_f(GuiChatOF.java:41)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:81)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:39:01] [Client thread/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.IllegalArgumentException: No enum constant net.minecraft.item.Item.ToolMaterial.COPPER
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.Enum.valueOf(Enum.java:238)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.item.Item$ToolMaterial.valueOf(Item.java:1769)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fz.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fz.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fz.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.function.Function.lambda$compose$0(Function.java:68)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fz.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.cl.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fd.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fd.c(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fd.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fd.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fd.a(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.fd.mine(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.api.process.IMineProcess.mine(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at baritone.bj.execute(Unknown Source)
[18:39:01] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 24 more

**Comment by ZacSharp** [comment] 2022-09-11 22:35
Update Baritone. This is a problem with CoFH mods and has been fixed quite a while ago (newest release is too old though).

Also it would have been nice to not have to guess that you are using Baritone v1.2.15 on Forge with OptiFine and at least one CoFH mod installed.

**Comment by ZacSharp** [comment] 2022-09-11 22:35
Duplicate of #3008

**Closed by ZacSharp** 2022-09-11 22:35 UTC
Labels: bug, duplicate

**Comment by TYtiany** [comment] 2022-09-12 01:00
> 更新男中音。这是CoFH mods的一个问题，很久以前就已经解决了(不过最新版本太旧了)。
> i use 1.2.15 had a same problem. 1.2.15 i not new?
> 此外，最好不要猜测你在Forge上使用的是男中音v1.2.15，并且安装了OptiFine和至少一个CoFH mod。
so i need to delete a CoFH mod? but CoFH mod is a mod needed.

**Comment by ZacSharp** [comment] 2022-09-12 14:28
The latest release for Minecraft 1.12.2 is v1.2.15, but it's already one year and five months old and is missing 156 commits, including the fix for this bug.
If you want an up-to-date version select the latest CI run from [this list](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=branch%3Amaster+is%3Asuccess+event%3Apush+actor%3Aleijurv), download the artifacts zip and extract the jar you need.
