### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by moto6333** [cabaletta/baritone#1780] opened 2020-06-11 23:06 UTC
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.
a ETA function so we can see when we will get to the cords we put in
## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.
we could toggle it and have a command to get a new update
## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.
so people can see when there will get to the cords so you can go do something and come back
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment] 2020-06-11 23:07
Duplicate of #1480

**Closed by dominikaaaa** 2020-06-11 23:07 UTC
Labels: enhancement
