### ISSUE TITLE
The command list returns a 404 in USAGE.md.

### ISSUE THREAD

**Issue by Antonio32A** [cabaletta/baritone#1628] opened 2020-04-26 19:19 UTC
## How to reproduce
1. Go to [USAGE.md](https://github.com/cabaletta/baritone/blob/master/USAGE.md).
2. Scroll down to Commands , 
    `For the rest of the commands, you can take a look at the code here.`
3. Click on [here](https://github.com/cabaletta/baritone/blob/master/src/api/java/baritone/api/utils/ExampleBaritoneControl.java).

## Expected result
The link should point to the list of commands.

## Actual result
The link doesn't point to the list of commands since the file has been probably renamed/removed.
It returns a 404 error instead.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment] 2020-04-26 19:20
Duplicate of #1040

**Comment by dominikaaaa** [comment] 2020-04-26 19:20
I should maybe get around to this someday :sweat_smile:

**Comment by dominikaaaa** [comment] 2020-04-26 19:21
For now, use https://baritone.leijurv.com/baritone/api/Settings.html

**Closed by dominikaaaa** 2020-04-26 19:20 UTC
Labels: bug
