### ISSUE TITLE
Unhandled exception occured.

### ISSUE THREAD

**Issue by ghost** [cabaletta/baritone#4183] opened 2023-11-05 16:54 UTC
![2023-11-05_17 52 52](https://github.com/cabaletta/baritone/assets/106018328/9ad547f2-1504-446d-9014-af8113065398)

**Comment by ZacSharp** [comment] 2023-11-05 21:27
No log, no other info on the error. I'll just assume this is yet another duplicate of a known and fixed problem.
If you think that's not the case, please provide the information requested by the template you ignored.

**Closed as completed by ZacSharp** 2023-11-05 21:27 UTC
Labels: bug, duplicate, invalid
