### ISSUE TITLE
Something like block group creation or searching by characters in name

### ISSUE THREAD

**Issue by SuperSuggestionMan** [cabaletta/baritone#3422] opened 2022-04-27 10:13 UTC
Something like 
#group create <block> <name>
Then
#mine <group name>
Or 
#mine nameinclude <characters of search>
Like 
#mine nameinclude log
Or 
Pre made groups such as logs or ores
#mine ores

**Comment by SuperSuggestionMan** [comment] 2022-04-27 10:15
Rip

**Comment by SuperSuggestionMan** [comment] 2022-04-27 10:15
# in thing doesn't work

**Comment by SuperSuggestionMan** [comment] 2022-04-27 10:15
Hashtag

**Comment by ZacSharp** [comment] 2022-04-27 16:48
Duplicate of #1311

**Closed by ZacSharp** 2022-04-27 16:48 UTC
Labels: duplicate, enhancement, invalid
