### ISSUE TITLE
Minning dosent work in a server

### ISSUE THREAD

**Issue by Handol224** [cabaletta/baritone#3772] opened 2022-12-26 11:55 UTC
## Some information
Operating system: windows 10
Java version: 
Minecraft version: 1.19.3
Baritone version: I am using the unoptimised version
Other mods (if used): 

when i log into singleplayer the minning works fine but when i go into my friends server it says this
[13:51:32] [Render thread/INFO]: [System] [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-12-27 01:22
Guessing this is a duplicate of #3756 and you need to update Baritone to a more recent CI run (specifically [this run](https://github.com/cabaletta/baritone/actions/runs/3732468264) or newer).
If that's wrong please provide the log file so we can have a look at the error.

**Closed by ZacSharp** 2022-12-27 01:22 UTC
Labels: bug, duplicate
