### ISSUE TITLE
#mine not working

### ISSUE THREAD

**Issue by Godfather096** [cabaletta/baritone#3758] opened 2022-12-12 15:54 UTC
## Some information
Operating system: Windows 10
Java version: version 8 update 351
Minecraft version: 1.19.3
Baritone version: null version
Other mods (if used): meteor-client-0.5.2-1718 fabric-api-0.69.0+1.19.3

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`
[16:36:21] [Render thread/INFO]: [System] [CHAT] [Baritone] > mine iron_ore deepslate_iron_ore raw_iron_block
[16:36:21] [Render thread/INFO]: Reloading ResourceManager: vanilla
[16:36:21] [Render thread/INFO]: [System] [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[16:36:21] [Render thread/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[16:36:21] [Render thread/INFO]: [STDERR]: 	at baritone.command.manager.CommandManager.execute(Unknown Source)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.a(Unknown Source)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at baritone.command.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.a(Unknown Source)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onSendChatMessage(Unknown Source)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.handler$zzb000$sendChatMessage(class_634.java)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_634.method_45729(class_634.java)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_44056(class_408.java:253)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:371)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:492)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:367)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:455)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:455)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1222)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[16:36:21] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "baritone.api.cache.IWorldData.getCachedWorld()" because the return value of "baritone.api.utils.IPlayerContext.worldData()" is null
[16:36:21] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at baritone.cache.WorldScanner.repack(Unknown Source)
[16:36:21] [Render thread/INFO]: [STDERR]: 	at baritone.command.defaults.MineCommand.execute(Unknown Source)
[16:36:21] [Render thread/INFO]: [STDERR]: 	... 28 more

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
typed #mine iron_ore deepslate_iron_ore raw_iron_block 
(or any block, none work)
## Modified settings
To get the modified settings run `#modified` in game
![Screenshot_10](https://user-images.githubusercontent.com/84199589/207091323-6b697c12-7fa5-4bd4-a4b8-6e11d1515dbb.png)
![Screenshot_11](https://user-images.githubusercontent.com/84199589/207091329-694501c2-d454-4538-9316-c529b6e489c6.png)
![Screenshot_12](https://user-images.githubusercontent.com/84199589/207091332-221df0ed-42be-40a2-ada4-f2be70032816.png)
![Screenshot_13](https://user-images.githubusercontent.com/84199589/207091334-5ef192c1-d0d7-473c-be58-6fd25873ed1d.png)
![Screenshot_14](https://user-images.githubusercontent.com/84199589/207091338-9a6c2f27-647a-4e56-b318-6791b56ede01.png)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-12-12 21:54
Duplicate of #3756

**Closed by ZacSharp** 2022-12-12 21:54 UTC
Labels: bug, duplicate

**Comment by ZacSharp** [comment] 2022-12-12 21:56
Thanks for the unobfuscated log though.

**Comment by wagyourtail** [comment] 2022-12-12 21:59
> Thanks for the unobfuscated log though.

that's just because meteor fork I think...

**Comment by Godfather096** [comment] 2022-12-12 22:41
im sorry it's my first time reporting a bug, so how can i fix this if it's marked as resolved?

**Comment by ZacSharp** [comment] 2022-12-13 19:52
If you mean this
![grafik](https://user-images.githubusercontent.com/68165024/207429919-46694d28-1a76-46e6-9473-e562e1c1d4aa.png)
then that's just GitHub being misleading.
This issue is closed because the bug was already reported in #3756 and you will have to look at that issue to see whether the bug is fixed.

**Comment by ZacSharp** [comment] 2022-12-13 20:02
What you can do right now is using [this version of Baritone](https://github.com/cabaletta/baritone/actions/runs/3679500984#artifacts) (click on "artifacts" to download it) to make another log with the exception, which you then upload as a comment on #3756.
