### ISSUE TITLE
Disable or modify parkour when hunger < 3

### ISSUE THREAD

**Issue by nacgarg** [cabaletta/baritone#169] opened 2018-09-15 03:07 UTC
Right now, if allowParkour is left on `true` and hunger is less than 3 (disallowing sprinting), then the bot gets confused when it misses the jump

**Comment by leijurv** [comment] 2018-09-15 03:48
Can't reproduce https://youtu.be/z0ltiT5Pyt8

**Comment by leijurv** [comment] 2018-09-15 03:48
Likely fixed by https://github.com/cabaletta/baritone/commit/d7a646789e6f5a804db095830d3e64c9547ce1dc#diff-df89cb622e702440deb655162f669fe8R84

**Closed by leijurv** 2018-09-15 03:48 UTC
Labels: can't reproduce
