### ISSUE TITLE
falling to death in nether when 'diagonal hugging'

### ISSUE THREAD

**Issue by fw4hre0xxq** [cabaletta/baritone#1290] opened 2020-02-11 05:35 UTC
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

Sometimes in The Nether, particularly on laggy servers, when doing the thing where baritone moves diagonally around a corner, when the blocks turn purple, I'm not sure what that's called; When doing that sometimes it doesn't make the move right somehow and I fall into lava. I've noticed this seems more likely to happen on laggy servers.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by fw4hre0xxq** [comment] 2020-02-11 06:30
Specifically it looks like it's walking into the blockstowalkinto when moving diagonally, and there isn't a block directly under it. What I'm asking is is there or could there be an option to disable doing blockstowalkinto when there isn't a supporting block, or in general?

**Comment by S-B99** [comment] 2020-02-27 15:09
Duplicate of #806

**Closed by S-B99** 2020-02-27 15:09 UTC
Labels: question
