### ISSUE TITLE
building schematics gives me 0 fps

### ISSUE THREAD

**Issue by SixwFive** [cabaletta/baritone#912] opened 2019-09-05 23:06 UTC
## Some information
Operating system: pc
Java version: Newest 
Minecraft version: 1.12.2
Baritone version: 4.7.3
Forge mods (if used): none

ok so my minecraft is being gay. So when i try to build somthing it works but gives me 0 fps

and i have a fine pc
 gtx 1070
 i7 87000k

So any suggestions

**Comment by BlueBlazeTech** [comment] 2019-09-18 15:03
I know this is a dumb question. but could the problem possibly be a driver issue?

**Comment by jonnyawsom3** [comment] 2019-09-27 12:18
_saying operating system: pc is just low effort_ and 4.7.3 is the latest version of impact, not baritone

**Comment by CDAGaming** [comment] 2020-02-26 15:28
GTX 1060 with i7-8750H, no signs of this issue occurring, though the game might slow down if you give it a giant schematic to work with, but unknown if thats the case here.

**Comment by S-B99** [comment] 2020-02-26 15:29
This is definitely a driver issue. What driver version are you running, and what operating system?

**Comment by S-B99** [comment] 2020-02-26 15:32
I'll close this until it gets a response, if the issue is still happening, as this was opened like 6 months ago.

**Closed by S-B99** 2020-02-26 15:32 UTC
Labels: bug, needs more info
