### ISSUE TITLE
how to make baritone rotate looks smooth and legit

### ISSUE THREAD

**Issue by Nokity4444** [cabaletta/baritone#4174] opened 2023-10-30 14:30 UTC
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2023-10-30 14:37
Duplicate of #2034

**Closed as completed by scorbett123** 2023-10-30 14:37 UTC
Labels: duplicate, question
