### ISSUE TITLE
I cant click in chat

### ISSUE THREAD

**Issue by NebulaOCE** [cabaletta/baritone#3587] opened 2022-07-31 04:45 UTC
i am trying to goto my most recent death, i cant figure out how to select it from the other, nor can i click on either one.
im just wondering if im being an idiot or not
im on 1.19.1 forge

**Comment by Julcraftlp** [comment] 2022-07-31 08:36
how do you even use that in forge 1.19? the version is not even supportet.

**Comment by Azuraluv** [comment] 2022-07-31 16:49
I cant click things in chat either. Im on 1.19.1. Using the artifacts from actions

**Comment by wagyourtail** [comment] 2022-07-31 16:57
other mods?

**Comment by JeffersonDawg** [comment] 2022-08-03 21:41
Same here, only mod I use and can't click in chat. 1.19.1

**Comment by wagyourtail** [comment] 2022-08-04 01:43
ok. yeah, just tested. is valid 1 moment...

**Comment by AlexGaming32** [comment] 2022-08-12 08:17
same here. 1.19,2 fabric

**Comment by LordVertice** [comment] 2022-09-05 22:25
Is there any way to access waypoints other than their name or clicking? By DB practice we should have a unique ID, it makes sense for it to be the same here. Maybe make it go like "death-1", "death-2" etc.

By fixing the click mechanic we're just putting a bandaid on the problem. There is a command to select waypoints by name, and that command should always work no matter what. Clicking is a different interface that should _also_ work, but it shouldn't be a fix for broken commands.

**Comment by ZacSharp** [comment] 2022-09-05 23:00
Chat buttons are just a convenient way to run commands so if the command was broken like you implied there would be no way for the chat gui to work. The reason why the clickable chat text can distinguish between equally named waypoints while you cannot is that it uses undocumented internal forms of the waypoints command to specify waypoints by timestamp (which is the unique id you proposed, you can see it in the output of `#waypoints list`)

**Comment by LordVertice** [comment] 2022-09-05 23:25
Good to know. I'll try writing out the waypoint with timestamp tomorrow, and see if it'll correctly set the goal. I still think a scheme like "death-n" is better than relying on timestamps, especially because this issue about clicking is still not resolved.

Btw on a note that's more related to this issue, I can confirm that none of the chat clicks I tried work at all, including but probably not limited to #set page selection and clicking for setting details, and of course waypoints, like reported by OP. Also autocomplete is pretty broken too, idk if that's tracked yet.

**Comment by ZacSharp** [comment] 2022-09-06 17:55
> Good to know. I'll try writing out the waypoint with timestamp tomorrow, and see if it'll correctly set the goal.

I don't think you'll be happy using the timestamps yourself (it's not as easy as typing some chat output back in because the timestamp is in seconds since some fixed date and `wp list` shows them in a human readable format).

> I still think a scheme like "death-n" is better than relying on timestamps, 

That's essentially preventing duplicate names by forced renaming, you can do that yourself as well (`#sethome` and bedwaypoints would still need some change though).

> especially because this issue about clicking is still not resolved.

 Have a look at #3592. Until it's merged and released (can take *quite* some time for the release to happen) I suggest you use the [CI build](https://github.com/cabaletta/baritone/actions/runs/2793730000).

> Btw on a note that's more related to this issue, I can confirm that none of the chat clicks I tried work at all, including but probably not limited to #set page selection and clicking for setting details, and of course waypoints, like reported by OP.

Known and fixed in #3592. This bug does indeed affect all chat buttons.

> Also autocomplete is pretty broken too, idk if that's tracked yet.

I don't think there is an issue for it, but it's been known for a looong time now. Probably since it exists.

**Comment by LordVertice** [comment] 2022-09-07 17:11
Ok so the CI build isn't for 1.19.2. Are there any breaking changes or do I just need to change the version number?

**Comment by wagyourtail** [comment] 2022-09-07 17:33
well, if you look at the 1.19.2 pr changes (#3597), yeah it's just version number changes in a few files...

**Comment by ZacSharp** [comment] 2022-10-23 00:28
#3592 is now merged.

**Closed by ZacSharp** 2022-10-23 00:28 UTC
Labels: bug
