### ISSUE TITLE
Add the ability to add tagged blocks to acceptableThrowawayItems

### ISSUE THREAD

**Issue by randomperson189** [cabaletta/baritone#1311] opened 2020-02-20 11:21 UTC
## Describe your suggestion
When I'm getting the pathfinder to place blocks for me, I want them to place a variety of the same block e.g. '#minecraft:wool' the # is a tag for the block which means it affects any wool colour so that means the pathfinder will place any wool colour without having to specify each one in the settings.

## Settings
for settings here's an example: '#set acceptableThrowawayItems #minecraft:wool, #minecraft_wood'

that means it will place any wool colour and any wood type

## Context
This will improve baritone alot since I won't have to specify each block type for acceptableThrowawayItems

**Comment by Ashesh3** [comment] 2021-02-23 13:36
+1 Can we have this?
Also can you share your `acceptableThrowawayItems` value?

**Comment by scorbett123** [comment] 2021-02-23 13:42
I feel like it would be better to have "groups" of blocks globally, so that it doesn't just have to be restricted to acceptableThrowawayItems.

**Comment by ZacSharp** [comment] 2022-08-27 02:53
Duplicate of #1089

**Closed by ZacSharp** 2022-08-27 02:53 UTC
Labels: duplicate, enhancement
