### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by LonerStars** [cabaletta/baritone#689] opened 2019-07-29 19:34 UTC
## Some information
Operating system:Mac
Java version: the current one
Minecraft version:1.14.4
Baritone version:1.14.4
Forge mods (if used): 

## Exception, error or logs
not a bug like that. more of a pathing issue

## How to reproduce
long distance, it sometimes rams and gets stuck around ender rods

## Final checklist
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by S-B99** [comment] 2020-03-13 12:46
Duplicate of #41

**Closed by S-B99** 2020-03-13 12:46 UTC
Labels: bug
