### ISSUE TITLE
Water and Lava replacement 

### ISSUE THREAD

**Issue by MunchyG** [cabaletta/baritone#2933] opened 2021-08-12 10:31 UTC
this is kinda both a bug and an enhancement.

you can't define water/lava levels for it to replace. 
eg.  #sel replace water[level=0] 'block'
which defines only water source blocks to be targeted
but at the moment it just causes an error.
so the enhancement would basically be to handle some nbt data for blocks. so only mine things in certain directions etc.

**Comment by ZacSharp** [comment] 2021-08-29 21:14
Baritone reporting errors when the user tries to use nonexistent features is not a bug, so this issue is only an enhancement.
Also specifying block properties for mining/building/whatever is already suggested in #1760 and even if #1760 is a bit cluttered this issue is a dublicate.

**Comment by ZacSharp** [comment] 2021-08-29 21:15
Duplicate of ##1760

**Closed by ZacSharp** 2021-08-29 21:15 UTC
Labels: duplicate, enhancement
