### ISSUE TITLE
Baritone not stopping command. Stop and Cancel not working. I am random going to somewhere. I tried to use stop, cancel and pause but It didn't work.

### ISSUE THREAD

**Issue by AnonymosProggramer** [cabaletta/baritone#3710] opened 2022-11-02 16:48 UTC
## Some information
Operating system:Windows 10
Java version:8
Minecraft version:1.12.2
Baritone version: 
Other mods (if used): Lamda, Rusherhack

## Exception, error, or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in-game

## Final checklist
- [x] I know how to properly use checkboxes 
- [x] I have included the version of Minecraft I'm running, baritone's version, and forge mods (if used).
- [x] I have included logs, exceptions, and / or steps to reproduce the issue.
- [x] I have not used any OwOs or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-11-04 22:20
Duplicate of #3713

**Closed** 2022-11-04 22:19 UTC
Labels: bug
