### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Nishatgamer** [cabaletta/baritone#4581] opened 2024-12-10 17:03 UTC
P## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.
When I start building with the help of baritone it's stucking

**Comment by ZacSharp** [comment] 2024-12-14 15:42
Duplicate of #4586

**Closed as completed by ZacSharp** 2024-12-14 15:42 UTC
Labels: duplicate, question
