### ISSUE TITLE
Adding multiple goals and pathing them in order

### ISSUE THREAD

**Issue by AirAustin** [cabaletta/baritone#3175] opened 2022-01-04 00:11 UTC
So when using the .goto command to travel tens of thousands of blocks in the nether I noticed that baritone instead of making its way to the nearest tunnel (to save time and my pickaxe) it often started digging its own (like 10 blocks apart). So that's one thing to fix, but this situation made me divide my path into 3 different paths. One from my portal to the highway (on 9b9t), the second along the highway, and the last one to another portal. So I made 3 different waypoints and then pathed baritone to them. The problem was that I had to check-up on baritone to see if it's done with the first path and manually input the second command (to the second waypoint; same with the third one). In google maps, you can add stops along your main route. And since baritones AI is sometimes not efficient enough, this would help a lot. Just like you can make it mine different blocks at once (.mine diamond_ore coal_ore), I wish I could make it go through multiple waypoints in the order I typed them e.g. (.waypoint goto 1 2 3) while (.waypoint save user 1/2/3). So for the present state of the AI, it would significantly improve baritones' efficiency. I could make it go through already made tunnels it recognized and not waste my resources and time just so it can mine new tunnels. Another thing I rather rarely happen to come upon is a point where baritone completely stops. When I input the .goto command again it searches for various paths for a while and then stops. As if it couldn't find a way to go.

**Comment by ZacSharp** [comment] 2022-01-04 22:39
Duplicate of #186

**Comment by ZacSharp** [comment] 2022-01-04 22:39
Duplicate of #176

**Closed by ZacSharp** 2022-01-04 22:39 UTC
Labels: duplicate, enhancement
