### ISSUE TITLE
Help Baritone class file for rr not found

### ISSUE THREAD

**Issue by Jamishs** [cabaletta/baritone#1755] opened 2020-06-04 08:20 UTC
## What do you need help with?
With as much detail as possible, describe your question and what you may need help with.

`error: cannot access rr
        BaritoneAPI.getProvider().getPrimaryBaritone().getCommandManager().execute("sel 1 -131,73,-25");
  class file for rr not found`

Trying to use baritone with a mod this happens when building it 
cannot find rr? when using execute

- [x] I know how to properly use check boxes 
- [x ] I have not used any OwO's or UwU's in this issue.

**Comment by Jamishs** [comment] 2020-06-04 08:23
![image](https://user-images.githubusercontent.com/60609917/83733129-b373f580-a67f-11ea-8091-d430da9137ac.png)

**Comment by Jamishs** [comment] 2020-06-04 09:55
![image](https://user-images.githubusercontent.com/60609917/83742908-91cd3b00-a68c-11ea-80d9-1433d0d6d9d3.png)
there are two executes?

**Comment by StijnSimons** [comment] 2020-06-04 10:46
1. You shouldn't be executing tasks like that.
2. Duplicate of #853 #1526 and some others.

**Comment by Jamishs** [comment] 2020-06-04 11:03
1. is there a better way?
2. rr class file?
3. what core?

**Comment by dominikaaaa** [comment] 2020-06-04 14:20
1. you should be calling an actual goal process instead
2. that's the obfuscated class name
3. Baritone 

As for sending specific commands, this code is from impact (you can delete the chat control part, I'm trying to figure out why it's there ngl)

https://github.com/kami-blue/client/blob/master/src/main/java/me/zeroeightsix/kami/util/MessageSendHelper.java#L68

**Comment by StijnSimons** [comment] 2020-06-04 14:26
KAMICRINGE 📸

**Comment by dominikaaaa** [comment] 2020-06-04 18:24
ok stijn

**Comment by TheK0tYaRa** [comment] 2020-06-11 14:45
Have you tried not using ` , ` when inputting coordinates?

**Comment by dominikaaaa** [comment] 2020-06-11 14:46
Thanks for pointing that out. I completely skipped over that. 

@Jamishs reopen this if you have any other questions.

**Closed by dominikaaaa** 2020-06-11 14:46 UTC
Labels: question
