### ISSUE TITLE
Make that #allowinventory gets items in creative inventory 

### ISSUE THREAD

**Issue by jonfinnelizaga** [cabaletta/baritone#1786] opened 2020-06-13 15:04 UTC
## Describe your suggestion it would be really helpful that you don't need to get items from creative 
With as much detail as possible, describe what your suggestion would do for Baritone.

## Settings#allowinventory
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context it would improve its building schematics
Describe how your suggestion would improve Baritone, or the reason behind it being added.

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment] 2020-06-13 16:08
Duplicate of #1675. Stop making duplicate issues

**Closed** 2020-06-13 16:08 UTC
Labels: enhancement
