### ISSUE TITLE
ETA Command

### ISSUE THREAD

**Issue by MoonBarc** [cabaletta/baritone#1480] opened 2020-03-29 21:22 UTC
## Describe your suggestion
When using Baritone, I quite often find myself like a obnoxious 7 year old trying to ask baritone _"ARE WE THERE YET???"_
To fix this, a simple `#eta` command would be very useful. It would show the remaining time in seconds, or if you explicitly set it (see below), it would show in ticks.

## Settings
There is not much to add to this. Maybe an option like `showEtaInTicks` would be useful, but otherwise there wouldn't be much.

## Context
My suggestion would improve baritone because (at least I think) there is an API method for finding the ETA, but it currently does not have a command.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by UltraBlackLinux** [comment] 2020-04-10 07:49
Impact client has this function, but it has the problem, that the its is only until the next path way decision will be made. This cant be useful.

**Comment by cazeip** [comment] 2020-05-29 09:17
@MoonBarc Understand that if you ask baritone to pathfind to a place that is not loaded yet, it will generate the path gradually. There is no way for baritone to know how much time is left because it does not know the terrain (e.g. It is faster to travel across a desert than to travel around a big mountain).

**Comment by cazeip** [comment] 2020-05-29 09:23
@MoonBarc Be aware that **if you ask baritone** to find a way to a place that is not loaded yet, **it will generate the way gradually**. Baritone has **no way of knowing** how much time is left because **it does not know the terrain** (for example, it is faster to cross a desert than to go around a large mountain).

What you can do is simply **look at the coordinates** and try to **figure out the distance**, and thus, an approximate time.

**Comment by dominikaaaa** [comment] 2020-05-29 14:42
I mean, Baritone caches the chunks, and ETA is always an estimate

**Comment by MoonBarc** [comment] 2020-05-29 15:02
Dunno if this would be somewhat impossible, but you could get the seed of the world, and generate an estimate off of that. This would exclude player-made structures, but for a freshly made world it would work relatively well. If cached chunks did exist though, it could work off of that as that is much more accurate.

**Comment by dominikaaaa** [comment] 2020-05-29 15:08
That's out of scope for baritone.

**Comment by ZacSharp** [comment] 2020-08-01 20:42
Is this a duplicate of #16?

**Comment by dominikaaaa** [comment] 2020-08-01 20:43
Not really, this issue is for a command to return the ETA

**Comment by ZacSharp** [comment] 2020-08-25 21:05
Would the eta suggested in #16 be sufficient or does this specifically ask for a complete (or as complete as possible) path through the cache?

**Comment by dominikaaaa** [comment] 2020-08-26 01:42
No, #16 is to improve the current ETA calculation, this issue is to add a command to let you access the ETA without a utility mod like Impact

**Comment by ZacSharp** [comment] 2020-08-26 15:21
I thought this is to add a command to access an improved ETA

**Comment by dominikaaaa** [comment] 2020-08-26 15:21
To access the ETA*

**Comment by ZacSharp** [comment] 2020-08-26 15:22
The current one? That's easy. Doing it.

**Comment by dominikaaaa** [comment] 2020-08-26 15:23
Yea, but there's no command for users to access the current ETA system

**Comment by ZacSharp** [comment] 2020-08-26 16:04
That's what I'm doing?

**Comment by dominikaaaa** [comment] 2020-08-26 16:06
There's no command to access the ETA?

**Comment by ZacSharp** [comment] 2020-08-26 16:09
And I am adding it (for our current segment ETA)

**Comment by ZacSharp** [comment] 2020-08-26 16:15
But should I also do #16 with the ETA suggested by @leijurv?
The command would show both

**Comment by dominikaaaa** [comment] 2020-08-26 16:21
I guess so

**Closed** 2021-02-20 04:13 UTC
Labels: enhancement
