### ISSUE TITLE
follow player causing unhandled exceptions

### ISSUE THREAD

**Issue by sportshead** [cabaletta/baritone#2135] opened 2020-10-31 11:18 UTC
## Some information
Operating system: Windows 10
Java version: `java version "1.8.0_261"`
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): Impact, optifine

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

```
[19:13:25] [main/INFO]: [CHAT] [Baritone] > follow player shadowtrooper_
[19:13:25] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[19:13:25] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[19:13:25] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[19:13:25] [main/INFO]: [STDERR]: 	at baritone.cd.execute(Unknown Source)
[19:13:25] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[19:13:25] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[19:13:25] [main/INFO]: [STDERR]: 	at baritone.cf.a(Unknown Source)
[19:13:25] [main/INFO]: [STDERR]: 	at baritone.cf$$Lambda$809/1777436796.accept(Unknown Source)
[19:13:25] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[19:13:25] [main/INFO]: [STDERR]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[19:13:25] [main/INFO]: [STDERR]: 	at bud.handler$sendChatMessage$zej000(SourceFile)
[19:13:25] [main/INFO]: [STDERR]: 	at bud.g(SourceFile)
[19:13:25] [main/INFO]: [STDERR]: 	at blk.b(SourceFile:327)
[19:13:25] [main/INFO]: [STDERR]: 	at blk.f(SourceFile:320)
[19:13:25] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.f(GuiChatOF.java:41)
[19:13:25] [main/INFO]: [STDERR]: 	at bkn.a(SourceFile:81)
[19:13:25] [main/INFO]: [STDERR]: 	at blk.l(SourceFile:416)
[19:13:25] [main/INFO]: [STDERR]: 	at blk.q(SourceFile:383)
[19:13:25] [main/INFO]: [STDERR]: 	at bib.t(SourceFile:1625)
[19:13:25] [main/INFO]: [STDERR]: 	at bib.az(SourceFile:1000)
[19:13:25] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:419)
[19:13:25] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[19:13:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:13:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:13:25] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:13:25] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:13:25] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
[19:13:25] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[19:13:25] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[19:13:25] [main/INFO]: [STDERR]: 	at baritone.bb$$Lambda$867/1403837550.apply(Unknown Source)
[19:13:25] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[19:13:25] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[19:13:25] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(Abstra[19:13:26] [main/INFO]: [CHAT] [Impact] allowPlace is on, and there are blocks in your inventory, but none on your hotbar!
[19:13:57] [main/INFO]: [CHAT] [Baritone] > stop
[19:13:57] [main/INFO]: [CHAT] [Baritone] ok canceled
[19:14:01] [main/INFO]: Loaded 123 advancements
 [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[19:13:25] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:13:25] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[19:13:25] [main/INFO]: [STDERR]: 	at baritone.bb.execute(Unknown Source)
[19:13:25] [main/INFO]: [STDERR]: 	... 25 more
[19:13:26] [main/INFO]: [CHAT] [Baritone] > follow player shadowtrooper_
[19:13:26] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[19:13:26] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[19:13:26] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[19:13:26] [main/INFO]: [STDERR]: 	at baritone.cd.execute(Unknown Source)
[19:13:26] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[19:13:26] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[19:13:26] [main/INFO]: [STDERR]: 	at baritone.cf.a(Unknown Source)
[19:13:26] [main/INFO]: [STDERR]: 	at baritone.cf$$Lambda$809/1777436796.accept(Unknown Source)
[19:13:26] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[19:13:26] [main/INFO]: [STDERR]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[19:13:26] [main/INFO]: [STDERR]: 	at bud.handler$sendChatMessage$zej000(SourceFile)
[19:13:26] [main/INFO]: [STDERR]: 	at bud.g(SourceFile)
[19:13:26] [main/INFO]: [STDERR]: 	at blk.b(SourceFile:327)
[19:13:26] [main/INFO]: [STDERR]: 	at blk.f(SourceFile:320)
[19:13:26] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.f(GuiChatOF.java:41)
[19:13:26] [main/INFO]: [STDERR]: 	at bkn.a(SourceFile:81)
[19:13:26] [main/INFO]: [STDERR]: 	at blk.l(SourceFile:416)
[19:13:26] [main/INFO]: [STDERR]: 	at blk.q(SourceFile:383)
[19:13:26] [main/INFO]: [STDERR]: 	at bib.t(SourceFile:1625)
[19:13:26] [main/INFO]: [STDERR]: 	at bib.az(SourceFile:1000)
[19:13:26] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:419)
[19:13:26] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[19:13:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:13:26] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:13:26] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:13:26] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:13:26] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
[19:13:26] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[19:13:26] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[19:13:26] [main/INFO]: [STDERR]: 	at baritone.bb$$Lambda$867/1403837550.apply(Unknown Source)
[19:13:26] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[19:13:26] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[19:13:26] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[19:13:26] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[19:13:26] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[19:13:26] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[19:13:26] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:13:26] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[19:13:26] [main/INFO]: [STDERR]: 	at baritone.bb.execute(Unknown Source)
[19:13:26] [main/INFO]: [STDERR]: 	... 25 more
[19:13:28] [main/INFO]: [CHAT] [Baritone] > stop
[19:13:28] [main/INFO]: [CHAT] [Baritone] ok canceled
[19:13:29] [main/INFO]: [CHAT] [Baritone] > follow player shadowtrooper_
[19:13:29] [main/INFO]: [CHAT] [Baritone] Following these types of entities:
[19:13:29] [main/INFO]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues
[19:13:29] [main/INFO]: [STDERR]: baritone.api.command.exception.CommandUnhandledException: java.lang.NullPointerException
[19:13:29] [main/INFO]: [STDERR]: 	at baritone.cd.execute(Unknown Source)
[19:13:29] [main/INFO]: [STDERR]: 	at baritone.x.a(Unknown Source)
[19:13:29] [main/INFO]: [STDERR]: 	at baritone.x.onSendChatMessage(Unknown Source)
[19:13:29] [main/INFO]: [STDERR]: 	at baritone.cf.a(Unknown Source)
[19:13:29] [main/INFO]: [STDERR]: 	at baritone.cf$$Lambda$809/1777436796.accept(Unknown Source)
[19:13:29] [main/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
[19:13:29] [main/INFO]: [STDERR]: 	at baritone.cf.onSendChatMessage(Unknown Source)
[19:13:29] [main/INFO]: [STDERR]: 	at bud.handler$sendChatMessage$zej000(SourceFile)
[19:13:29] [main/INFO]: [STDERR]: 	at bud.g(SourceFile)
[19:13:29] [main/INFO]: [STDERR]: 	at blk.b(SourceFile:327)
[19:13:29] [main/INFO]: [STDERR]: 	at blk.f(SourceFile:320)
[19:13:29] [main/INFO]: [STDERR]: 	at net.optifine.gui.GuiChatOF.f(GuiChatOF.java:41)
[19:13:29] [main/INFO]: [STDERR]: 	at bkn.a(SourceFile:81)
[19:13:29] [main/INFO]: [STDERR]: 	at blk.l(SourceFile:416)
[19:13:29] [main/INFO]: [STDERR]: 	at blk.q(SourceFile:383)
[19:13:29] [main/INFO]: [STDERR]: 	at bib.t(SourceFile:1625)
[19:13:29] [main/INFO]: [STDERR]: 	at bib.az(SourceFile:1000)
[19:13:29] [main/INFO]: [STDERR]: 	at bib.a(SourceFile:419)
[19:13:29] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[19:13:29] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:13:29] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:13:29] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:13:29] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:13:29] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
[19:13:29] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[19:13:29] [main/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[19:13:29] [main/INFO]: [STDERR]: 	at baritone.bb$$Lambda$867/1403837550.apply(Unknown Source)
[19:13:29] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[19:13:29] [main/INFO]: [STDERR]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[19:13:29] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[19:13:29] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[19:13:29] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[19:13:29] [main/INFO]: [STDERR]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[19:13:29] [main/INFO]: [STDERR]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[19:13:29] [main/INFO]: [STDERR]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[19:13:29] [main/INFO]: [STDERR]: 	at baritone.bb.execute(Unknown Source)
[19:13:29] [main/INFO]: [STDERR]: 	... 25 more
```

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
run `#follow player <playername>`

## Modified settings
To get the modified settings run `#modified` in game
chatControl

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2020-10-31 11:32
duplicate of #1608

**Closed** 2020-10-31 12:32 UTC
Labels: bug
