### ISSUE TITLE
Command Baritone to do multiple commands in order

### ISSUE THREAD

**Issue by Grovre** [cabaletta/baritone#641] opened 2019-07-25 00:04 UTC
## Describe your suggestion
Say you want to Baritone to go mine x amount of ore. When it's done, instead of just standing there, what if you could tell it to go home after it's done mining when you told it to go mine?

## Context
Being able to give baritone waypoint commands after mining a certain amount of ore would let you mine afk for as long as you want as long as you don't die. When used with the setting to disconnect after reaching a waypoint, telling Baritone to go mine, go home and disconnect would be a huge advantage for Baritone users and most would see this as a big improvement. It doesn't even have to be used with the disconnect setting, just simply automatically going home after a long (and easy) mining session would have many users see this as a much needed feature.

## Final checklist
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by GamingInfinite** [comment] 2019-07-26 00:26
I think that this is a great idea for it, especially for a grindy mode like skyblock or factions.

**Comment by SylveonBottle** [comment] 2019-08-02 05:02
Duplicate of #176?

**Closed** 2020-02-26 03:44 UTC
Labels: enhancement
