### ISSUE TITLE
An unhandled exception occurred. The error is in your game's log.

### ISSUE THREAD

**Issue by tommy5837947** [cabaletta/baritone#4179] opened 2023-11-05 02:20 UTC
There is a question and the logs is under the stove
[2023-11-05-3.log.gz](https://github.com/cabaletta/baritone/files/13258134/2023-11-05-3.log.gz)

**Comment by ZacSharp** [comment] 2023-11-05 14:10
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-11-05 14:10 UTC
Labels: bug, duplicate
