### ISSUE TITLE
An unhandled exception occurred. The error is in your game's log...

### ISSUE THREAD

**Issue by Tendas240** [cabaletta/baritone#4199] opened 2023-11-19 22:11 UTC
## Some information
Operating system: Windows 10
Java version: Java 8 Update 281
Minecraft version: 1.20.2
Baritone version: baritone-1.20.2-20231022.115809-1
Provided by the meteor community on their website:
![image](https://github.com/cabaletta/baritone/assets/71498430/0d3b2db4-d3c5-4abc-8414-2d751fd2d18b)

Other mods (if used): See bottom

## Exception, error or logs
[latest.log](https://github.com/cabaletta/baritone/files/13404728/latest.log)

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
perform the command on deepslate level:
mine diamond_ore deepslate_diamond_ore

## Modified settings
![image](https://github.com/cabaletta/baritone/assets/71498430/541f1212-dd10-4f77-9858-a0c40118f9e9)
![image](https://github.com/cabaletta/baritone/assets/71498430/4e1555b3-f723-454b-9f79-53a0e27ba57e)
![image](https://github.com/cabaletta/baritone/assets/71498430/98cd8bb0-ef24-42fb-94ef-0996b13ff9a1)
![image](https://github.com/cabaletta/baritone/assets/71498430/7de66c6f-b2fe-4342-8ff1-e86bf7f8f3b9)
![image](https://github.com/cabaletta/baritone/assets/71498430/b773b135-edab-44ea-aeb4-33d86f7d5338)
![image](https://github.com/cabaletta/baritone/assets/71498430/db04112d-0d52-4c6e-8d02-c5563d923285)
![image](https://github.com/cabaletta/baritone/assets/71498430/49cbb95d-abbf-4d49-98a0-13fba2935199)
![image](https://github.com/cabaletta/baritone/assets/71498430/ec88b878-3566-4fd5-8705-e568fcfde3b9)
![image](https://github.com/cabaletta/baritone/assets/71498430/3bc87200-59fe-493e-a6db-b545ab2148e9)

Fabric mods:

![image](https://github.com/cabaletta/baritone/assets/71498430/a82ffd0c-58d3-4e38-b96f-6c5bce1010de)

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-11-19 22:36
Duplicate of #4112

**Closed as completed by ZacSharp** 2023-11-19 22:36 UTC
Labels: bug, duplicate

**Comment by Tendas240** [comment] 2023-11-20 07:52
> Duplicate of #4112

this doesn't help. i read those discussions and people reference other posts but i still don't get what I'm suppossed to do to fix it. in this manner i'm just a user. no coding experience. so what exactly do i have to do?

**Comment by ZacSharp** [comment] 2023-11-20 19:57
You follow [the link](https://github.com/cabaletta/baritone/actions/workflows/gradle_build.yml?query=is%3Asuccess+event%3Apush) I gave you on the closed pull request, choose the latest (topmost) entry for your version (version is listed as branch), scroll down to the section labeled "Artifacts" and click on the file called "Artifacts" (only works while you are logged in). The "Artifacts.zip" you get from that contains all the files you know from the releases, just with funky version numbers.
Sorry if closing the issue with no further information is a bit harsh, it's just that after ~20 duplicates (some as uninformative as "`#mine` doesn't work", thanks for providing a log right away), I'm far from typing out an explanation without someone explicitly asking for it.
