### ISSUE TITLE
Baritone doesn't understand how to use boats

### ISSUE THREAD

**Issue by mhoivik** [cabaletta/baritone#4106] opened 2023-08-18 16:11 UTC
whenever I try to use boats to get over a sea with baritone, it simply tries to walk to the set cords as it would if it wasn't in a boat. it would be nice if Baritone used the boat it has at its disposal.

As it is now, especially in the pre-elytra early game it is incredibly slow to travel oversea

**Comment by scorbett123** [comment] 2023-08-18 16:14
Duplicate of #4034

**Closed by scorbett123** 2023-08-18 16:14 UTC
Labels: enhancement
