### ISSUE TITLE
Allow Stacked Commands

### ISSUE THREAD

**Issue by rjbarber** [cabaletta/baritone#2604] opened 2021-03-23 15:58 UTC
Allow Primary, Secondary, Tertiary commands that operate simultaneously and with some level of priority. Such as when pathing, Primary command would be goto xxxx yyyy, secondary command would be mine some_block, teriary command would be goto chest. The order of actions would be goto xxxx yyyy unless there is some_block in the vacinity (requires a WithinRange setting?) or if a chest is within range, goto chest. If no chest or block to mine within range, continue pathing.

**Comment by scorbett123** [comment] 2021-03-23 15:59
duplicate of #186

**Comment by l1ving** [comment] 2021-03-23 16:30
and of many others

**Closed by l1ving** 2021-03-23 16:30 UTC
Labels: duplicate
