### ISSUE TITLE
Check if block was protected by plugin

### ISSUE THREAD

**Issue by 5UP3R-D1N** [cabaletta/baritone#3277] opened 2022-02-22 07:47 UTC
## Describe your suggestion
Baritone is trying to break block that inside a protected area and it just break that block forever, so I suggest make it like :
3 attempt if the block keep appearing again, cancel and find new path

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

## Context
Baritone is so awesome, my every single modpack used baritone

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2022-03-04 21:31
Duplicate of #220

**Closed by ZacSharp** 2022-03-04 21:31 UTC
Labels: duplicate, enhancement
