### ISSUE TITLE
Have an option to disable Baritone's auto tool.

### ISSUE THREAD

**Issue by crypthusiast0** [cabaletta/baritone#1617] opened 2020-04-24 18:15 UTC
## Describe your suggestion
Basically what this function would do is disable Baritone's auto tool feature, so you can mine certain blocks not with the fastest tool. At first, this would sound useless, but on some servers, especially prison servers, require you to mine beacons with a pickaxe, rather than your hand.

## Context
As I said above, some servers require you to mine certain blocks with tools, even if in vanilla it isn't the fastest tool.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by dominikaaaa** [comment] 2020-04-24 18:17
Duplicate of #1334

**Closed by dominikaaaa** 2020-04-24 18:17 UTC
Labels: enhancement

**Comment by crypthusiast0** [comment] 2020-04-24 18:27
whoops
has the feature been implemented yet...?

**Comment by dominikaaaa** [comment] 2020-04-24 18:28
No
![2020-04-24-142845_463x107_scrot](https://user-images.githubusercontent.com/17222512/80244998-e9ad6680-8637-11ea-9641-a5e03f4f2236.png)

**Comment by djsuperS** [comment] 2021-02-05 22:25
so it just wont get added? or am i being stupid and it already is cuz i cant find it in pull requests

**Comment by l1ving** [comment] 2021-02-05 22:32
It is already implemented.

**Comment by djsuperS** [comment] 2021-02-05 22:36
well how do i use it if im alowed to ask because i cant find it anywhere
and when i go to all the other pages and use those commands it says its an invalid command

**Comment by l1ving** [comment] 2021-02-05 22:37
you're not running the latest commit then

**Comment by djsuperS** [comment] 2021-02-05 22:38
im running the 1.6.2 version rn
is there a later version?

**Comment by l1ving** [comment] 2021-02-05 22:39
commit, not version

**Comment by djsuperS** [comment] 2021-02-05 22:40
commit? sorry if im a bit anoying im really new to this so can you maybe explain commit

**Comment by djsuperS** [comment] 2021-02-05 22:51
ohhh ok sorry for asking im kinda stupid i just googled it

**Comment by djsuperS** [comment] 2021-02-05 23:02
ok im kinda lost ive found a version of wagyourtail but i really dont know how to install it

**Comment by Tytova** [comment] 2021-03-05 16:16
> commit, not version

and how do i install that? its 2021 already and still not added to baritone public version.....

**Comment by l1ving** [comment] 2021-03-05 16:56
yes it is. there just hasn't been a new release.

**Comment by Tytova** [comment] 2021-03-05 16:59
> yes it is. there just hasn't been a new release.

may i ask how to add it to my current release? can u tell me some steps please? that would be helpful!

**Comment by scorbett123** [comment] 2021-03-05 17:03
You would have to build it yourself, there are instructions for that.

**Comment by Tytova** [comment] 2021-03-05 17:07
> You would have to build it yourself, there are instructions for that.

can you please tell me where can i find those instructions?

**Comment by scorbett123** [comment] 2021-03-05 18:07
[https://github.com/cabaletta/baritone/blob/master/SETUP.md#build-it-yourself](https://github.com/cabaletta/baritone/blob/master/SETUP.md#build-it-yourself)

**Comment by Tytova** [comment] 2021-03-05 18:36
> https://github.com/cabaletta/baritone/blob/master/SETUP.md#build-it-yourself

sounds so complicated for a person like me lmao, may i ask why the autotool disable option didn't get added yet?

**Comment by ehylo** [comment] 2021-03-05 19:00
because a release isn't made everytime there is a commit

**Comment by l1ving** [comment] 2021-03-05 19:19
It did get added

**Comment by ehylo** [comment] 2021-03-05 19:57
reading through this I'm confused, it has been added, and it should be in 1.6.2 because #1947 was merged before that release just do `#disableAutoTool` and it should work.

**Comment by scorbett123** [comment] 2021-03-05 20:18
Most users are using 1.12.2, and that was released ages ago, I  believe 1.16 is the only one with it.

**Comment by l1ving** [comment] 2021-03-05 21:17
> reading through this I'm confused, it has been added, and it should be in 1.6.2 because #1947 was merged before that release just do `#disableAutoTool` and it should work.

The master branch has not been merged upwards as far as I know.

**Comment by Tytova** [comment] 2021-03-05 21:32
> Most users are using 1.12.2, and that was released ages ago, I believe 1.16 is the only one with it.

Im using 1.16 right now and it says the command is invalid, am i using a wrong version or it didn't get added to 1.16?

**Comment by scorbett123** [comment] 2021-03-05 21:57
> > reading through this I'm confused, it has been added, and it should be in 1.6.2 because #1947 was merged before that release just do `#disableAutoTool` and it should work.
> 
> The master branch has not been merged upwards as far as I know.

I believe it has in https://github.com/cabaletta/baritone/commit/98da14469175081b8b0b7c607ec786fb97598dce

**Comment by ehylo** [comment] 2021-03-06 00:46
> > reading through this I'm confused, it has been added, and it should be in 1.6.2 because #1947 was merged before that release just do `#disableAutoTool` and it should work.
> 
> The master branch has not been merged upwards as far as I know.

ah my bad, yeah it was added a while ago and master wasn't merged upwards until after 1.6.2, so 1.6.3 should have it but 1.6.2 probably doesn't have it

**Comment by l1ving** [comment] 2021-03-06 03:36
> > Most users are using 1.12.2, and that was released ages ago, I believe 1.16 is the only one with it.
> 
> Im using 1.16 right now and it says the command is invalid, am i using a wrong version or it didn't get added to 1.16?

The `master` branch likely wasn't merged upwards when making the release so you will have to wait for the next release

**Comment by Tytova** [comment] 2021-03-06 08:50
i just downloaded 1.16.5 baritone with fabric mod and still didn't find the command? .....

**Comment by scorbett123** [comment] 2021-03-06 12:14
> i just downloaded 1.16.5 baritone with fabric mod and still didn't find the command? .....

It works for me, make sure that you are doing #disableAutoTool, and that you are downloading it from [here](https://github.com/cabaletta/baritone/releases)

**Comment by Tytova** [comment] 2021-03-06 17:01
> > i just downloaded 1.16.5 baritone with fabric mod and still didn't find the command? .....
> 
> It works for me, make sure that you are doing #disableAutoTool, and that you are downloading it from [here](https://github.com/cabaletta/baritone/releases)

yes it worked, thanks daddy
