### ISSUE TITLE
#sel fill oak_planks crashes

### ISSUE THREAD

**Issue by LuckyMika** [cabaletta/baritone#3776] opened 2023-01-01 14:36 UTC
## Some information
Operating system: Windows 10
Java version: 17
Minecraft version: 1.18.2
Baritone version: 1.8.3
Other mods (if used): Optifabric, Optifine (latest)

## Exception, error or logs
[debug.log](https://github.com/cabaletta/baritone/files/10328912/debug.log)
[latest.log](https://github.com/cabaletta/baritone/files/10328913/latest.log)

## How to reproduce
1. Select an area using the sel commands
2. Use `sel fill oak_planks`

## Modified settings
allowDiagonalAscend
allowDiagonalDescend
allowParkour
allowParkourPlace
allowWalkOnBottomSlab
antiCheatCompatability
avoidance
chatControl
jumpPenalty
layerOrder

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2023-01-01 15:16
Duplicate of #3298

**Closed by ZacSharp** 2023-01-01 15:16 UTC
Labels: bug, duplicate

**Comment by ZacSharp** [comment] 2023-01-01 15:18
Fixed in #3308
