### ISSUE TITLE
.litematic files

### ISSUE THREAD

**Issue by C00kiemax** [cabaletta/baritone#3705] opened 2022-10-29 14:01 UTC
I want to ask if its possible to add .litematic files to build instead of .schematic files. Because schematica mod is dead and in updatet versions you have to use litematica.

**Comment by rycbar0** [comment] 2022-10-29 14:31
this is a comming feature. if you use 1.12, 1.16 or 1.17 you can install the newest CI build the get .litematic support.

**Comment by ZacSharp** [comment] 2022-10-29 21:52
Duplicate of #668

**Closed by ZacSharp** 2022-10-29 21:52 UTC
Labels: duplicate, enhancement
