### ISSUE TITLE
1.14.4 Wont Connect To Realms

### ISSUE THREAD

**Issue by Boonheadshot** [cabaletta/baritone#628] opened 2019-07-24 08:47 UTC
## Some information
Operating system: Windows 10
Java version: 8 211
Minecraft version: 1.14.4
Baritone version: 1.14.4
Forge mods (if used): na

## Exception, error or logs

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 24/07/19 09:39
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at dnc.f(SourceFile:537)
	at dnc.b(SourceFile:779)
	at dnc.a(SourceFile:766)
	at dnc.a(SourceFile:630)
	at cyc.e(SourceFile:954)
	at cyc.b(SourceFile:410)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at dnc.f(SourceFile:537)
	at dnc.b(SourceFile:779)
	at dnc.a(SourceFile:766)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 625, 55
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dkf.a(SourceFile:421)
	at cyc.b(SourceFile:1923)
	at cyc.b(SourceFile:430)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1287018304 bytes (1227 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.14.4-Baritone
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

## How to reproduce
Attempting to connect to a realm stays on connecting and then goes to saving world then crashes, works as expected on singleplayer and multiplayer.
## Final checklist
- [/ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ /] I have included logs, exceptions and / or steps to reproduce the issue.
- [ /] I have not used any OwO's or UwU's in this issue.

**Comment by Quiist** [comment] 2019-07-24 16:14
I have the same issue

**Comment by 0-x-2-2** [comment] 2019-07-24 19:22
This looks like a Minecraft issue 🤔

**Comment by Dreamotaye** [comment] 2019-07-24 23:41
Also having this issue.

**Comment by realflow100** [comment] 2019-07-24 23:46
Me too.

**Comment by leijurv** [comment] 2019-07-24 23:57
This is strange because it appears to be realms only (multiplayer works for me, well, at least hypixel does). also i dont have a realm lol

Can someone who's having this crash confirm that among realms and multiplayer, and among baritone and vanilla 1.14.4, the only combination that crashes is realms with baritone?

**Comment by Dreamotaye** [comment] 2019-07-24 23:58
i can confirm that 1.14.4 vanilla does work with realms but baritone does not

**Comment by leijurv** [comment] 2019-07-25 00:00
what about multiplayer baritone vs realms baritone?

**Comment by Dreamotaye** [comment] 2019-07-25 00:09
so with baritone im able to connect to multiplayer but i type .b mine ore1 ore2 and it doesnt work but it is not possible to connect to realms cause it crashes.

**Comment by realflow100** [comment] 2019-07-25 00:09
1.14.4 baritone singleplayer works for me. and baritone in multiplayer.
but i cant join any realms with baritone. if i try to. the game crashes. can join in vanilla.

**Comment by leijurv** [comment] 2019-07-25 00:16
ree

someone wanna whitelist leijurv on their realm so i can figure this out? XD

**Comment by Dreamotaye** [comment] 2019-07-25 00:43
i can get you added to my friends for a little so i can try to figure it out but can you msg me on discord @Dreamotaye#3900

**Comment by Krixsix** [comment] 2019-07-25 11:44
leijurv i invited you to a realm with op so you can test

**Comment by poosislayer** [comment] 2019-07-25 13:01
Huh, I accidentally found a weird way of fixing this issue, I tried joining mcplayhd.net and after about 20 seconds of the "joining world" screen, it gave me a connection lost window, after that I was able to join a realm.

**Comment by Boonheadshot** [comment] 2019-07-25 13:17
^Why does that work

**Comment by realflow100** [comment] 2019-07-25 17:04
works for me too. how?? thats the strangest workaround/fix ever. hopefully that means this can be fixed in a future update.

**Comment by og-seph** [comment] 2019-07-25 17:41
@poosislayer Solution worked for me to, Weird that this is a solution tho

**Comment by leijurv** [comment] 2019-07-25 23:04
Fixed by https://github.com/cabaletta/baritone/commit/2ca4c3042ac2f2f265d2626e92cbe1b95b7f8245

**Closed by leijurv** 2019-07-25 23:04 UTC
Labels: bug
