### ISSUE TITLE
A Queue for tasks

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [cabaletta/baritone#2981] opened 2021-09-01 18:49 UTC
## Describe your suggestion
U can say #mine oak_log 13 and the #q goto crafting_table and baritone is goind to mine 13 oak logs and then go to the next task in the queue go to the crafting table

## Settings
(blank)
## Context
U would not have to wait for the task to finish before doing another one
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by ZacSharp** [comment] 2021-09-01 19:41
Duplicate of #176

**Closed by ZacSharp** 2021-09-01 19:41 UTC
Labels: duplicate, enhancement
