### ISSUE TITLE
Mode for highlighting targets, goals, or paths, without AI activating?

### ISSUE THREAD

**Issue by iamlcarus** [cabaletta/baritone#1663] opened 2020-05-05 11:06 UTC
So, Baritone highlights things when given a command. It will highlight potential targets when told to mine a certain block, or highlight a path showing where the AI will go.
The idea is that it would allow for using Baritone as a form of X-Ray when used standalone, or perhaps simply using the pathfinding function to tell the player where they should go.
I know Baritone will automatically mine and move for you, but an issue with this is that it doesn't always take hostile mobs into account that well, and more often than not telling it to mine or go somewhere has it take me straight into a creeper.
Giving the player the ability to control how they react to these things could be one solution to this issue.

**Comment by dominikaaaa** [comment] 2020-05-05 13:15
Duplicate of #928

**Closed by dominikaaaa** 2020-05-05 13:15 UTC
