### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Zenker64774** [cabaletta/baritone#3347] opened 2022-03-21 12:51 UTC
## Some information
Operating system: Windows 10
Java version: ???
Minecraft version: 1.18.2
Baritone version: ???
Other mods (if used): 

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue

Linux: `~/.minecraft/logs/`

Windows: `%appdata%/.minecraft/logs/`

Mac: `/Library/Application\ Support/minecraft/logs/`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

## Modified settings
To get the modified settings run `#modified` in game

## Final checklist
- [x] I know how to properly use check boxes 
- [ ] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [ ] I have included logs, exceptions and / or steps to reproduce the issue.
- [ ] I have not used any OwO's or UwU's in this issue.
Who knows how to solve this error in baritone ?? I 'm playing on version 1.18.2 .
Baritonel an unhandled exception occurred, the error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues

**Comment by wagyourtail** [comment] 2022-03-21 14:35
Duplicate of the pinned issue. Please learn to read

**Closed by wagyourtail** 2022-03-21 14:35 UTC
Labels: bug

**Comment by wagyourtail** [comment] 2022-03-21 14:38
also why'd you create this same issue 3 times and then NOT actually fill in any further details.... at least title it.
