### ISSUE TITLE
Adding Litematic support in Baritone

### ISSUE THREAD

**Issue by NormalHuman-Anything** [cabaletta/baritone#3267] opened 2022-02-14 02:23 UTC
## Describe your suggestion
With as much detail as possible, describe what your suggestion would do for Baritone.

in baritone commands, there is schematics command, but it does not litematic file

## Settings
If applicable, what settings/customizability should be offered to tweak the functionality of your suggestion.

how abput adding Litematic commands because in newer version, schematic is not available(like 1.18.1

## Context
Describe how your suggestion would improve Baritone, or the reason behind it being added.

can build bigger structures in newer version servers

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by scorbett123** [comment] 2022-02-14 13:52
Duplicate of #668.

**Closed by scorbett123** 2022-02-14 13:52 UTC
Labels: enhancement
